bnb-chain/bsc

- consensus/parlia/parlia.go
- eth/api_tracer.go
This pr contains two parts:
1. As we are going to support gov func, most work have been done in GovHub system contract, but the consensus engine needs to init govHub/tokenHub/RelayerIncentivize Contracts after genesis block.
2. Also, we apply more strick condition for a system transaction, the gas-price of a system transaction is zero, to avoid the misjudge of a transaction sent by a validator, safer with this condition.
> [R4R]add gov/tokenHub/RelayerIncentivize contracts to the init list and apply  strict condition for system transaction 

- consensus/parlia/parlia.go
A validator failed to sync a block produced by itself,  because in previous logic,  we decide if it is mining by whether the producer of the block is the validator of Parlia consensus engine or not.
> [R4R]fix validator failed to sync a block produced by itself,  resolve #3

- eth/fetcher/block_fetcher.go
- miner/worker.go
In mainnet, bsc will have 21 validators. It will reach finality after 11 blocks. resolve #7
Meaning :
1. `BlockFetcher`: block fetcher will ignore block who's num is before `currentNum-maxUncleDist`.
2. `staleThreshold`: miner module will clean works that before `currentNum-staleThreshold`.
3. `miningLogAtDepth`: will report finality when one block is `miningLogAtDepth` before `currentNum`.
> [R4R] modify params for Parlia consensus with 21 validators

- consensus/parlia/parlia.go
- miner/worker.go
- params/protocol_params.go
Currently clique and parlia do not check the gas-limit and gas-used, it may cause security issue.
However, because of the system transactions, the gas-used of parlia implement may exceed the gas-limit, so we reserve about 100000 gas for system transactions. For now system transaction cost 22,748+ 1,516 + 24,439 = 48703 gas at most. resolve issue #9
> [R4R]add gas limit check in parlia implement

- consensus/parlia/parlia.go
According to the design https://docs.google.com/document/d/1g0sQKHYmNGMuvJxl3qKbuaNkwuq_prNKviJtPqgmkew/edit?usp=sharing, we will introduce disable/enable channel func.
Liveness slash may fail when the channel is disabled, so do not panic under such situation
> [R4R]Allow liveness slash fail

- params/protocol_params.go
Have test slash transaction when there are 41 validators, the max gas consumption could be 434543,  adjust SystemTxsGas to  500000 would be safe
> [R4R]reestimate the gas consumption for system tx when there is 41 validator

- cmd/geth/retesteth.go
- consensus/parlia/parlia.go
- consensus/parlia/parlia_test.go
- consensus/parlia/ramanujanfork.go
- consensus/parlia/snapshot.go
- core/genesis.go
- eth/fetcher/block_fetcher.go
- params/config.go
Currently it is specified in the consensus protocol that out-of-turn validators have to wait a randomized amount of time before sealing the block. It is currently implemented in the client-side node software and works with the assumption that validators would run the canonical version.
However, given that validators would be economically incentivized to seal blocks as soon as possible, it would be possible that the validators would run a modified version of the node software to ignore such a delay.
This pr targets to enforce the wait time through the use of a verifiable delay function:
1. Take the height of the block as the seed of the randomizer.
2. generate the back-off metrics and shuffle it by above randomizer.
3. use the distance between the validator and the in-turn validator as …
> [R4R]enforce backoff time for out-turn validator

- consensus/parlia/parlia.go
While syncing, this log is very annoying and it consumes a lot of space for log file
> Disable noisy log from consensus engine

- Dockerfile
We need build a kubernets data-seed cluster, and we want to add `curl` cmd to the running docker instance, so that we can use it to test whether the node is catch up not not, as a metrics of readiness.
Just add `curl` in docker file
* ...
...
> [R4R]add curl in docker image

- les/server_handler.go
This PR fixes a bug in GetProofsV2 request serving that could potentially cause a panic because of header being nil.
A DoS vulnerability can make a LES server crash via malicious GetProofsV2 request from a connected LES client.
Mirror PR:  https://github.com/ethereum/go-ethereum/pull/21896
advisories: https://github.com/ethereum/go-ethereum/security/advisories/GHSA-r33q-22hv-j29q
This vulnerability only concerns users explicitly enabling les server; disabling les prevents the exploit.
...
> [R4R]les: fix GetProofsV2 bug (#21896)

- eth/filters/api.go
- eth/filters/filter_system.go
Fix the potential deadlock of pub/sub module.
More detail in: https://github.com/binance-chain/bsc/issues/58
The deadlock dependency is:
Routine A:NewPendingTransactionFilter want to lock filtersMu to consume hashes;
Routine B: eventLoop is waiting Routine A to consume hashes so that it can push new hash to channel.
Routine C: Unsubscribe is holding lock filtersMu, but it is waiting for Routine B to consume uninstall channel.
There is no need to fetch lock on `NewPendingTransactionFilter` routine, so just loose the logic.
And fix the potential risk that `Unsubscribe` routine does not drain all the `hash`, `header` and `log`. 
...
> [R4R]fix potential deadlock of pub/sub module

- rpc/handler.go
- rpc/metrics.go
We need to do statistics of different kinds of requests, so add request count gauge for each kind of request.
Metrics change.
No
Add more monitor dashboard
...
No
> [R4R]add rpc method request gauge

- rpc/client.go
- rpc/handler.go
- rpc/http.go
- rpc/server.go
For some infura service, bsc client may run on Cloud behind CDN/ALB, there is a requirement for these node to know the client IP to trouble shoot some issue.
Just add the one more log message
* ...
...
> [R4R] Add `x-forward-for` log message when handle message failed

- consensus/parlia/parlia.go
- consensus/parlia/snapshot.go
- core/forkid/forkid.go
- eth/backend.go
- les/client.go
- params/protocol_params.go
- BEP-87: Visual Fork of Binance Smart Chain
- [1. Summary](#1-summary)
- [2. Abstract](#2-abstract)
- [3. Status](#3-status)
- [4. Motivation](#4-motivation)
- [5. Specification](#5-specification)
- [5.1 Fork Hash](#51-fork-hash)
- [5.2 Vanity](#52-vanity)
- [5.3 Vanity](#53-clients)
- [5.4 Backwards Compatibility](#54-backwards-compatibility)
- [6. License](#6-license)
This BEP describes a proposal to enable the chain to display the whole view of validators that on different upcoming forks.  
The four bytes of `Header.Extra[28:32]` will be fulfilled with `NEXT_FORK_HASH`. The `NEXT_FORK_HASH` indicates which fork the signer of this block is going to stay on. By analysing `N` (`N` is the amount of validators) continuous block headers, we are able to know which fork is supported by the …
> [R4R]support fork id in header; elegant upgrade

- accounts/abi/type.go
- cmd/clef/docs/setup.md
- consensus/ethash/algorithm.go
- core/tx_pool.go
- internal/ethapi/api.go
- internal/web3ext/web3ext.go
- p2p/discover/v5_udp.go
- p2p/enode/nodedb.go
- rpc/json.go
- rpc/testdata/invalid-batch.js
- rpc/testdata/invalid-nonobj.js
- signer/storage/aes_gcm_storage.go
BSC001: Integer Overflow when generating ethash dataset
It is fixed on go-ethereum: https://github.com/ethereum/go-ethereum/pull/21793
BSC002: AES GCM return value improper validation possibly leading to Denial of Service
It is fixed on go-ethereum: https://github.com/ethereum/go-ethereum/pull/21379 
BSC003: Off-by-one error in queuing a batch of transactions
It is fixed on go-ethereum: https://github.com/ethereum/go-ethereum/pull/21683 
BSC004: DoEstimateGas improper validation possibly leading to Denial of Service
It is fixed on go-ethereum: https://github.com/ethereum/go-ethereum/pull/21601
BSC005: Missing validation after unmarshalling RPC JSON message
It is fixed on go-ethereum: https://github.com/ethereum/go-ethereum/pull/21497 
BSC006: Type Confusion when handling a dynamic type …
> [R4R] security patch from go-ethereum

- consensus/parlia/parlia.go
If a new node sync from genesis, it will keep get a warning , which is confusing to users, so let us make it a debug level.
* ...
...
> [R4R]change the fork waring to debug to avoid confusion

- Dockerfile
add tini for docker image
If we don't have tini in docker image , we can't kill bsc container gracefully
None
* add tini for docker image in Dockerfile
* ...
...
> add tini for docker image

- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- eth/backend.go
- eth/config.go
- eth/handler.go
- eth/handler_test.go
- eth/helper_test.go
- eth/protocol_test.go
- node/config.go
Add a new `directbroadcast` flag, when it is enabled, the node will broadcast its block to all peers.
There is some empty block in main-net, parts of the reason the block propagation latency, we add this flag to relieve such situation. start the node with `--directbroadcast` to enable this feature.
...
> [R4R]enable directbroadcast flag to decrease the block propagation time 

- accounts/abi/bind/backends/simulated.go
- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- eth/backend.go
- eth/config.go
- eth/filters/api.go
- eth/filters/bench_test.go
- eth/filters/filter.go
- eth/filters/filter_system_test.go
- eth/filters/filter_test.go
- graphql/graphql.go
- les/client.go
- node/config.go
`GetLog` API with unlimited block range will consume huge CPU and IO resource, which has import great pressure to our data seed nodes. As a result, our data seed node always can't sync recent blocks.
Add `--rangelimit` flag to our geth. If a node started with this flag, a default block range limit will be applied to `GetLog` API, thus the pressure to BSC node will be reduced.
* ...
...
> R4R: limit range get log

- cmd/faucet/website.go
- cmd/geth/chaincmd.go
- cmd/geth/main.go
- cmd/geth/retesteth.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- consensus/clique/clique.go
- consensus/consensus.go
- consensus/ethash/consensus.go
- consensus/parlia/parlia.go
- eth/config.go
- miner/miner.go
- miner/worker.go
The `miner worker` together with `parlia consensus` has a defect that if the previous validator produces a large block or propagate the block to the next validator later than 3 seconds,  if the next validator still tries to include tx as much as possible, it will eventually produce an empty block. This PR target to solve this issue.
We add a new interface of consensus engine: `Delay()`, which is special designed for the consensus engine that has a fixed blocking time. If the miner is working on commit tx and found that it reach the `Delay()-delayLeftOver` time, it will stop commit tx and seal a block, so that the empty block can be avoid.
an new option is added:
```
--miner.delayleftover 50000000
```
* ...
...
... reference …
> [R4R]apply max commit tx time for miner worker

- consensus/consensus.go
- consensus/parlia/parlia.go
- consensus/parlia/snapshot.go
- core/blockchain.go
If the validators of BSC run prune state node, it will write state in period. However, the write operation will take more than 3 seconds, it may get the validator been slashed or the next validator will generate an empty block.
This PR is to fix this without running in archive mode.
What we introduce:
The validators are scheduled to generate blocks in order, it is safe to write when the validator still far from its  turn to generate blocks.
No
The condition to write block state. No affect to data-seed
...
> [R4R]validator only write database state when enough distance

- internal/ethapi/api.go
- rpc/handler.go
- rpc/metrics.go
We need a health check endpoint to detect whether the RPC func of a node is ok.
Decide to use the rpc latency as the health metrics.
* ...
...
> [R4R]add health check endpoint

- core/blockchain.go
Increase the cache size of receiptsCacheLimit to improve the performance
* ...
...
> [R4R]update receiptsCacheLimit to 10000

- core/state/pruner/pruner.go
- core/state/snapshot/snapshot.go
- les/peer.go
The pruning tool is broken, and add layer 1 as the scope of the prune target.
Fix the prune tool
* ...
...
> [R4R] make prune tool available

- core/blockchain.go
Fix the disk increase dramaticly issue
currently, 2.5G cache is not enough to hold the dirty cache of recent 1024 blocks.
It will trigger Cap to reduce the cache size.
Becuase dirty cache is written to disk.
`Dereference` here will not work..
* ...
...
> [R4R]fix disk increase dramaticly issue

- eth/peer.go
There is a dead lock issue in the Reorg routine of Transaction Pool implement of v1.0.7, which is already fixed in the latest geth v1.10.2 version. The randomly ungraceful shutdown connection between the upgrade version and current version trigger the deadlock, it is rarely happen . Why the connection is ungraceful shutdown is not very clear(connection upgraceful shutdown is very common actually), but we obviously need tolerate this.
https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/eth/protocols/eth/broadcast.go#L122
* ...
...
> [R4R]fix the reorg routine stuck issue

- CHANGELOG.md
- params/version.go
BUGFIX
* [\#190](https://github.com/binance-chain/bsc/pull/190) fix disk increase dramaticly
* [\#191](https://github.com/binance-chain/bsc/pull/191) fix the reorg routine of tx pool stuck issue
* ...
...
> [R4r]prepare for release v1.0.7-hf.1

- CHANGELOG.md
- params/version.go
This is a maintained release.
BUGFIX
* [\#194](https://github.com/binance-chain/bsc/pull/194) bump btcd to v0.20.1-beta
> [R4R]prepare release  v1.0.7-hf.2

- consensus/parlia/parlia.go
- consensus/parlia/snapshot.go
- eth/backend.go
Fix validator failed to produce a block occasionally.
The issue is caused by the persistence action, it takes around 48 seconds, so the validator do not have time to produce the block.
```
t=2021-05-17T07:49:55+0000 lvl=info msg="Imported new chain segment"            blocks=1   txs=517   mgas=46.932   elapsed=218.339ms   mgasps=214.950  number=7,482,287 hash=0x2a7769438c9d64ce5192        41e99414e75890a37e568db6b24b7daf5dc3814158e8 dirty="2.00 GiB"
t=2021-05-17T07:50:41+0000 lvl=info msg="Persisted trie from memory database"   nodes=5,205,776 size="1.10 GiB"   time=43.360182272s gcnodes=47,892,102 gcsize="16.62 GiB" gctime=2m53.758774587s l        ivenodes=1,017,189 livesize="323.76 MiB"
t=2021-05-17T07:50:41+0000 lvl=info msg="Imported new chain segment"            blocks=1   txs=360 …
```
> [R4R]use more aggressive write cache policy

- core/vm/gen_structlog.go
- core/vm/logger.go
- core/vm/logger_json.go
- eth/tracers/tracers_test.go
- internal/ethapi/api.go
Improves the performance of debug.traceTransaction
Description
Cherry-pick the commit https://github.com/ethereum/go-ethereum/pull/23016
> eth/tracers: improve tracing performance (#23016)

- eth/fetcher/block_fetcher.go
If a fork block is generated, the fork block is write faster than the original block, which will cause the subsequent block write delay.
Put the blocks that cannot find the parent block into the queue, wait for the parent block to write, and then import it.
> [R4R]fix: block fetcher efficiency

- cmd/utils/flags.go
- core/blockchain.go
Flag `--triesInMemory` specified but does not work.
> fix: TriesInmemory specified but not work

- miner/miner.go
Fix https://github.com/binance-chain/bsc/issues/341
release v1.1.1-beta will not copy state anymore during proposing block to improve the performance, so that the pending block is null, this PR target to fix it.
* ...
...
> [R3R]fix pending block null issue

- core/state/trie_prefetcher.go
Fix issue https://github.com/binance-chain/bsc/issues/365
The current implementation may abort the subfetcher concurrently, it is not threadsafe.
No
We setup a new routine to process the abort of subfetcher.
...
> [R4R]fix double close channel of subfetcher

- CHANGELOG.md
- params/version.go
release v1.1.1
A stable release v1.1.1
None
Minor fix:
*[\#350](https://github.com/binance-chain/bsc/pull/350) flag: fix TriesInmemory specified but not work
*[\#355](https://github.com/binance-chain/bsc/pull/355) miner should propose block on a proper fork
*[\#358](https://github.com/binance-chain/bsc/pull/358) miner: fix null pending block
*[\#360](https://github.com/binance-chain/bsc/pull/360) pruner: fix state bloom sync permission in Windows 
...
> [R4R]prepare release v1.1.1

- eth/state_accessor.go
- eth/tracers/api.go
This PR fixes getting the wrong state via `stateAtTransaction`
Due to Parlia consensus that BSC uses, `stateAtTransaction` should include additional checks.  
Before mining the block, validator adds to additional transactions to the end of the block, but before the transactions will be made the validator's balance is changing in [parlia.go](https://github.com/binance-chain/bsc/blob/master/consensus/parlia/parlia.go#L1010).  
While tracing the transaction via `debug_traceTransaction` the state is retrieved through [`StateAtTransaction`](https://github.com/binance-chain/bsc/blob/master/eth/tracers/api.go#L730) but there is no any checks whether the transaction is system during the generation of the state.  
This check is present in …
> fix: tracing system transactions failed due to wrong state

- core/vm/analysis.go
- core/vm/analysis_test.go
- core/vm/instructions.go
This makes the analysis for code/data faster, and more evenly spread. Previously, the worst-performing case was PUSH7.
PUSH1 started at ~40ns, and going upwards towards 50ms at PUSH7.
This PR doesn't improve the PUSH1 situation, but does markedly improve the (previous) worst-case quite a lot, and also the normal-case (for code which is not push).
The origin PR: https://github.com/ethereum/go-ethereum/pull/23381
> [R4R]core/vm: faster code analysis (#23381)

- .github/generate_change_log.sh
- .github/release.env
- .github/workflows/release.yml
Publish new release page when the new tag was push
N/A
New workflow:
1. update changelog into `CHANGELOG.md`
2. update the version name of `params/version.go`
3. make a new tag from the `master` branch
4. push tag
*Notice*
Please make sure `CHANGELOG.md` contains the tag with format `## v...`(ex: ## v1.1.2)
And ci pipeline will get the content below the tag as release body.
*Addition*
If you want to change `mainnet.zip` or `testnet.zip`, please update the download URL to `.github/release.env` with the name `MAINNET_FILE_URL` and `TESTNET_FILE_URL`.
Example of a release page made by ci: https://github.com/j75689/bsc/releases/tag/v1.1.2
* add `.github/generate_change_log.sh`
* add `.github/release.env`
* add `.github/workflows/release.yml`
N/A
N/A
> ci pipeline for release page

- eth/filters/api.go
- eth/filters/filter_system.go
Please see #388 
This issue cause by https://github.com/binance-chain/bsc/pull/59
Now the deadlock issue fix by official https://github.com/ethereum/go-ethereum/pull/22178
So just need to revert https://github.com/binance-chain/bsc/pull/59. 
`go test -race ./eth/filters/...`
```
ok      github.com/ethereum/go-ethereum/eth/filters     6.639s
```
- revert commit `3d3f9694a426eafc32640a643b5399a58209da1c`
N/A
#388
> fix: nil pointer issue (#388)

- eth/downloader/downloader.go
fix https://github.com/binance-chain/bsc/issues/404
The downloader need check whether header is nil or not before using it.
No
* ...
...
> [R4R]fix nil point in downloader

- core/state/snapshot/iterator.go
fixed typo.
* strorage -> storage
...
> core/state/snapshot: fix typo

- core/block_validator.go
- core/state/statedb.go
1.Fix panic in trie_prefetcher close
2.Fix trie_prefetcher abortLoop goroutine leak 
1.In ValidateState, there are three goroutines running concurrently, if the previous one return error, the upper caller function InsertChain would return and call it's defer function to close prefetcher, while the IntermediateRoot goroutine still run and when it done call its defer function to close prefetcher, this time the prefetcher is nil, so it will trigger a panic. So we should wait all the goroutines done in ValidateState to avoid this panic.
2.In InsertChain, if we enable diffsync, and insert two more blocks here, then all the blocks except the last one wound't do call StopPrefetcher, so these blocks' abortLoop goroutine will leak. So we should do the StopPrefetcher in IntermediateRoot to avoid …
> [R4R]fix prefetcher related bugs

- internal/ethapi/api.go
Add needToReplay condition to accelerate eth_getDiffAccountsWithScope
Replay the whole block spend too much time, actually we need't do that, so add an quick way to decide whether to replay the block.
* ...
...
> Accelerate get diff accounts with scope

- eth/handler_diff.go
fix: graceful shutdown bug
1. `delete(ps.diffWait, id)` while  the handshake fails on `handler_diff.go`
```
goroutine 21121611 [chan receive, 9 minutes]:
github.com/ethereum/go-ethereum/eth.(*peerSet).waitDiffExtension(0xc0027f8230, 0xc0d4793c00, 0xc266559f40, 0x0, 0x0)
github.com/ethereum/go-ethereum/eth/peerset.go:206 +0x20c
github.com/ethereum/go-ethereum/eth.(*handler).runEthPeer(0xc0002990e0, 0xc0d4793c00, 0xc207a63a10, 0x0, 0x0)
github.com/ethereum/go-ethereum/eth/handler.go:261 +0x1db
github.com/ethereum/go-ethereum/eth.(*ethHandler).RunPeer(0xc0002990e0, 0xc0d4793c00, 0xc207a63a10, 0xc0d1709540, 0x7f7d641990e0)
github.com/ethereum/go-ethereum/eth/handler_eth.go:46 +0x3f
github.com/ethereum/go-ethereum/eth/protocols/eth.MakeProtocols.func1(0xc24b3a55c0, 0x1b02cb8, 0xc0d1709540, …
```
> [R4R] fix: graceful shutdown bug

- cmd/utils/flags.go
- core/blockchain.go
- core/blockchain_diff_test.go
- core/state_processor.go
- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
- eth/downloader/queue.go
- eth/downloader/resultstore.go
- eth/ethconfig/config.go
- eth/handler_diff.go
- eth/protocols/diff/handler.go
- node/node.go
This pr focus on the detailed improvement of diff sync.
The diff sync protocol does not behave well as we expected:
1. A peer gets less than 50% chance to diff sync.
2. A peer may receive duplicated diff layer.
3. The diff layer cache may pop recent difflayer.
4. Open too many files issue when enable `persist diff` 
5. The received difflayers maybe dropped once disconnected with the peer.
No
No
> [R4R] improve the protocol details of Diff sync

- core/blockchain.go
- core/error.go
- core/state/statedb.go
- internal/ethapi/api.go
Signed-off-by: Keefe-Liu <bianze.kernel@gmail.com>
Get block's diff accounts by replaying block when diff layer not found.
The diff layer just can cache for a few days, when there is no diff layer, the eth_getDiffAccounts API couldn't work, in this case we should replay the block and get the diff accounts, it may slow but i can work right.
* ...
...
> get diff accounts by replaying block when diff layer not found

- CHANGELOG.md
- params/config.go
- params/version.go
BUGFIX
* [\#509](https://github.com/binance-chain/bsc/pull/509) fix graceful shutdown bug
IMPROVEMENT
* [\#527](https://github.com/binance-chain/bsc/pull/527) improve diffsync protocol in many aspects
* [\#493](https://github.com/binance-chain/bsc/pull/493) implement fast getDiffAccountsWithScope API
...
> prepare for release v.1.1.5

- CHANGELOG.md
- core/blockchain.go
- core/error.go
- core/state/statedb.go
- internal/ethapi/api.go
- params/config.go
- params/version.go
v1.1.5 is a hard fork release. 
v1.1.5 brings Bruno hard fork which introduces a real-time burning mechanism into the economic model of BSC. Please refer to BEP95 for more details. The Bruno hard fork is expected to happen at block height xxx. The current block generation speed forecasts this to occur around November 30th at 08:00 AM (UTC). All clients are recommended to upgrade by November 30th.
We improved the diffsync protocol in this release and rolled it out as a stable feature. Diff sync improves the syncing speed by 60%～70% approximately according to the test. All full nodes are suggested to enable it by adding `--diffsync` in the starting command. Refer to BEP93 for more details.
BUGFIX
* [\#509](https://github.com/binance-chain/bsc/pull/509) fix graceful shutdown bug
IMPROVEMENT …
> Release v1.1.5

- PULL_REQUEST_TEMPLATE
We just remove the unnecessary parts of our PR template, as we have a fine CI/CD workflow now.
1. `Preflight checks` is unnecessary because we get CI/CD checks now.
2. `Already reviewed by ` is unnecessary, since the reviewer would approve the PR if it is ok.
3. `Related issues` is unnecessary, since we should attach the issue in the description part.
No
No
> [R4R]remove unnecessary part in PR template

- eth/protocols/snap/handler.go
- trie/trie.go
This PR cherry-pock the DoS vulnerabilities fixed in  go-ethereum v1.10.9.
check issue https://github.com/binance-chain/bsc/issues/583
A vulnerable node is susceptible to crash when processing a maliciously crafted message from a peer, via the snap/1 protocol. The crash can be triggered by sending a malicious snap/1 GetTrieNodes package.
More details please check the [report](https://github.com/ethereum/go-ethereum/security/advisories/GHSA-59hh-656j-3p7v) and the [upstream PR](https://github.com/ethereum/go-ethereum/pull/23657)
None
https://github.com/ethereum/go-ethereum/pull/23657
> [R4R]eth/protocols/snap, trie: better error-handling (#23657)

- go.mod
- go.sum
merge goleveldb changes on memory alloction
1. Reduce memory allocation of buffer_pool and db util/buffer_pool, db: Reduce memory allocation syndtr/goleveldb#367
2. snappy-4.0.0 upgrade Updated snappy version syndtr/goleveldb#365
it is already merged in geth
this update help reducing memory allocation of leveldb , 
after tested on full sync mode , the updated leveldb will reduce the memory usage by 4%-5%, and it is more stable from the memory curve
> go.mod: update goleveldb

- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- core/events.go
- core/tx_pool.go
- core/tx_pool_test.go
- core/types/transaction.go
- eth/handler.go
- eth/handler_eth_test.go
- eth/handler_test.go
- eth/peerset.go
When the network traffic is heavy, transactions that have been broadcast may be truncated in peers' tx_pools, while these local pending transactions have been marked as known, the source node won't broadcast them again, so they have no chance to be mined. 
We add a timer to check whether the local pending transactions stay in tx_pool exceed a threshold, once transactions exceed the threshold, they will be announced to some peers again. The  TxPool.ReannounceTime is used to control the threshold,  the default value of TxPool.ReannounceTime is too big to be exceeded, users can config this parameter to enable this feature.
Also need to pay attention, this feature only announce the local pending transactions. If your node is configured TxPool.NoLocals=false, then the transactions sent to this …
> [R4R]reannounce local pending transactions

- .github/generate_change_log.sh
- .github/workflows/pre-release.yml
In order to make it easier to test before the new version is released, make a CI flow of the pre-release version to testing before the official release.
This ci process will draft a pre-release page, but will not publish it.
**Notice: please tag a new version with `pre-` prefix.**
* .github/workflows/pre-release.yml
* .github/workflows/release.yml
* .github/generate_change_log.sh
> [R4R] pre-release ci flow

- CHANGELOG.md
- params/version.go
This is a hotfix version. including a DoS issue fix from go-ethereum, leveldb improvement from go-ethereum, and a feature to improve p2p tx broadcast function.
BUGFIX
* [\#582](https://github.com/binance-chain/bsc/pull/582) the DoS vulnerabilities fixed in go-ethereum v1.10.9
IMPROVEMENT
* [\#578](https://github.com/binance-chain/bsc/pull/578) reduce memory allocation and upgrade snappy version
FEATURES
* [\#570](https://github.com/binance-chain/bsc/pull/570) reannounce local pending transactions
> prepare for release v.1.1.6

- .github/generate_change_log.sh
- .github/workflows/pre-release.yml
- CHANGELOG.md
- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- core/events.go
- core/tx_pool.go
- core/tx_pool_test.go
- core/types/transaction.go
- eth/handler.go
- eth/handler_eth_test.go
- eth/handler_test.go
- eth/peerset.go
- eth/protocols/snap/handler.go
- go.mod
- go.sum
- params/version.go
- trie/trie.go
This is a hotfix version. including a DoS issue fix from go-ethereum, leveldb improvement from go-ethereum, and a feature to improve p2p tx broadcast function.
This feature is introduced to handle some extreme situations, it won't affect the original function, and it is disabled by default. Users can enable this feature by setting TxPool.ReannouceTime according to their needs.
```bash
geth --config ./config.toml --datadir ./node --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0 --txpool.reannouncetime 5m
```
BUGFIX
* [\#582](https://github.com/binance-chain/bsc/pull/582) the DoS vulnerabilities fixed in go-ethereum v1.10.9
IMPROVEMENT
* [\#578](https://github.com/binance-chain/bsc/pull/578) reduce memory allocation and upgrade snappy version
FEATURES
* …
> release v1.1.6

- eth/handler.go
The previous logic of reannouncing transactions is a little bit redundant, we reorganize the logic to replace the double loop. 
The function has not changed, just reorganize the code to make it look more concise.
`go test -v -run TestTransactionPendingReannounce ./eth/*.go`
`--- PASS: TestTransactionPendingReannounce (0.62s)`
No
> [R4R]reorganize the logic of reannouncing transactions

- .github/release.env
- CHANGELOG.md
- core/blockchain_diff_test.go
- core/state_processor.go
- params/version.go
This PR is to fix a possible inconsistent state when doing diffsync. Since it is a syncing vulnerability which impact many clients, will release v1.1.7 especially for this patch.
Diffsync will assemble the modification to MPT and snapshot according to the received difflayer and verify against the block header.  In some cases(will disclose in future), the modification to MPT and snapshot is incorrect.
The  problematic logic is apply too stick condition to modify the smart contract trie: https://github.com/binance-chain/bsc/blob/0b575443c43f47f2f50ed5549d2bcaf7ccc39ab4/core/state_processor.go#L256
The current release, if you come across with *bad block* error with log message like: `expected tx hash xx, get xx, nonce xx, to xx, value xx, gas xx, gasPrice xx, data xx`. Here are some steps …
> [R4R]fix state inconsistent when doing diffsync

- eth/handler_eth_test.go
- eth/peerset.go
- eth/protocols/diff/handshake.go
- p2p/peer.go
- p2p/server.go
- p2p/server_test.go
For now, when accepting p2p peers in p2p server, we will run `runEthPeer` and `RunPeer` in `diffHandler` and `snapHandler` concurrently, so sometimes `runEthPeer` will hang there for waiting for the signal that it missed before it runninng. 
This will cause we can not stop the bsc node gracefully, so we add a timeout for stopping p2p server and a timeout for handling p2p peers.
When we can not stop the bsc node gracefully, we will see this in the profile:
``` go
goroutine 78355508 [chan receive, 100 minutes]:
github.com/ethereum/go-ethereum/eth.(*peerSet).waitDiffExtension(0xc000eb69b0, 0xc06931f5e0)
github.com/ethereum/go-ethereum/eth/peerset.go:206 +0x17e
github.com/ethereum/go-ethereum/eth.(*handler).runEthPeer(0xc0031fe000, 0xc06931f5e0, 0xc193063f68) …
```
> [R4R] add timeout for stopping p2p server

- trie/proof.go
- trie/proof_test.go
Fix "panic: deletion not supported" bug, cherry-pick from https://github.com/ethereum/go-ethereum/pull/23960
Return error when range contains deletion at `VerifyRangeProof`, then when trie update, the deletion value won't get there, the panic won't be triggered.
```
go test -v -run TestEmptyValueRangeProof ./trie/*.go
=== RUN   TestEmptyValueRangeProof
--- PASS: TestEmptyValueRangeProof (0.01s)
```
#475 
#576
> trie: reject deletions when verifying range proofs

- core/blockchain.go
- core/blockchain_diff_test.go
- core/state_prefetcher.go
- core/state_processor.go
By improving the snapshot clean cache hit rate, we can improve the capacity of BSC further.
According to the test, the cache hitting rate on BSC is about 94%, while the miss 6% IO will cost 32% of execution time.
We try to preload the state from DB by applying the transactions in advance. It turns out the execution  time was reduced by 30%-40%  
Verified on testnet and mainnet.
No impact to users
> [R4R]prefetch state by applying the transactions within one block

- .github/generate_change_log.sh
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
The release page adds the binary file of the ARM system.
Github Action doesn't provide the origin ARM OS runner. 
So the binaries of ARM will be built by `xgo` tools.
```
make geth-linux-arm
```
*NOTE*: `xgo` lib does not support go modules, please make sure your code files are under the path `$GOPATH/src`
* add arm binaries for release pipeline
[#712](https://github.com/binance-chain/bsc/issues/712)
> [R4R] add ARM binaries for release pipeline

- .gitignore
- cmd/geth/chaincmd.go
- cmd/geth/dbcmd.go
- cmd/geth/main.go
- cmd/geth/pruneblock_test.go
- cmd/geth/snapshot.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- core/blockchain.go
- core/blockchain_repair_test.go
- core/blockchain_sethead_test.go
- core/blockchain_snapshot_test.go
- core/blockchain_test.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_chain_test.go
- core/rawdb/chain_iterator.go
- core/rawdb/database.go
- core/rawdb/freezer.go
- core/rawdb/schema.go
- core/rawdb/table.go
- core/state/pruner/pruner.go
- eth/downloader/downloader.go
- ethdb/database.go
- node/node.go
- rlp/safe.go
- tests/fuzzers/bls12381/bls12381_fuzz.go
This is for the off-line block prune, in bsc storage, there's db wrapper of ancientDb(freezer) and kvDb(levelDB), the space was mainly occupied by ancientDb, the purpose of this is to prune and remain the specific number of old blocks in ancientDb by specifying the amount of blocks you'd like to remain after pruning in the CLI flag. Then the pruner will prune and only remain this specified amount backward, this first block is not necessarily the genesis block because we may prune many rounds. Actually we can prune and remain any amount of blocks as long as the amount specified did exceed the number of blocks inside ancientDb
###Example:
Assume all blocks in ancientDb are [0,1,... 1000], if pruning amount of 500 blocks, then [0,...499] will be pruned, the data in ancientDb will be [500, …
> [R4R]offline block prune

- .github/release.env
- CHANGELOG.md
- PULL_REQUEST_TEMPLATE
- params/version.go
Prepare for the release v1.1.8
FEATURES
* [\#668](https://github.com/binance-chain/bsc/pull/668) implement State Verification && Snapshot Commit pipeline
* [\#581](https://github.com/binance-chain/bsc/pull/581) implement geth native trace 
* [\#543](https://github.com/binance-chain/bsc/pull/543) implement offline block prune tools
IMPROVEMENT
* [\#704](https://github.com/binance-chain/bsc/pull/704) prefetch state by applying the transactions within one block 
* [\#713](https://github.com/binance-chain/bsc/pull/713) add ARM binaries for release pipeline
BUGFIX
* [\#667](https://github.com/binance-chain/bsc/pull/667) trie: reject deletions when verifying range proofs #667
* [\#643](https://github.com/binance-chain/bsc/pull/643) add timeout for stopping p2p server to fix can not gracefully …
> [R4R]prepare for relase v1.1.8

- eth/protocols/trust/handler_test.go
- eth/protocols/trust/peer_test.go
The increasing adoption of BSC leads to a more active network. On the other hand, the node maintainer had a hard time keeping their node catching up with the chain. A new syncing protocol to lower the hardware requirement is an urgent need.
Currently a BSC node has two kinds of state world: MPT and snapshot. MPT(Merkle Patricia Tries) is a tree-structured state world. The key function of MPT is to generate the state root to ensure state consistency, while the query/commit on MPT is quite slow. Snapshot is a flattened key-value-based state world. Snapshot provides fast queries and commits. The storage size of the snapshot increases slowly even with a large transaction volume. Snapshot is usually used for block processing, while MPT is used for state verification.
In order to lower the …
> [R4R]Separate Processing and State Verification on BSC: add test cases for trust protocol

- core/gaspool.go
- core/state_prefetcher.go
- core/types.go
- core/types/transaction.go
- core/types/transaction_test.go
- miner/worker.go
When miner process mining work, there would be some hard disk access wich are quite time consuming processes.
- Add some prefetch routines to warm up touched data slots by apply transactions concurrently to the given individual state database copy.
Notable changes:
- Modify `Prefetch` inteface so that it would be compatible with mining `prefetcher`
- Add `PrefetchMining` method for state_prefetcher just like `Prefetch` but a mining version
> [R4R]Prefetch state data on mining process

- core/blockchain_diff_test.go
- core/state_processor.go
The developer proposes a fast node in these PR https://github.com/bnb-chain/bsc/pull/640.
And the fast node is adopted by many developers, there is some adaptive work to do to make fast node serve diffsync well.
A fast node is a node without  MPT(Merkle Patricia Tries, which means the account inside the generated difflayer will not have the correct `storageRoot`. 
Currently, diffsync will check the calculated `storageRoot` of each account against the `storageRoot` within the untrusted difflaayer.  While this is not necessary to guarantee the correctness of each account, since diffsync will verify the state root of the biggest account MPT, which already guarantees the data consistency. We will remove the redundant check in this PR to be compatible with fast node.
No API changes.
No
> [R4R] skip verification on account storage root to tolerate with fastnode when doing diffsync

- core/state/statedb.go
Bugfix for diff layer may have nil code even there is a new smart contract created in the block.
The bug is introduced in pipecommit PR. 
When doing `Commit` of `StateDB`,  the difflayer is returned while the `commmitTrie` routine may assign the code of difflayer in the future.
This bug will impact the diff sync: difflayer may not contains the all changed codes.
No
After this patch, the node can always get the same difflayers.
> [R4R]fix code of difflayer not assgin before return

- cmd/geth/snapshot.go
- core/headerchain.go
- core/rawdb/chain_iterator.go
- eth/state_accessor.go
- internal/ethapi/api.go
fix prune-block-tool bugs
fix bugs:
1. When the prune-block-tool  is executed, "Failed to decode block body" error may be reported due to txloopuplimit setting.
2. Added some verification logic, because some data related to the block may be deleted after the prune-block-tool is executed.
3. Force the input of ‘--datadir.ancient’ to be an absolute path. Many users always fail to execute because they are caught in the splicing of relative paths of ‘--datadir’ and ‘--datadir.ancient’
> [R4R]fix pruner block tool bug, add some check logic

- core/blockchain.go
- core/state/state_object.go
- core/state_prefetcher.go
- miner/worker.go
Since the miner has prefetched data , this PR make the miner main process and the prefetch process share a shared_pool with the stateDB.  By this way , the prefetch data that can be directly fished to the L1.5 layer and make miner prefetch faster
* ...
> add sharedStorage to the prefetcher of miner

- cmd/utils/flags.go
- eth/backend.go
This PR is going to disable diffsync when pipecommit is enabled.
After several rounds of performance improvement,  it turns out the `diffsync` performance is no better than a pipecommit enabled node. This PR is going to disable diffsync when pipecommit is enabled and leave the further enhancement to https://github.com/bnb-chain/bsc/issues/819
No
No
> [R4R]disable diffsync when pipecommit is enabled

- core/state_prefetcher.go
since the main thread has become faster after using sharedStorage , we need more prefetch thread num to make the prefetch is faster than main process.
After after adding some metric on prefetch therad ,   the metric shows that the prefetcher with two threads has 5-20% faster than main process while  prefetcher with three threads has become 20-40% faster than main process .
The yellow line is using 3 thread
The two test machine is on AWS , the two nodes has worked in fullsync mode and has caught up to the latest block
The cost of process a block show that the processing cost of main process with three prefetch threads  has become 3%-10% faster than two prefetch threads
Compare to the processing cost of main process prefetcher with 3 thread  and 4 thread ,  the cost of process a block is …
> change prefetch thread num

- core/state/statedb.go
Fix a node stuck issue when pipecommit is enabled.
The node is just stuck and does not import blocks anymore.
The routine profile is: [deadlock_routines.log](https://github.com/bnb-chain/bsc/files/8401688/deadlock_routines.log)
```
goroutine 56646460 [chan receive, 1207 minutes]:
github.com/ethereum/go-ethereum/core/state/snapshot.(*diffLayer).WaitAndGetVerifyRes(0xc04f35afd0)
github.com/ethereum/go-ethereum/core/state/snapshot/difflayer.go:271 +0x34
github.com/ethereum/go-ethereum/core/state.(*StateDB).WaitPipeVerification(0x12d773a474e4ba1)
github.com/ethereum/go-ethereum/core/state/statedb.go:907 +0x2d
github.com/ethereum/go-ethereum/core.(*BlockValidator).ValidateState.func3()
github.com/ethereum/go-ethereum/core/block_validator.go:140 +0x38 …
```
> [R4R]fix deadlock when failed to verify state root

- core/state/statedb.go
A possible deadlock when commit trie failed
A node stuck and failed to import any blocks, the go routine profile is:  [routine.txt](https://github.com/bnb-chain/bsc/files/8401973/routine.txt)
```
github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit.func1.1(0x40eefc8fc0, 0x0, 0x420496c2f8, 0x1, 0x1, 0x572e056600a67eff, 0x99b123d0825edb78)
/ext-go/1/src/github.com/ethereum/go-ethereum/core/state/statedb.go:1367 +0x2d4
github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit.func1(0x0, 0x0)
/ext-go/1/src/github.com/ethereum/go-ethereum/core/state/statedb.go:1413 +0x5c
github.com/ethereum/go-ethereum/core/state.(*StateDB).Commit.func4(0x429104c180, 0x4316b0ec80)
/ext-go/1/src/github.com/ethereum/go-ethereum/core/state/statedb.go:1502 +0x28
created by …
```
> [R4R]fix deadlock on miner module when failed to commit trie

- miner/worker.go
panic with nil pointer of `Transaction.inner`
If `PrefetchMining` run fast enough that sub-prefetcher-routines checked `txCurr` before transaction had been peeked from `TransactionByPriceAndNonce` at the main worker routine, it would get an empty `Transaction` struct with nil `inner` filed which would cause panic in `func (s EIP155Signer) Sender(tx *Transaction) (common.Address, error)`
N/A
* Instead of using empty `Transaction` for tx initialization, `Peek` the first `transaction` from `TransactionByPriceAndNonce` for current transaction `txCurr` at `miner/worker.go:line787` which would be accessed in mining-prefetcher-routine
> [R4R]Fix miningprefetcher

- core/state_processor.go
There is a bug in diffsync - the error check of the creation of new statedb is too late, which could lead to panic. This pr tries to fix this bug.
Error check should be done right after the creation of statedb.
NA
* check the `err` in the correct location
> [R4R] Fix nil statedb in diffsync

- .github/release.env
- CHANGELOG.md
- params/version.go
Prepare for the release v1.1.9.
IMPROVEMENT
* [\#792](https://github.com/binance-chain/bsc/pull/792) add shared storage for prefetching state data
* [\#795](https://github.com/binance-chain/bsc/pull/795) implement state verification pipeline in pipecommit
* [\#803](https://github.com/binance-chain/bsc/pull/803) prefetch state data during the mining process
* [\#812](https://github.com/bnb-chain/bsc/pull/818) skip verification on account storage root to tolerate with fastnode when doing diffsync
* [\#818](https://github.com/bnb-chain/bsc/pull/818) add shared storage to the prefetcher of miner
* [\#820](https://github.com/bnb-chain/bsc/pull/820) disable diffsync when pipecommit is enabled
* [\#830](https://github.com/bnb-chain/bsc/pull/830) change the number of prefetch threads
BUGFIX
* …
> [R4R] prepare for release of v1.1.9

- .github/release.env
- CHANGELOG.md
- PULL_REQUEST_TEMPLATE
- cmd/geth/snapshot.go
- cmd/utils/flags.go
- core/block_validator.go
- core/blockchain.go
- core/blockchain_test.go
- core/headerchain.go
- core/rawdb/chain_iterator.go
- core/state/shared_pool.go
- core/state/snapshot/difflayer.go
- core/state/snapshot/disklayer.go
- core/state/snapshot/journal.go
- core/state/snapshot/snapshot.go
- core/state/state_object.go
- core/state/statedb.go
- core/state_prefetcher.go
- core/state_processor.go
- core/types.go
- core/types/transaction.go
- core/types/transaction_test.go
- eth/backend.go
- eth/state_accessor.go
- internal/ethapi/api.go
- miner/worker.go
- params/version.go
- trie/database.go
Release v1.1.9 a performance improvement release.
IMPROVEMENT
* [\#792](https://github.com/binance-chain/bsc/pull/792) add shared storage for prefetching state data
* [\#795](https://github.com/binance-chain/bsc/pull/795) implement state verification pipeline in pipecommit
* [\#803](https://github.com/binance-chain/bsc/pull/803) prefetch state data during the mining process
* [\#812](https://github.com/bnb-chain/bsc/pull/812) skip verification on account storage root to tolerate with fastnode when doing diffsync
* [\#818](https://github.com/bnb-chain/bsc/pull/818) add shared storage to the prefetcher of miner
* [\#820](https://github.com/bnb-chain/bsc/pull/820) disable diffsync when pipecommit is enabled
* [\#830](https://github.com/bnb-chain/bsc/pull/830) change the number of prefetch …
> [R4R] Release v1.1.9

- core/state_prefetcher.go
- core/types/transaction.go
- core/types/transaction_test.go
panic when length of heads equal to zero when `shift`
- `TransactionsByPriceAndNonce.Shift` should only be called after `TransactionsByPriceAndNonce.Peek` directly and void invoke on `TransactionsByPriceAndNonce.Shift` when `Peek` show a nil result, otherwise might cause a panic for zero length `TransactionsByPriceAndNonce.heads` when doing `Shift`
- `func (p *statePrefetcher) PrefetchMining(...)` invoked `TransactionsByPriceAndNonce.Forward` before `TransactionsByPriceAndNonce.Shift` with no `TransactionsByPriceAndNoncePeek` check while `TransactionsByPriceAndNonce.Forward` might change `TransactionsByPriceAndNonce.heads` to zero length.
N/A
* rearrange calling sequence in the dispatcher of `prefechmining`, make sure `Peek` be checked before `Shift`
* `func (p …
> [R4R]fix:Shift panic for zero length of heads

- core/receipt_processor.go
- core/state_processor.go
There's risk of memory leak for channel in `bloomProcessors` in `Process` when an early return happen.
We need to ensure closing channel (`bloomProcessors.Close()`) before return
N/A
* user defer to make sure `bloomProcessors.Close()` be executed before `Process` return
* keep current `bloomProcessors.Close()` for efficiency.
> [R4R] fix:defer bloomprocessor close

- core/block_validator.go
- core/state/statedb.go
- miner/worker.go
If a validator runs 1.1.9 with `pipecommit` enabled, sometimes it will fail to write block due to incorrect account roots, like this:
```
t=2022-04-25T05:11:48+0000 lvl=info msg=“Sealing block with”                    number=17,244,681 delay=2.740279174s  headerDifficulty=2 val=0x70F657164e5b75689b64B7fd1fA275F334f28e18
t=2022-04-25T05:11:51+0000 lvl=eror msg=“Failed writing block to chain”         err=“can’t create storage trie: missing trie node 542e5fc2709de84248e9bce43a9c0c8943a608029001360f8ab55bf113b23d28 (path )”
```
This pr fix this issue by calling `CorrectAccountsRoot` before commit the block in mining.
In `pipecommit`, the account roots are populated with dummy data, in the importing process the account roots are corrected, however, they are not corrected in the mining process. …
> [R4R] fix validator pipecommit issue

- CHANGELOG.md
- README.md
- params/config.go
- params/version.go
It is a maintenance release.
FEATURE
* [\#885](https://github.com/binance-chain/bsc/pull/885) add Euler Hardfork, including BEP-127 and BEP-131
BUGFIX
* [\#856](https://github.com/binance-chain/bsc/pull/856) fix logic issue: handlers.removePeer() is called twice
* [\#860](https://github.com/binance-chain/bsc/pull/860) fix:defer bloomprocessor close
* [\#877](https://github.com/binance-chain/bsc/pull/877) fix validator pipecommit issue
* [\#870](https://github.com/binance-chain/bsc/pull/870) fix:Shift panic for zero length of heads
The Euler upgrade height for testnet is 19203503.
> [R4R] prepare for release v1.1.10

- core/state/state_object.go
- core/state/statedb.go
This pr tries to improve block importing by splitting mutex for snap account and storage.
The access to snap accounts and snap storage could use different locks to avoid unnecessary race.
* Before
```
Dropped 546 nodes (cum <= 0.02mins)
Showing top 40 nodes out of 106
flat  flat%   sum%        cum   cum%
3.59mins 90.44% 90.44%   3.59mins 90.44%  sync.(*Mutex).Unlock (partial-inline)
0.37mins  9.26% 99.71%   2.17mins 54.68%  sync.(*RWMutex).Unlock
0     0% 99.71%   0.03mins  0.74%  github.com/VictoriaMetrics/fastcache.(*Cache).Set
0     0% 99.71%   0.03mins  0.74%  github.com/VictoriaMetrics/fastcache.(*bucket).Set
0     0% 99.71%   0.51mins 12.93%  github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain
0     0% 99.71%   0.02mins  0.58% …
```
> [R4R] improve snap mutex

- core/state/state_object.go
the updateTrie function need to update trie node and  snap in a for loop,  since the snap updating need wait lock , it may make update trie slower , this PR use a groutine to update snap to make update trie more efficient
When chasing blocks in batches, the time overhead of volidation is reduced by 10%, 
The overall efficiency of batch sync blocks has been improved， the follow lines represents the delay of volidation with pipeline commit
When executing the latest block, the latency of updateTrie is reduced by 30%-40%,  the follow lines represents the delay of an updateTrie function call.
* ...
> asynchronous  update snap in  updatetrie

- CHANGELOG.md
- README.md
- params/config.go
- params/version.go
V1.1.11 is a is a hard fork release that contains the update about the block number of `Euler Fork` upgrade. 
The upgrade will start at block number `18907621`,  approximately at 2022-06-22 08:00:00 UTC.
UPGRADE
* [\#927](https://github.com/bnb-chain/bsc/pull/927) add readme for validators about how to enter/exit maintenance
* [\#942](https://github.com/bnb-chain/bsc/pull/942) update the blockNumber of Euler Fork upgrade on BSC Mainnet
No
* Update the blockNumber of `Euler Fork` upgrade to `18907621` on mainnet
* More details about `Euler Fork`, please refer to https://github.com/bnb-chain/bsc/pull/885
> [R4R] Release For BSC v1.1.11

- README.md
Correct stale doc links
As the docs.binance.org migrate to docs.bnbchain.org, the structure of new docs site also changed, we should replace stale doc link with new one.
No
> [R4R]Updated Links to docs.bnbchain.org

- core/state/statedb.go
This pr will fix an issue, i.e., some account root is not correctly set when committing mpt ,during pipecommit.
During pipecommit, the account root is populated as `dummyRoot` and will be corrected at several places. However, the previous code will skip some accounts during correction stage.  This will lead to commit error when committing mpt.
This fix will correct the root for `stateOjbect`, which's account root length is zero.
NA
* change CorrectAccountRoots function
> [R4R] fix pipecommit issue

- CHANGELOG.md
- README.md
- docs/parlia/README-BEP-127.md
- params/config.go
- params/version.go
V1.1.11 is a is a hard fork release that contains the update about the block number of `Euler Fork` upgrade. 
The upgrade will start at block number `18907621`,  approximately at 2022-06-22 08:00:00 UTC.
UPGRADE
* [\#927](https://github.com/bnb-chain/bsc/pull/927) add readme for validators about how to enter/exit maintenance
* [\#942](https://github.com/bnb-chain/bsc/pull/942) update the blockNumber of Euler Fork upgrade on BSC Mainnet
No
* Update the blockNumber of `Euler Fork` upgrade to `18907621` on mainnet
* More details about `Euler Fork`, please refer to https://github.com/bnb-chain/bsc/pull/885
> Merge fast node branch with latest release

- core/vm/interpreter.go
current code logic of for...range...check to delete elements in slice is not correct, would skip checking the element next to the element be deleted of which error was detected.
```
for i, v := range slice{
// check slice[i]
slice = append(slice[:i], slice[i+1:]...)
}
```
declare a new slice for left eipIDs
core/vm/interpreter.go : NewEVMInterpreter(...)
> [R4R] correct logic for eip check of NewEVMInterpreter

- core/blockchain.go
- core/state_prefetcher.go
- core/types.go
State Prefetch was first implemented in v1.1.8, see [PR 704](https://github.com/bnb-chain/bsc/pull/704). It improved the performance of block process a lot by improving the snapshot cache hit rate.
This PR did not change its logic, but did some improvements.
1.Use `AsMessageNoNonceCheck` to skip nonce check for prefetch transactions.
For state prefetch, no need to check transaction's nonce, since the transaction's result will be discarded anyway.
2.Improve the transaction dispatch policy
** Replace atomic read by channel close to interrupt state prefetch
** Try to do state prefetch when the prefetch thread is idle, no need to divide into 3 sub-arrays
I add some tracing logs to show the workflow of state prefetch.
As the bellow tracing show, we have 3 prefetch thread. Before the PR, their …
> [R4R]: Improve state prefetch

- cmd/geth/main.go
- cmd/geth/pruneblock_test.go
- cmd/utils/flags.go
- core/blockchain.go
- core/blockchain_repair_test.go
- core/blockchain_sethead_test.go
- core/blockchain_snapshot_test.go
- core/blockchain_test.go
- core/headerchain.go
- core/rawdb/accessors_chain_test.go
- core/rawdb/accessors_metadata.go
- core/rawdb/chain_iterator.go
- core/rawdb/database.go
- core/rawdb/freezer.go
- core/rawdb/prunedfreezer.go
- core/rawdb/schema.go
- core/state/pruner/pruner.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
- eth/handler.go
- eth/sync.go
- node/node.go
- params/network_params.go
Block Data no longer transfer to AncientDB when delete from KVStore.
Save more os resources, disk space, disk bandwidth, cpu.
Release more disk space, disk bandwidth resources.
"./geth" start command add "--puneancient" parameter
* add punedfreezer struct inherit AncientStore interface, implement not save to AncientDB when delete from KVStore
* add 'PruneAncientFlag'(record abcinet type) and 'StableStateBlockNumber'(record lastest rootHash savetodisk)
* add check logic for block data is nil, because maybe delete when transfer to AncientDB
> add prune ancient feature

- core/state/trie_prefetcher.go
- core/state/trie_prefetcher_test.go
There are 2 types of triePrefetcher instances.
1.New created `triePrefetcher`: it is the one to do trie prefetch to speed up validation phase.
2.Copied `triePrefetcher`: it just do a copy of the prefetched trie,  it won't do prefetch at all. The copied tries are all kept in p.fetches.
In thie PR, we try to improve the new created one, to make it concurrent safe, while the copied one's behavior stay unchanged(its logic is very simple).
As commented in `triePrefetcher` struct, its APIs are not thread safe. So callers should make sure the created triePrefetcher should be used within a single routine. As we are trying to improve triePrefetcher, we would use it concurrently, so it is necessary to redesign it for concurrent access.
The redesigned workflow:
1.start a mainLoop to do the real trie …
> [R4R]: Redesign triePrefetcher to make it thread safe

- miner/worker.go
```
t=2022-07-07T12:38:34+0000 lvl=info msg="Mining aborted due to sync"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xff0ffd]
goroutine 110 [running]:
github.com/ethereum/go-ethereum/miner.(*worker).commitTransactions(0xc000269b80, 0xc01db799a0, 0xc076245840, 0xc01cdc87e0, 0xc076245800)
github.com/ethereum/go-ethereum@/miner/worker.go:922 +0xc2d
github.com/ethereum/go-ethereum/miner.(*worker).fillTransactions(0xc000269b80, 0xc01cdc87e0, 0xc01db799a0)
github.com/ethereum/go-ethereum@/miner/worker.go:1121 +0x219
github.com/ethereum/go-ethereum/miner.(*worker).commitWork(0xc000269b80, 0xc01cdc87e0, 0x1, 0x62c6d3ca)
github.com/ethereum/go-ethereum@/miner/worker.go:1168 +0x150 …
```
> [R4R] fix nil pointer issue when stopping mining new block

- core/blockchain.go
- core/state/statedb.go
- core/state/trie_prefetcher.go
- core/state_processor.go
We found that the current trie prefetch could be not fast enough, especially trie prefetch of the outer big state trie tree. When processing a big block, thousands of accounts's root hash could be changed. In this PR, we try to optimize it in 2 approaches.
Instead of do trie prefetch until a transaction is finalized, we could do trie prefetch in advance. Try to prefetch the trie node of the From/To accounts, since their root hash are most likely to be changed.
The bellow tracing image shows, the trieprefetch has several idle state.
After trie prefetch From/To in advance, it will be busy.
Currently, we create a subfetcher for each account address to do trie prefetch. But if the number of changed account or updated KV is too large, the subfetcher would not be able to fetch all the trie node …
> [R4R][Feature]: Improve trie prefetch

- miner/worker.go
1. The code for the mining block upgrade system contract is missing. https://github.com/bnb-chain/bsc/blob/de4abf9d09afac7ad54d3268647d1c8f5aa61e95/miner/worker.go#L966
2. Incorrect update of `stateb` when miner enables `pipecommit`.
1. Missed when merging ethereum versions.
2. When a miner does a `commit`, a new `*environment` is copied to work, but when `pipecommit` is enabled, `CorrectAccountsRoot` should be called to correct the root hash of the accounts in the snapshot, which results in only the copied ones be updated, and the continuously running `statedb` is not properly updated.
N/A
* miner/worker.go
> [R4R] fix: missing contract upgrades and incorrect behavior when miners enable pipecommit

- core/remote_state_verifier.go
- core/tx_pool.go
Signed-off-by: cryyl <yl.on.the.way@gmail.com>
When fast node insert a block, it will judge whether the 11 ahead of current block has been verified. While, if a block is an empty block, it must be verified. So if the 11 ahead block is an empty block, the AncestorVerified function will return true.
* In the AncestorVerified function, if the 11 ahead of current block is an empty block, return true.
> [R4R]fix: resolve the concurrent cache read and write issue for fast node

- cmd/geth/snapshot.go
- cmd/utils/flags.go
- core/rawdb/database.go
- core/rawdb/freezer.go
- core/rawdb/freezer_batch.go
- core/rawdb/freezer_table_test.go
- core/rawdb/freezer_test.go
- core/rawdb/prunedfreezer.go
- core/state/pruner/pruner.go
* Freezer batch compatible offline prune tool.
* Normalized the prune-block command parameters to avoid the first execution failure for new users due to parameter problems.
Usage
* geth snapshot prune-block --datadir $datadir_var --datadir.ancient $ancientdir_var
| --datadir and --datadir.ancient parameters are required options and uses absolute path
Code changes: 
* add offset(after offline prune tool running, offset stands the start block number in ancient) to freezer batch.
* batch reset and commit will consider offset.
> [R4R]db: freezer batch compatible offline prunblock command

- core/blockchain_reader.go
This PR tries to fix the issue that the fast node can not been recovered after being force kill.
The logic of `HasBlockAndState` on develop branch is different from the [fastnode](https://github.com/bnb-chain/bsc/tree/fastnode) branch, which cause the problem.
We tried to force kill a fast node, and bring it back again, we will get the following logs to ensure the patch works:
```
=2022-07-25T12:30:30+0000 lvl=info msg="Importing sidechain segment"            start=915,482 end=916,833
t=2022-07-25T12:30:30+0000 lvl=eror msg="Expired request does not exist"         peer=c10f40b516f6b4deb81c0a03e9f35fbe77a5e782c283946653f54832540e22ff
t=2022-07-25T12:30:30+0000 lvl=eror msg="Expired request does not exist"         peer=6ce892615c659728db873e6367d026272816a6b5136a40fcefd9ab3343fdb92f …
```
> [R4R]fix: fast node can not recover from force kill or panic

- internal/ethapi/transaction_args.go
Just remove noisy warning logs which are expected.
BSC get system transaction whose gas limit is 9,223,372,036,854,775,807, which will always exceed the default 50,000,000 cap, so there is no need to warn.
Dismiss the following logs:
```
t=2022-07-25T12:35:50+0000 lvl=warn msg="Caller gas above allowance, capping"   requested=9,223,372,036,854,775,807 cap=50,000,000
```
No
> [R4R]log: disable noisy logs since system transaction will cause gas capping

- eth/handler.go
- eth/handler_diff.go
`broadcastDiffLayers` is not properly closed, the memory accumulates too many resources and causes OOM.
```
goroutine 8845520 [select, 3426 minutes]:
github.com/ethereum/go-ethereum/eth/protocols/diff.(*Peer).broadcastDiffLayers(0xc081628d20)
github.com/ethereum/go-ethereum/eth/protocols/diff/peer.go:47 +0xab
created by github.com/ethereum/go-ethereum/eth/protocols/diff.NewPeer
github.com/ethereum/go-ethereum/eth/protocols/diff/peer.go:41 +0x2f0
goroutine 7119763 [select, 3531 minutes]:
github.com/ethereum/go-ethereum/eth/protocols/diff.(*Peer).broadcastDiffLayers(0xc10bcd4e40)
github.com/ethereum/go-ethereum/eth/protocols/diff/peer.go:47 +0xab
created by github.com/ethereum/go-ethereum/eth/protocols/diff.NewPeer
github.com/ethereum/go-ethereum/eth/protocols/diff/peer.go:41 +0x2f0 …
```
> [R4R] fix: memory leak issue with diff protocol

- core/blockchain.go
- core/state/statedb.go
- core/state/trie_prefetcher.go
- core/state_prefetcher.go
- miner/worker.go
This is another PR to enhance the trie prefetch, try to reuse the execution results of state prefetch.
Currently, state prefetch just pre-execute the transactions and discard the results. It is helpful to increase the snapshot cache hit rate. It would be more helpful, if it can do trie prefetch at the same time, since the it will preload the trie node and build the trie tree in advance.
This PR is to implement it, by reusing the main trie prefetch and doing finalize after transaction is executed.
With this PR, the peek validation of the BSC 2022.04.18 burst traffic reduced by ~39% even based on the previous trie prefetch optimizations.
No impact to user.
> [R4R]: Trie prefetch on state pretch

- core/state/state_object.go
`trie.update`/`trie.delete` had been done twice which is redundant
`Lock` could just be used to protect concurrent access on `statedb.snapStorage`, not the `storage` itself.
N/A
N/A
*  remove redundant code.
* `Unlock` earlier.
> [R4R] rm duplicate update/delete on tire

- core/state/state_object.go
- core/state/statedb.go
`prefetcher` be accessed after non-nil condition as a field of `statedb` is not safe.
eg: as in `pipecommit` mode, `statedb` might be used as `activestatedb` to `StopPrefetcher`, which would `panic` during:
```
if prefetcher != nil {
prefetcher.used(s.data.Root, usedStorage)
}
```
get `prefetcher` from `statedb` before check nil condition
N/A
-
> [R4R] Fix pipecommit active statedb

- core/state/state_object.go
- core/state/statedb.go
BSC has merged https://github.com/ethereum/go-ethereum/pull/23628 to avoid hitting outdated snapshots, so we can remove #926 code that was introduced at the time to fix diffHash mismatch. 
In previous versions, the snapshot tree executed `parent.flatten()` without first locking the current difflayer when `cap`, but first executed the `parent.flatten()` to change it to be `stale` state and relinks the current `difflayer.parent` (removes the stale's difflayer from the recursive structure).
And this has caused a problem. There is a small chance that the stale difflayer will be obtained first when the difflayer is accessed externally, and then the difflayer.parent will be locked and re-linked, resulting in the snapshot being judged when acquiring the Account or Storage data. Returns null for …
> [R4R] fix: remove diffhash patch introduced from separate node

- p2p/server.go
For the fast node, verify node is a special setting that can do remove state root verification.
The development branch does have bugs in mark verify nodes. This PR aims to fix the bug.
Both `dialDest` and `n` here is pointers, we shall just compare whether the ID equals.
After the patch, fast node can work smoothly in `full` and `insecure` mode.
No
> [R4R]fix: verify node is not treated as verify node

- .github/release.env
- CHANGELOG.md
- params/version.go
Release v1.1.12 is a performance release. the following two features are introduced in this release.
1. `Separate Processing and State Verification.`
2. `Pruning AncientDB inline at runtime.` 
Separate Processing and State Verification is introduced in https://github.com/bnb-chain/bsc/pull/926. it introduces two type nodes to make full use of different storage, one is named fast node, and the other is named verify node. The fast node will do block processing with snapshot, it will do all verification against blocks except state root. The verify node receives diffhash from the fast node and then responds MPT root to the fast node.
If you want to use this feature, See more details [here](https://docs.bnbchain.org/docs/BSC-separate-node)
A new flag is introduced to prune ancient undesired …
> [R4R] Prepare for v1.1.12

- core/state/snapshot/difflayer.go
- core/state/snapshot/disklayer.go
- core/state/snapshot/snapshot.go
- core/state/state_object.go
- core/state/statedb.go
- core/state/trie_prefetcher.go
- core/state/trie_prefetcher_test.go
current `pipecommit` mode would use dummyRoot as account storageRoot before previous block had done commit. This would lead `trirePrefetcher` not able to work.
Remove dummyRoot to keep previous storage root while doing triePrefetch and recover stateRoot to enable effective triePrefetch in `pipecommit` mode
It's fine to do `triePrefetch` on previous `stateRoot/storageRoot` and would do a lot help for all the `accounts/storages` which are not modified during previous block.
And this would cause no harm since we use the corrected root when we do updateTrie and commit, which would ignore the stale node prefetched and the path node in cache would still help even though they were prefetched from a stale root.
green-line: before<br/> 
yellow-line: after
- on …
> [R4R] Pipecommit enable trie prefetcher

- core/blockchain.go
- core/state/snapshot/difflayer.go
- core/state/snapshot/disklayer.go
- core/state/snapshot/snapshot.go
- core/state/state_object.go
- core/state/statedb.go
- core/state/trie_prefetcher.go
- core/state/trie_prefetcher_test.go
- core/state_prefetcher.go
- core/state_processor.go
- miner/worker.go
This is a combined PR of these 4 PRs:
https://github.com/bnb-chain/bsc/pull/975: broadcast block before commit block and add metrics 
https://github.com/bnb-chain/bsc/pull/952: [Feature]: Improve trie prefetch 
https://github.com/bnb-chain/bsc/pull/996: Trie prefetch on state prefetch
https://github.com/bnb-chain/bsc/pull/992: Pipecommit enable trie prefetcher 
These patch are for performance optimization, they were reviewed and merged into branch develp_July_200M first to wait the v1.1.12 release.
Since v1.1.12 is released now, we can merge them into the develop branch.
Optimizations include: mine phase, validation phase and pipecommit mode.
For detail, please refer the origin PR description.
Refer each PR.
No impact to user
> [R4R]feat: Merge holding performance PRs after v1.1.12 is released.

- .github/commitlint.config.js
- .github/workflows/commit-lint.yml
- docs/lint/commit.md
Added Commit Lint Checker, which will automatically check the commit message format when submitting PR.
Docs: https://github.com/j75689/bsc/blob/ci/commitlint/docs/lint/commit.md
1. https://commitlint.js.org/#/reference-configuration
2. https://github.com/wagoid/commitlint-github-action
Success: 
Fails:
N/A
> ci: add commit message lint

- cmd/geth/pruneblock_test.go
- cmd/utils/flags.go
- core/blockchain_repair_test.go
- core/blockchain_sethead_test.go
- core/blockchain_snapshot_test.go
- core/blockchain_test.go
- core/rawdb/accessors_chain_test.go
- core/rawdb/database.go
- core/state/pruner/pruner.go
- eth/downloader/downloader_test.go
- node/node.go
Fixed the bug #1034 that 'prune-state/insecure-prune-all ...'  and some other offline commands will fail after using '--pruneancient' to start geth. 
* Add ‘skipCheckFreezerType’ parameter to 'NewDatabaseWithFreezer' function.
* When offline commands open database with 'MakeChainDatabase', will set skipCheckFreezerType true, skip freezer type checking. Make sure the command is executed correctly.
* When starting geth, use 'OpenAndMergeDatabase' to open the database, will set skipCheckFreezerType false, force freezer type checking to prevent freezer from being mixed with prunefreezer.
> state: fix offline tool start failed when start with pruneancient

- .github/commitlint.config.js
The commitlint will check scope's case by default, only lower-case is allowed, e.g. the following commit message will fail:
"BEP100:  implement xxx"
Just remove this check.
None
None
No impact to users
> ci: no type-case check for scope.

- .github/commitlint.config.js
merge commit format should be allowed, such as:
None
None
None.
> ci: allow merge pull request

- build/ci.go
- cmd/geth/pruneblock_test.go
1. fix TestOfflineBlockPrune
2. trigger unit case for testing cmd in ci
1. This test case is broken after merging go-ethereum
https://github.com/bnb-chain/bsc/issues/1046
`make test`
N/A
> test: fix TestOfflineBlockPrune

- consensus/misc/eip1559_test.go
- consensus/parlia/parlia.go
- core/block_validator_test.go
- params/protocol_params.go
`GasLimitBoundDivisor` should be 256 in BSC, was changed to `1024` in the merged ethereum version, fixed back here
1. change `GasLimitBoundDivisor` to 256
2. Ignore some test cases for eip-1559, bsc doesn't enable it
1. Start a private network (2 v1.1.11 miners, 1  miner of this version), and continuously initiate transfer transactions, which does not affect block generation
N/A
> consensus: fix the GasLimitBoundDivisor

- .github/commitlint.config.js
Fix the pattern of commit lint
changed parser pattern from `/^(.*): .*/` to `/^(.*):.*/`, allow the message formats like `(scope):(subject)`.
N/A
* .github/commitlint.config.js
> ci: fix the pattern of commit lint

- core/tx_pool.go
issue: https://github.com/ethereum/go-ethereum/issues/23690
force calls Reheap periodically on the txpool to evict old transactions from the priced list when London fork is not enabled. Otherwise, it calls setBaseFee that internally calls Reheap.
The patch refer to https://github.com/maticnetwork/bor/pull/201/files 
pending...
N/A
> txpool: reheap the priced list if london fork not enabled

- core/state_prefetcher.go
There might be no receiver for txCh when interruptCh is closed and goroutine will be blocked here forever
* ...
> fix:fix potential goroutine leak

- core/blockchain.go
- core/state/statedb.go
- Since `statedb` would be accessed concurrently in different routine, it's not proper to use defer with `activeState` in the `insertchain`
- `triePrefetcher` is safe to be accessed like `trie` to get cached node when stopped, and since `triePrefetcher` had been redesigned to concurrency safe, there's no need to use `Lock`.
`StopPrefetcher` manually
N/A
* `StopPrefetcher` manually
*  Modify `StopPrefetcher` to keep stopped prefetcher in `statedb`
> statedb: get rid of activestate, stopPrefetcher manually

- CHANGELOG.md
- params/version.go
update version to v1.1.13 and CHANGELOG.md
N/A
N/A
v1.1.13
FEATURE
* [\#1051](https://github.com/bnb-chain/bsc/pull/1051) Implement BEP153: Native Staking
* [\#1066](https://github.com/bnb-chain/bsc/pull/1066) Upgrade cross chain logic of native staking
IMPROVEMENT
* [\#952](https://github.com/bnb-chain/bsc/pull/952) Improve trie prefetch
* [\#975](https://github.com/bnb-chain/bsc/pull/975) broadcast block before commit block and add metrics
* [\#992](https://github.com/bnb-chain/bsc/pull/992) Pipecommit enable trie prefetcher
* [\#996](https://github.com/bnb-chain/bsc/pull/996) Trie prefetch on state pretch
BUGFIX
* [\#1053](https://github.com/bnb-chain/bsc/pull/1053) state: fix offline tool start failed when start with pruneancient
* [\#1060](https://github.com/bnb-chain/bsc/pull/1060) …
> upgrade: update version and CHANGELOG.md

- cmd/utils/flags.go
Overwrites `HTTPHost` in config.toml via cli flag when starting a node.
```
./geth --config ./config.toml --datadir ./node  --cache 8000 --http --http.addr 0.0.0.0 
```
When starting a node with flag `http` and `http.addr`, the config `HTTPHost` will be overwrite by the flag `http.addr`.
It's reasonable to overwrite the config in config.toml via cli flag.
Start a node with command:
```
./geth --config ./config.toml --datadir ./node  --cache 8000 --http --http.addr 0.0.0.0 
```
This pr will allow overwriting `HTTPHost` in config.toml via cli flag.
> config: overwrite HTTPHost in config.toml via cli flag

- Dockerfile
- core/state_transition.go
- core/tx_pool.go
- core/types/blacklist.go
- core/vm/contracts.go
- core/vm/contracts_lightclient.go
- core/vm/evm.go
- params/config.go
This PR introduce an emergency nano hard fork, all clients must upgrade to this version.
The cross-chain bridge-related precompile contracts have been exploited, this PR aims to suspend the precompile contract and block the hacker's account.
Account `"0x489A8756C18C0b8B24EC2a2b9FF3D4d447F79BEc", "0xFd6042Df3D74ce9959922FeC559d7995F3933c55"` are blocked.
It is an emergency hardfork, all client must upgrade to this release.
> nanofork: add black list account

- CHANGELOG.md
- params/version.go
This PR introduce an emergency nano hard fork, all clients must upgrade to this version.
The cross-chain bridge-related precompile contracts have been exploited, this release aims to suspend the precompile contract and block the hacker's account.
* [\#1109](https://github.com/bnb-chain/bsc/pull/1109) nanofork: block exploitation accounts and suspend cross chain bridge related precompile contracts
Account `"0x489A8756C18C0b8B24EC2a2b9FF3D4d447F79BEc", "0xFd6042Df3D74ce9959922FeC559d7995F3933c55"` are blocked.
It is an emergency hardfork, all client must upgrade to this release.
> release: prepare for release v1.1.15

- accounts/abi/bind/backends/simulated.go
- accounts/url_test.go
- cmd/ethkey/message.go
- cmd/ethkey/utils.go
- common/format.go
- core/blockchain.go
- core/types/block.go
- core/types/transaction.go
- core/vm/analysis.go
- eth/filters/filter.go
- eth/filters/filter_system_test.go
- internal/ethapi/backend.go
- p2p/discover/v4_udp_test.go
- signer/core/signed_data.go
- trie/committer.go
- trie/database.go
Sync with `go-ethereum 1.10.19`:
mainly including some bug fixes, and together with some separate `prs`: https://github.com/bnb-chain/bsc/pull/1139, https://github.com/bnb-chain/bsc/pull/1140, https://github.com/bnb-chain/bsc/pull/1141.
N/A
N/A
N/A
> all: sync with upstream

- p2p/discover/lookup.go
- p2p/discover/v4_udp.go
- p2p/discover/v5_udp.go
- p2p/discover/v5wire/encoding.go
- p2p/dnsdisc/client.go
- p2p/enr/entries.go
- p2p/peer.go
- p2p/peer_error.go
- p2p/simulations/http.go
Sync with `go-ethereum`:
> from Go 1.13 on errors.Is is preferred for comparing errors.
N/A
N/A
N/A
> p2p: use errors.Is for error comparison

- consensus/parlia/parlia.go
- miner/worker.go
Inside parlia snapshot, BEP-131 validator set is updated at `number%s.config.Epoch == uint64(len(snap.Validators)/2)`.
Simplify it is `blockNumber%200 = 10`
`parlia.SignRecently()` is the first function be called when `miner.worker` getting NewChainHead signal, which controls the starting of the packing tasks.
```go
case head := <-w.chainHeadCh:
if !w.isRunning() {
continue
}
clearPending(head.Block.NumberU64())
timestamp = time.Now().Unix()
if p, ok := w.engine.(*parlia.Parlia); ok {
signedRecent, err := p.SignRecently(w.chain, head.Block.Header())
if err != nil {
log.Info("Not allowed to propose block", "err", err)
continue
}
if signedRecent {
log.Info("Signed recently, must wait")
continue
}
}
commit(true, commitInterruptNewHead)
```
But there is bug inside the `parlia.SignRecently()` …
> parlia urgent: BEP-131 bug. Cause new validators on blockNumber%Epoch = 11 are slashed often. 

- core/block_validator.go
There is duplicated validation check.
N/A
N/A
remove redundant `func`
> core:remove redundant func

- .github/workflows/unit-test.yml
Fixes the github action job name.
Currently shows as this:
* Only changes the github action job name.
> typo: .github fix job name

- Dockerfile
Specify bind-tools version
Have a fixed version to make it more safe to build image.
* fixed bind-tools version in Docker image to 9.16.33
> ci: specify bind-tools version

- CHANGELOG.md
- cmd/utils/flags.go
- params/version.go
Release v1.1.17 is a maintenance release, it includes several bug fixes.
IMPROVEMENT
* [\#1114](https://github.com/bnb-chain/bsc/pull/1114) typo: .github fix job name
* [\#1126](https://github.com/bnb-chain/bsc/pull/1126) ci: specify bind-tools version
* [\#1140](https://github.com/bnb-chain/bsc/pull/1140) p2p: upstream go-ethereum: use errors.Is for error comparison
* [\#1141](https://github.com/bnb-chain/bsc/pull/1141) all: prefer new(big.Int) over big.NewInt(0)
* [\#1159](https://github.com/bnb-chain/bsc/pull/1159) core: remove redundant func
BUGFIX
* [\#1138](https://github.com/bnb-chain/bsc/pull/1138) fix: upstream patches from go-ethereum 1.10.19
* [\#1139](https://github.com/bnb-chain/bsc/pull/1139) fix: upstream go-ethereum: fix duplicate fields names in the generted go struct
* …
> release: update version and changelogs

- miner/worker.go
`BSC` doesn't enable `tip` mechanism
NA
NA
NA
> miner: disable enforceTip when get txs from txpool

- miner/worker.go
- miner/worker_test.go
The code of work.go is critical for BSC block generation.
Try to do some code enhancement for it:
1.the resubmit intervalAdjust code was for PoW consensus, can be deleted.
2.change the work interrupt from atomic check to channel communication.
With PoW, there will be a periodic timer to check if it is the time to stop packing transaction and start calculating the desired hash value, since other miner could succeed in hash compute if it spends too much time packing transactions.
It will commit the current fruit to calculate root at a reasonable time.
And it will schedule a new work to get a big block if new transaction was received.
When there are too many transactions in the TxPool, the interval of the resubmit timer would be increased and vice versa.
But it is not needed with PoS …
> worker: some code enhancement on work.go

- miner/miner.go
- miner/worker.go
`pre-seal` empty block is for PoW to deliver an empty block ASAP to gain the block mine reward.
It is useless for PoS consensus and it does not work for BSC either.
Delete the code to make worker simpler.
NA
NA
NA
> worker: remove pre-seal empty block

- miner/worker.go
`fillTransactions` will call `commitTransactions` twice, if the delay timer is expired during the first call, it will make the delay timer never be triggered in the second commitTransactions call. Pseudo code:
x := time.NewTimer(time.Second)
<-x.C
fmt.Println("read delay 1")
<-x.C
fmt.Println("read delay 2")  // will never hit
NA
NA
NA
> worker: fix a bug of the delay timer.

- core/forkid/forkid.go
Refactor the code for better structure of efficiency.
- We don't need a `else` statement while the `if` statement has a `return`
- there's no need to use the internal variable `next`
NA
remove the useless code.
> core/forkid: refactor nextForkHash

- miner/worker.go
Add double sign check for safety.
The current 4 mining loops could have asynchronous risk of mining block with same height in rare case.
Keep recently mined blocks to avoid double sign for safety
NA
NA
> worker: add double sign check for safety.

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- Makefile
- cmd/geth/main.go
- cmd/utils/flags.go
- metrics/exp/exp.go
- metrics/label.go
- metrics/prometheus/collector.go
- metrics/prometheus/prometheus.go
- metrics/registry.go
1. metrics: add build info into metrics server
2. metrics: add label type in metrics package
3. ci: add git info to cross-compile
4. ci: fix build cmd of arm binary
implement a `Label` type in the metrics package, and set build-info into metrics server.
1. /debug/metrics
2. /debug/metrics/prometheus
* metrics package
> metrics: add build info into metrics server

- CHANGELOG.md
- params/version.go
v1.1.18 is a hard-fork release.  The mainnet is expected to have a scheduled hardfork upgrade named Gibbs at block height 23,846,001. The current block generation speed forecasts this to occur around 12th Dec. 2022 at 10:00 AM (UTC). The validators and full node operators on Mainnet should switch their software version to  [v1.1.18](https://github.com/bnb-chain/bsc/releases/tag/v1.1.18) by 12th Dec.
Besides, a critical issue has been patched in this release to fix theoretically non-maliciously, double-sign issue, all validators are encouraged to upgrade to the latest version as soon as possible.
IMPROVEMENT
* [\#1209](https://github.com/bnb-chain/bsc/pull/1209) metrics: add build info into metrics server
* [\#1204](https://github.com/bnb-chain/bsc/pull/1204) worker: NewTxsEvent and …
> release: prepare for v1.1.18 release.

- metrics/label.go
- metrics/prometheus/collector.go
1. the label in `prometheus` must match the regex [a-zA-Z_:][a-zA-Z0-9_:]*.
ex. api_http_requests_total{method="POST", handler="/messages"}
fix the printer in `metrics/prometheus`
* metrics/label
* metrics/prometheus
> metrics: fix the label format of prometheus server

- metrics/prometheus/collector.go
fix the incorrect format of prometheus label
1. https://github.com/bnb-chain/bsc/pull/1217
2. https://github.com/bnb-chain/bsc/pull/1222
N/A
N/A
BUGFIX
* [\#1217](https://github.com/bnb-chain/bsc/pull/1201) metrics: build-info causes prom error
* [\#1222](https://github.com/bnb-chain/bsc/pull/1185) fix the label format of prometheus server
> hotfix: fix the incorrect format of prometheus label

- eth/filters/filter.go
- eth/handler.go
- eth/protocols/snap/sync.go
- rpc/client.go
- rpc/client_test.go
- rpc/http.go
- trie/sync.go
Sync with go-ethereum 1.10.26, mainly include the some bugfixs and enhancement of snap sync 
1. The JSON-RPC client no longer hangs when invalid batch results are returned by the server
2. A corner-case issue in the filter system is resolved.
3. Various improvements to snap sync
None
1, fix datarace on CHT challenge reply/shutdown 
2, check children's existence concurrently for snap heal 
3, fix problems due to idle-but-busy peers
4, throttle trie heal requests
> eth, trie: sync with upstream v1.10.26  to solve snap sync issues 

- core/bloom_indexer.go
- core/rawdb/table.go
- ethdb/batch.go
- ethdb/leveldb/leveldb.go
- ethdb/memorydb/memorydb.go
- tests/fuzzers/bn256/bn256_fuzz.go
- tests/fuzzers/stacktrie/trie_fuzzer.go
- trie/iterator_test.go
- trie/trie_test.go
This PR sync from ethereum to preallocate memory in bloom filter when the approximate size of batch is
known in advance.
Leveldb also offers another API called MakeBatch which can
pre-allocate the memory area. So if the approximate size of batch is
known in advance, this API can be used in this case.
And  it's possible that get the need memory size to Batch for BloomIndexer.Commit() in advance.
So it seems better to use NewBatchWithSize() than NewBatch().
None
* adds an addtional API called NewBatchWithSize for db
batcher
* use NewBatchWithSize() than NewBatch() for BloomIndexer.Commit()
> Add NewBatchWithSize API for db and use this API for BloomIndexer.Commit()

- cmd/utils/flags.go
- core/rawdb/database.go
- core/rawdb/prunedfreezer.go
- eth/ethconfig/config.go
This PR, optimized the behavior of the pruneancient flag, making the meaning of 'pruneancient' clearer, and fixed the compatibility issue between pruneancient flag and the snap prune-blocks tool, the changes include the following points:
1. If set the pruneancient flag, the ${datadir}/geth/chaindata/ancient dir will be removed. Restart without the pruneancient flag, the ancient data will start with the previous point that the oldest unpruned block number. This change makes the  ‘pruneancient’ clearer and better compatible with the snap prune-blocks tool.
2. Before this PR once the pruneancient flag is set, it needs to be set every time it starts. Since the ancient data still exists, it will be regarded as part of the blockchain database, but it will destroy the continuity of the database, …
>   fix comments: prune ancient compatibility, add prune ancient comments

- .github/workflows/build-test.yml
- .github/workflows/commit-lint.yml
- .github/workflows/docker-release.yml
- .github/workflows/integration-test.yml
- .github/workflows/lint.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/unit-test.yml
- go.mod
- go.sum
Some GitHub action tools will no longer be supported soon. Update these tools to ensure that CI can normally work in the future.
1. `ubuntu-18.04` => `ubuntu-latest`
2. `macos-11` => `macos-latest`
3. `windows-2019` => `windows-latest`
4. `actions/checkout@v2` => `actions/checkout@v3`
5. `actions/setup-go@v2` => `actions/setup-go@v3`
6. `actions/cache@v2` => `actions/cache@v3`
7. `actions/upload-artifact@v2` => `actions/upload-artifact@v3`
8. `actions/download-artifact@v2` => `actions/download-artifact@v3`
9. `actions/create-release@latest`, `actions/upload-release-asset@v1` => `softprops/action-gh-release@v1`
1. `github.com/go-ole/go-ole v1.2.1` => `github.com/go-ole/go-ole v1.2.6`
N/A
* ci
> ci: update unmaintained tools to use maintained tools

- README.md
The readme is a bit out of date, this PR aims to update it.
1. The hardware requirement for running full node on mainnet needs an update.
2. Add more details about running a fullnode, and the link to the doc website.
3. Add a chapter: `Operating a private network`
No impact to users
None
> docs: update the readme to latest

- README.md
The lint to bsc-deploy repo is wrong, this PR is going to fix it.
Fix the wrong link of bsc-deploy repo
No impact to user
No notable change
> docs: minor fix about the readme

- .github/CONTRIBUTING.md
- README.md
- cmd/checkpoint-admin/README.md
- cmd/devp2p/README.md
- cmd/geth/consolecmd.go
- docs/parlia/README-BEP-127.md
- docs/postmortems/2021-08-22-split-postmortem.md
Some links to the geth website show error 404, this PR is going to update them respectively.
Update the links to the correct ones
No impact to the users
No notable changes
> docs: minor fix on geth links

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
ci: disable CGO_ENABLED when building binary
The current release binary will depend on `GLIBC`, which may make some Users not easy to use, so disable `CGO_ENABLED` in the official release version to remove the dependency on C lib.
https://github.com/j75689/bsc/releases/tag/v1.1.19-rc3
* ci(release)
> ci: disable CGO_ENABLED when building binary

- consensus/parlia/parlia.go
add a check for the length of extraData
#1286 
not related
Notable changes:
- consensus/parlia/parlia.go
> parlia : add a check for the length of extraData.

- .github/workflows/build-test.yml
- .github/workflows/integration-test.yml
- .github/workflows/lint.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/unit-test.yml
- Dockerfile
- docker/Dockerfile
- go.mod
- go.sum
1. [dep: update tendermint to v0.31.14](https://github.com/bnb-chain/bsc/commit/b3f7f73f086503c2e4f3c475c936a846a04a2406)
2. [ci build: remove GOPROXY=direct](https://github.com/bnb-chain/bsc/commit/d4b433e6a839177e8485874649fb7688d876e2f2)
github.com/bnb-chain/tendermint v0.31.13 has been deprecated because checksums on GOPROXY are directed to the wrong version.
N/A
* dep update
* ci
> dep: update tendermint to v0.31.14

- eth/fetcher/block_fetcher.go
Some node report sync sucks, node logs as below:
```bash
t=2023-02-01T07:44:23+0000 lvl=info msg="Imported new chain segment" blocks=1 txs=138 mgas=18.556 elapsed=2.235s mgasps=8.302 number=25,284,893 hash=0x3b08654acd530ea6d793610218f81d9614d3b31b8eeffe7b372fc809ce15fc09 dirty="226.27 MiB" 
t=2023-02-01T07:44:23+0000 lvl=info msg="Chain reorg detected" number=25,284,892 hash=0x331cb0211dab8c564d87583bcf540ba4030b6b69c4e7d6887252b319ed940914 drop=1 dropfrom=0x3b08654acd530ea6d793610218f81d9614d3b31b8eeffe7b372fc809ce15fc09 add=1 addfrom=0xc91bb810c5aca2c562d36335835673f119b2cdf7404ad18e1b1ff223b9ceada2 
t=2023-02-01T07:44:23+0000 lvl=info msg="Imported new chain segment" blocks=1 txs=123 mgas=20.816 elapsed=226.522ms mgasps=91.893 number=25,284,893 …
```
> fix: eth fetcher re-queue issue

- CHANGELOG.md
- Dockerfile
- params/version.go
Release v1.1.19 is a maintenance release, it includes several bug fixes and improvements.
We upgrade the insecure packages in #1274, and fix the sync issue in #1301.
It is recommended to upgrade to the `v1.1.19` for security, and stability.
FEATURE
* [\#1199](https://github.com/bnb-chain/bsc/pull/1199) mointor: implement double sign monitor
IMPROVEMENT
* [\#1226](https://github.com/bnb-chain/bsc/pull/1226) eth, trie: sync with upstream v1.10.26 to solve snap sync issues
* [\#1212](https://github.com/bnb-chain/bsc/pull/1212) metrics: add miner info into metrics server
* [\#1240](https://github.com/bnb-chain/bsc/pull/1240) Add NewBatchWithSize API for db and use this API for BloomIndexer.Commit()
* [\#1254](https://github.com/bnb-chain/bsc/pull/1254) ci: update unmaintained tools to use …
> release: prepare for release v1.1.19

- Dockerfile
The Docker image build failed due to the `bind-tools` version.
N/A
* Dockerfile
> fix: Docker build failed because of invalid `bind-tools` version

- cmd/utils/flags.go
deprecate diffsync flag
When the time for the handshake is around 10s, when sending a message to the diffwait channel at the same time, the waitDiffExtension enters the timeout logic, which will cause a deadlock.
no example
* flag.go:deprecated --diffsync flag and add a warning about it
> cmd/utils/flags.go: --diffsync flag is deprecate.

- consensus/errors.go
- consensus/parlia/parlia.go
- params/config.go
BEP188 introduces a new block broadcast strategy for validators to improve the network capacity and stability. As this BEP allows in-turn validators broadcast mined block earlier, consensus need to adapt to it.
Currently, a mined block will not be broadcasted until the timestamp header.Time is reached, even though the mining process is finished. If an in-turn validator spends too much time in the importing phase, it may not have enough time to mine its own block. In extreme cases, it could generate an empty block or even miss its block. This could be a challenge to the stability of the blockchain.With this BEP, validators could begin to import a block earlier and have more time to mine a new block.
The current consensus engine of the BNB chain does not accept future blocks, which means …
> parlia: consensus changes for Early broadcast 

- consensus/parlia/parlia.go
- consensus/parlia/ramanujanfork.go
This is an implementation of [BEP-172](https://github.com/bnb-chain/BEPs/pull/172) which is meant to enhance the stability of network when slash happened.
Check the [BEP-172](https://github.com/bnb-chain/BEPs/pull/172) for details
N/A
* update `backoffTime` algorithm(consensus/parlia/parlia.go) calculating delay time for `offturn` validators
> parlia: Network Stability Enhancement On Slash Occur BEP-172

- consensus/parlia/parlia.go
no behavior change, only make the code more readable
> refactor the code in func backOffTime()

- accounts/abi/bind/bind_test.go
- core/vm/contracts_lightclient.go
- core/vm/contracts_lightclient_test.go
- core/vm/lightclient/types.go
- go.mod
- go.sum
This pr will add more strict checks for the proofs of lightclient:
+ make sure that the length of proof operations is equal to 2
+ make sure that the proofs are strictly in the desired order
+ check the key format
* add proof ops check and key checker
> sec: add proof ops check and key checker

- consensus/parlia/parlia.go
- core/systemcontracts/upgrade.go
- core/vm/contracts.go
- core/vm/contracts_lightclient.go
- core/vm/contracts_lightclient_test.go
- core/vm/evm.go
- params/config.go
The following BSC upgrades will be named by BLS(Boneh-Lynn-Shacham)
Bohr is too similar to Bonel,  rename Bohr to Planck, to avoid confusion.
> rename: change the next upgrade name to Planck

- consensus/parlia/parlia.go
When `parlia` check the `recent signed` validator, it would get rid of the 1st one in the `snapshot.Recents` (validator of the block with height :header.number-(len(validators)/2+1)) )
delete the 1st validator in recent signed list when do the `backoffTime()` calculation
N/A
* consensus/parlia/parlia.go: `backoffTime()`
> consensus: fix delete the 1st validator from snapshot.recents list

- params/config.go
Planck hard fork will be enabled on height 28196022 for testnet(around 20th Mar)
No
No
No
> upgrade: update the fork height of planck upgrade on testnet

- CHANGELOG.md
- params/version.go
v1.1.20 is a hard-fork release for BSC Chapel testnet.
The Chapel testnet is expected to have a scheduled hardfork upgrade named `Planck` at block height 28,196,022. The current block generation speed forecasts this to occur around 20th Mar 2023 at 01:30 AM (UTC). 
The `Planck` hardfork includes 3 BEPs to enhance network stability and security:
[BEP-171: Security Enhancement for Cross-Chain Module](https://github.com/bnb-chain/BEPs/blob/master/BEP171.md)
[BEP-172: Network Stability Enhancement On Slash Occur](https://github.com/bnb-chain/BEPs/blob/master/BEP172.md)
[BEP-188: Early Broadcast Mature Block For In-Turn Validators](https://github.com/bnb-chain/BEPs/blob/master/BEP188.md)
The validators and full node operators on Chapel testnet should switch their software version to …
> release: prepare for v1.1.20 release

- CHANGELOG.md
- consensus/errors.go
- consensus/parlia/parlia.go
There is many reorg detected when running performance stress test, which is caused by BEP-188.
So revert the code of BEP-188.
NA
NA
NA
> upgrade: remove BEP-188 from planck hardfork

- miner/worker.go
It could happen on node shutdown.
The crash callstack:
NA
NA
NA
> fix: crash on nil access when TxPool shutdown

- docker/Dockerfile
fix truffle test
web3 package not found when exec generate-genesis.js
using package-lock.json works
* ...
> ci: Fix truffle test

- consensus/parlia/parlia.go
- eth/tracers/api.go
support withLog when TraceCall
* ...
> tracer: enable withLog for TraceCall

- core/tx_list.go
- core/vm/contracts_lightclient.go
- core/vm/lightclient/types.go
Several potential risks are detected by scan tool. 
Two type of checks are added in this PR to enhance security:
case 1: out of bounds access to array.
case 2: integer addition overflow.
NA
NA
NA
> fix: add some boundary check for security

- miner/worker.go
cases should be `fallthrough` to use the next statments
* ...
> miner: add fallthrough for switch cases

- core/types/blacklist.go
- eth/protocols/snap/sync.go
fix typo Merkel to Merkle
More Info: 
[https://en.wikipedia.org/wiki/Merkle_tree](url)
core/types/blacklist.go
eth/protocols/snap/sync.go
> typo: fix Merkel to Merkle

- params/config.go
Planck hard fork will be enabled on height 27281024 for mainnet(around 12th April 2023)
No
No
No
> upgrade: update the fork height of planck upgrade on mainnet

- CHANGELOG.md
- params/version.go
v1.1.21 is a hard-fork release for BSC mainnet.
The mainnet  is expected to have a scheduled hardfork upgrade named `Planck` at block height 27,281,024. The current block generation speed forecasts this to occur around 12th April 2023 at 05:30 AM (UTC). 
The `Planck` hardfork includes 2 BEPs to enhance network stability and security:
[BEP-171: Security Enhancement for Cross-Chain Module](https://github.com/bnb-chain/BEPs/blob/master/BEP171.md)
[BEP-172: Network Stability Enhancement On Slash Occur](https://github.com/bnb-chain/BEPs/blob/master/BEP172.md)
The validators and full node operators on mainnet should switch their software version to [v1.1.21](https://github.com/bnb-chain/bsc/releases/tag/v1.1.21) before 12th April 2023.
FEATURE
* …
> release: prepare for release v1.1.21

- miner/worker.go
if the mined block inserted as `sidechain` by the commiter, then shouldn't broadcast it.
details ref: #1382 
test with stress test (tps=800, duration=600s):
- before: reorg_execution=13
- with pr#1382+pr#1383: reorg_executio=0
Reduce `offturn/sidechain` blocks traffic, reduce the probability of reorgs under big transactions traffic.
This could reduce the `offturn/sidechain` network traffic, and 
- since`parlia` is order based, it's unnecessary for validator to broadcast the block mined by itself and considered as `sidechain`.
- under big traffic or bad network condition, the `sidechain` blocks would cause more chaos(reorgs) since validators decided to reorg the head of canonical chain by 50% probability when the ttd were equal.
N/A
* add each change in a bullet point …
> miner: no need to broadcast sidechain header mined by this validator

- consensus/parlia/parlia.go
Fix the issue reported in: https://github.com/bnb-chain/bsc/issues/1345 (Bootstrapping Parlia gobbles up RAM and doesn't show progress)
There is a bug in [parlia.go.snapshot()](https://github.com/bnb-chain/bsc/blob/master/consensus/parlia/parlia.go#L434).
It would traverse the blocks in ancient db until the genesis is reached to get the snapshot, which could be huge if the ancient db already contain a huge number of block(e.g. block 26 million).
Actually there is a soft finality height, which is 90000, it can be used as snapshot trust limit. We can use it to rebuild the snapshot.
NA
NA
NA
> fix: parlia.snapshot() run into trouble after removedb

- log/format.go
- node/config.go
- node/node.go
Support custom time format configuration for `console log` and `file log`
Add `TermTimeFormat` and `TimeFormat` files in config.toml to support custom configuration
`TermTimeFormat` is the time format used for console logging.
`TimeFormat` is the time format used for file logging.
1. Console log
2. File log
* logger
> log: support custom time format configuration

- log/format.go
- node/config.go
- node/node.go
Support custom time format configuration for `console log` and `file log`
Add `TermTimeFormat` and `TimeFormat` files in config.toml to support custom configuration
`TermTimeFormat` is the time format used for console logging.
`TimeFormat` is the time format used for file logging.
1. Console log
2. File log
* logger
> log: support custom time format configuration (#1401)

- Makefile
fix dev tools build error. Ref https://github.com/bnb-chain/bsc/issues/1402
May change `go-bindata` to `go embed` later;
* Fixed the package path of `go-bindata`;
> Makefile: fix devtools install error

- node/config.go
fields of Node.LogConfig is pointer,
when a field is not set, generate config.toml will fail for marshaling nil
* ...
> Fix init network without  setting TimeFormat

- CHANGELOG.md
- params/version.go
Release v1.1.22 is a maintenance release, it includes several bug fixes and improvements.
We upgrade the consensus code to abort unnecessary block sealing or broadcast to reduce the chance of reorg. It could improve the stability of the network.
FEATURE
* [\#1361](https://github.com/bnb-chain/bsc/pull/1361) cmd/faucet: merge ipfaucet2 branch to develop
IMPROVEMENT
* [\#1412](https://github.com/bnb-chain/bsc/pull/1412) fix: init-network with config.toml without setting TimeFormat
* [\#1401](https://github.com/bnb-chain/bsc/pull/1401) log: support custom time format configuration
* [\#1382](https://github.com/bnb-chain/bsc/pull/1382) consnesus/parlia: abort sealing when block in the same height has updated
* [\#1383](https://github.com/bnb-chain/bsc/pull/1383) miner: no need to broadcast …
> release: prepare for release v1.1.22

- Dockerfile
docker: upgrade alpine version & fix apks version error;
`bind-tools` version break frequently, may use the latest default.
* upgrade docker alpine version;
* fix apks version error;
> docker: upgrade alpine version & fix apks version error;

- Dockerfile
opt docker package version problems, change to use latest version.
* docker: upgrade alpine version & remove apks version;
* ...
> docker: upgrade alpine version & remove apks version;

- cmd/evm/internal/t8ntool/transaction.go
- core/bench_test.go
- core/blockchain_test.go
- core/error.go
- core/state_processor_test.go
- core/state_transition.go
- core/tx_pool.go
- core/vm/eips.go
- core/vm/errors.go
- core/vm/gas_table.go
- core/vm/gas_table_test.go
- core/vm/instructions.go
- core/vm/interpreter.go
- core/vm/jump_table.go
- core/vm/jump_table_test.go
- core/vm/opcodes.go
- eth/tracers/api_test.go
- light/txpool.go
- params/protocol_params.go
- tests/transaction_test_util.go
This PR port patches for [EIP-3855: PUSH0 instruction](https://eips.ethereum.org/EIPS/eip-3855) and [EIP-3860: Limit and meter initcode](https://eips.ethereum.org/EIPS/eip-3860)
Corresponding BEPs:
https://github.com/bnb-chain/BEPs/pull/216
https://github.com/bnb-chain/BEPs/pull/217This PR ported patches for [EIP-3855: PUSH0 instruction](https://eips.ethereum.org/EIPS/eip-3855) and [EIP-3860: Limit and meter initcode](https://eips.ethereum.org/EIPS/eip-3860)
Corresponding BEPs:
https://github.com/bnb-chain/BEPs/pull/216
https://github.com/bnb-chain/BEPs/pull/217
> Implement 2 EIPS: limit and meter initcode and PUSH0 instructions

- cmd/faucet/faucet.go
Faucet service would have chance to block when reorg happend.
- imported block with contract_nonce: 10
- reqs: `txs` with nonce: 10, 11
- reorg block with nonce: 7
- reqs: `txs` list grows to: 10, 11, 9(=7+`len{10,11}`)
- reorg block with nonce: 10
- reqs: `txs` list grows to: 10, 11, 9, 13(=10+`len{10,11,9}`)
- GAP: nonce=12
N/A
* clear `reqs` list when `updated nonce` became lower
> cmd/faucet: clear reqs list when reorg to lower nonce

- core/blockchain.go
https://github.com/bnb-chain/bsc/pull/1379 try to fix the random UT fail of TestLargeReorgTrieGC, while it introduced another bug.
It could cause panic crash, since `wg` could be used after it is freed, since there is an asynchronous risk.
For detail of the panic, you may refer: https://github.com/bnb-chain/bsc/issues/1456
To fix the UT fail, we only need to make sure `triedb.Dereference(root.(common.Hash))` can be done in `tryCommitTrieDB()`, so we can just add another `WaitGroup` in `tryCommitTrieDB()` for synchronization.
NA
NA
> fix: panic on using WaitGroup after it is freed.

- CHANGELOG.md
- core/blockchain.go
- params/version.go
Release v1.1.23 is a hot fix release, v1.1.22 has a critical bug, the client could crash due to improperly use of a local variable. 
For detail, just refer the following PR.
BUGFIX
* [\#1464](https://github.com/bnb-chain/bsc/pull/1464) fix: panic on using WaitGroup after it is freed
No API or Command changes.
N/A
> release: prepare for release v1.1.23

- cmd/geth/blsaccountcmd.go
- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- eth/backend.go
- miner/miner.go
1. fix: handle error when fail to import bls account
2. fix: only validator need bls wallet
1. when account password mismatch or key file is bad
report error instead of success
2. add flag to enable voting
geth with '--vote' or configure in config.toml both supported
* ...
> fix: improvements after testing fast finality

- params/config.go
Planck hard fork will be enabled on height [29295050](https://testnet.bscscan.com/block/countdown/29295050) for testnet(around 6:30am on 27th April)
NA
NA
NA
> upgrade: block height of Boneh on testnet

- CHANGELOG.md
- consensus/parlia/abi.go
- consensus/parlia/lubanFork.go
- consensus/parlia/parlia.go
- consensus/parlia/snapshot.go
- core/forkchoice.go
- core/systemcontracts/upgrade.go
- core/vm/contracts.go
- core/vm/evm.go
- eth/gasprice/gasprice_test.go
- eth/handler_eth_test.go
- params/config.go
To follow the naming rule of BNB Chain hard fork, we replace Boneh-Lynn with Luban & Plato.
NA
NA
No impact to users.
> upgrade: rename hardfork to Luban & Plato

- core/vote/vote_journal.go
- core/vote/vote_manager.go
after luban upgrade, voting is enabled, but not use justified number in fork choice;
so it can generate reorg easily as before by shutdown one validator
as in picture:
validator vote for 49578-->49579
then reorg and sourceNumber reset to 49577
all votes after reorg will rejected for span voting
1. there may be great distance between blockNumber and targetNumber
so iterator from sourceNumber + 1 to targetNumber is dangerous
2. just ignore votes for target before targetNumber - maxSizeOfRecentEntry when checking rules
by the way:
this case is just a reason why we require sourceNumber of vote is in a range before block.number
set maliciousVoteSlashScope to 256 is safe:
if current block is n
then target block number is n-1
then iterate begin target number is n-1-256
then …
> fix: all votes rejected for span voting caused by reorg

- consensus/parlia/parlia.go
- consensus/parlia/snapshot.go
attestation of snapshot went to wrong on two machines in old qa env
and can't be fixed by rewinding blocks
1.PR https://github.com/node-real/bsc/pull/64 is to fix a vote attestation security flaw 
but it leads to much more complexity, because of recursive call, as following 
```
verifyVoteAttestation  block n,   nearest checkpoint and before n is m
--> GetJustifiedNumberAndHash block n-1
--> snapshot      block n-1
get snapshot at m
--> verifyVoteAttestation m+1,verifyVoteAttestation m+2...verifyVoteAttestation n-1
...
--> snapshot
--> snapshot      block n-2			
get snapshot at m
--> verifyVoteAttestation m+1,verifyVoteAttestation m+2...verifyVoteAttestation n-2
...
```
it's difficult to analyze the reason when problem generated
so need to simplify update of attestation and keep the vote …
> fix: simplify update of attestation

- core/vote/vote_pool.go
receivedVotes  extend not as expected
when transfer votes from futurevotes to curvotes,
discard invalid votes, but forget to remove it from receivedVotes
* ...
> fix: memory leak of receivedVotes

- p2p/peer.go
The previous PR: https://github.com/bnb-chain/bsc/pull/1484/, raised the log level from trace to warn, try to print more log on P2P error.
But it turns out the warning log will spam over the screen.
Complain received in https://github.com/bnb-chain/bsc/issues/1526
Revert the level to trace.
NA
NA
> log: revert a log back to trace level (#1527)

- cmd/utils/flags.go
refer to https://github.com/bnb-chain/bsc/issues/1536
Set it to default only when BLSWalletDir is empty and there is no flag for it
So is VoteJournalDir.
* ...
> fix: config for VoteJournalDir and BLSWalletDir

- consensus/parlia/parlia.go
- consensus/parlia/snapshot.go
- core/vote/vote_journal.go
- core/vote/vote_manager.go
- core/vote/vote_pool.go
- core/vote/vote_signer.go
1. dynamic metrics labels make metrics too large to display
votesManagerMetric --> votesManagerCount
votesSigningErrorMetric-->votesSigningError and log.Error
2. unify error metrics about fast finality
verifyVoteAttestationFailedGauge--> verifyVoteAttestationError
updateAttestationFailedGauge--> updateAttestationError
"voteJournal/local"-->"voteJournal/error"
3. NewRegisteredCounter instead of NewRegisteredGauge
* ...
> fix: remove dynamic metric labels about fast finality

- eth/handler_bsc.go
for now,
p2p protocol run as normally even when bsc extension failed to handshake.
even if we don't drop p2p connect with nill bsc extension,
an error log should be output, to provide info for  analysing by node runner
* ...
> fix: output an error log when bsc extension fail to handshake

- core/rawdb/schema.go
I noticed this redundant operation.
So I removed the unnecessary append.
Less operation - faster node :)
> x = append(y) is equivalent to x = y

- core/vm/evm.go
- core/vm/logger.go
- eth/tracers/js/goja.go
- eth/tracers/js/internal/tracers/call_tracer_legacy.js
- eth/tracers/js/tracer_test.go
- eth/tracers/logger/access_list_tracer.go
- eth/tracers/logger/logger.go
- eth/tracers/logger/logger_json.go
- eth/tracers/native/4byte.go
- eth/tracers/native/call.go
- eth/tracers/native/noop.go
- eth/tracers/native/prestate.go
This PR is a cherry-pick of [go-ethereum/#26291](https://github.com/ethereum/go-ethereum/pull/26291). It drops the `time` field of `vm.EVMLogger.CaptureEnd`.
> This removes the 'time' field from logs, as well as from the tracer interface. This change makes the trace output deterministic.  If a tracer needs the time they can measure it themselves. No need for evm to do this.
Stay up to date with go-ethereum improvements.
> eth/tracers, core/vm: remove `time` from `vm.EVMLogger`

- consensus/parlia/parlia.go
it's from a FQA 'for validators, How To Check If Vote Works?'
here add a counter to check it easily.
1.add log at debug level is not good, it's will force validators to set log level to debug, which will lead to log spam,
so add a metric is a better way.
2. votesManagerCounter is not  accurate
because, after validator set up vote key locally, votesManagerCounter will increase,
even before using bsc-edit-validtor to add vote key
3. when VerifyVote == true, it shows that
a. vote key is set right locally and vote has passed bls signature verification by func basicVerify
b. can get vote key from snapshot, so vote key is properly added by using  bsc-edit-validtor
c. bsc p2p is enabled by default
so we can add a counter in VerifyVote to detect whether Voting Works right
add an example CLI or …
> metrics: add a counter for validator to check work status of voting

- eth/protocols/snap/handler.go
- eth/protocols/snap/sync_test.go
These tests fail randomly, including `TestMultiSyncManyUselessWithLowTimeout`, and `TestMultiSyncManyUnresponsive` in `eth/protocols/snap`.
you could reproduce it by following:
```bash
seq 1 20 | parallel go test -count=10 ./eth/protocols/snap -run "TestMultiSyncManyUselessWithLowTimeout" -failfast
```
Because of append empty slot to results, cause err "Remote side rejected our delivery: more entries available".
* eth/protocols/snap: fix flaky test, don't include empty snapshot slot slice;
> fix: fix snap flaky tests

- cmd/bootnode/main.go
- eth/backend.go
- eth/protocols/eth/discovery.go
- p2p/discover/common.go
- p2p/discover/table.go
- p2p/discover/table_test.go
- p2p/discover/table_util_test.go
- p2p/discover/v4_udp.go
- p2p/discover/v5_udp.go
- p2p/discover/v5_udp_test.go
- p2p/server.go
This PR implements [BEP194](https://github.com/bnb-chain/BEPs/pull/194)
This change should improve peer discovery time by filtering out peers from different networks e.g. ETH
* adding peer do the table is now async as it also requires to get ENR record from the node
* this could also help to filter out nodes, that are not running latest HF
> p2p/discover: implement ENR node filtering

- params/config.go
Planck hard fork will be enabled on height [29861024](https://testnet.bscscan.com/block/countdown/29861024) for testnet(around 6:30am on 17th May)
NA
NA
NA
> upgrade: block height of Plato on testnet

- consensus/parlia/parlia.go
- consensus/parlia/snapshot.go
The first validator in snap.Recents is shifted out and allowed to seal the block already. However, when determining if we should slash the validator in Finalize and FinalizeAndAssemble, we mark that first validator as unable to seal block and don't slash this validator. This commit fixes that bug and creates a separate helper function to check if the validator recently signed a block for consistency in all places the check happens.
> fix: recently signed check when slashing unavailable validator

- CHANGELOG.md
- params/version.go
v1.2.2 is a hard-fork release for BSC testnet.
The Chapel testnet is expected to have a scheduled hardfork upgrade named `Plato` at block height 29,861,024. The current block generation speed forecasts this to occur around 17th April 2023 at 06:30 AM (UTC). 
The `Plato` hard fork only includes 1 BEPs:
[BEP-126: Introduce Fast Finality Mechanism 6(The 2st Part)](https://github.com/bnb-chain/BEPs/blob/master/BEP126.md)
The validators and full node operators on Chapel testnet should switch their software version to [v1.2.2](https://github.com/bnb-chain/bsc/releases/tag/v1.2.2) before 17th May 2023.
FEATURE
* [\#1574](https://github.com/bnb-chain/bsc/pull/1574) upgrade: update PlatoUpgrade contracts code
* [\#1594](https://github.com/bnb-chain/bsc/pull/1594) upgrade: block height of Plato on …
> release: prepare for release v1.2.2

- core/systemcontracts/upgrade.go
we need restart bsc after modifying RialtoGenesisHash if there is a code upgrade in test network for QA
add latestUpgrade and let it point to latest code upgrade
* ...
> upgrade: avoid to modify RialtoGenesisHash and restart when testing in rialtoNet

- core/vm/contracts.go
- core/vm/evm.go
- eth/gasprice/gasprice_test.go
- eth/handler_eth_test.go
- params/config.go
Enable Berlin EIPs by including the BerlinBlock in BSCChainConfig
This enable following Berlin EIPs into the BSC:
[EIP-2565](https://eips.ethereum.org/EIPS/eip-2565): ModExp Gas Cost
[EIP-2929](https://eips.ethereum.org/EIPS/eip-2929): Gas cost increases for state access opcodes
[EIP-2718](https://eips.ethereum.org/EIPS/eip-2718): Typed Transaction Envelope
[EIP-2930](https://eips.ethereum.org/EIPS/eip-2930): Optional access lists
Introducing the Berlin upgrade to BSC.
* Most of the Berlin EIPs implementation code are exist but not enabled for bsc, this change simply enable those eips by adding the Berlin block number to BSC chain config.
* This PR also introduce the HertzBlock for BSC, as an umbrella for covering EIPs of Berlin and (maybe) afterwards London.
> feature: Enable Berlin EIPs

- CHANGELOG.md
- params/config.go
- params/version.go
v1.2.4 is a hard-fork release for BSC mainnet.
The mainnet is expected to have a scheduled hardfork upgrade named `Luban` at block height 29,020,050. The current block generation speed forecasts this to occur around 12th Jun 2023. 
The `Luban` hardfork includes 3 BEPs:
[BEP-126: Introduce Fast Finality Mechanism 6(The 1st Part)](https://github.com/bnb-chain/BEPs/blob/master/BEP126.md)
[BEP-174: Cross Chain Relayer Management 5](https://github.com/bnb-chain/BEPs/blob/master/BEP174.md)
[BEP-221: CometBFT Light Block Validation](https://github.com/bnb-chain/BEPs/pull/221)
The validators and full node operators on mainnet  should switch their software version to [v1.2.4](https://github.com/bnb-chain/bsc/releases/tag/v1.2.4) before 12th Jun 2023.
FEATURE …
> release: draft release v1.2.4

- README.md
Tried with this command:
./geth --tries-verify-mode none --config ./config.toml --datadir ./node  --cache 8000
Sync to block: 28459251(May 23 2023), it takes ~2.1TB
NA
NA
NA
> readme: update the disk requirement to 2.5TB

- consensus/parlia/parlia.go
- consensus/parlia/snapshot.go
- core/types/vote.go
remove naturally finality
naturally finality is alias of probabilistic finality in the code.
1. The probabilistic finality is only probabilistic. In extreme cases, it may be reverted without penalty, so it is not suitable to acknowledge it through the interface
2. Different application scenarios of probabilistic finality may choose different numbers of blocks. For example, 15 is recommended, while the main station uses 21 for deposits and withdrawals. but only a fixed number can be specified in the code
3. The Ethereum client will also degenerate to a probabilistic finality when the vote fails, but the number of blocks is not specified in the code; Bitcoin has probabilistic finality, and the number of blocks is not specified in the code
Notable …
> fix: remove naturally finality

- eth/handler.go
fix ungraceful shutdown caused by malicious Vote Monitor
can't shutdown malicious vote monitor now,
votesSub.Unsubscribe() and votesSub.Err() wait for each other
* ...
> fix: ungraceful shutdown caused by malicious Vote Monitor

- consensus/parlia/parlia.go
- consensus/parlia/snapshot.go
- core/rawdb/chain_iterator.go
- miner/worker.go
Some logs are not needed to be shown to an average user, so they can be downgraded from "info" to "debug".
Refer: #1650
It helps to improve the UX.
The following are the logs of a mock validator:
```
t=2023-05-31T02:21:16+0000 lvl=info msg="The validator is not authorized"       addr=0xB8f7166496996A7da21cF1f1b04d9B3E26a3d077
t=2023-05-31T02:21:17+0000 lvl=info msg="The validator is not authorized"       addr=0xB8f7166496996A7da21cF1f1b04d9B3E26a3d077
t=2023-05-31T02:21:17+0000 lvl=info msg="The validator is not authorized"       addr=0xB8f7166496996A7da21cF1f1b04d9B3E26a3d077
t=2023-05-31T02:21:17+0000 lvl=info msg="Commit new mining work"                number=28,679,795 sealhash=0xdbdd4f52de9f2a433d55defdd2a036effcab25f3439f5a93c69e89f1be134f06 uncles=0 txs=120  gas=9,680,235 …
```
> consensus, core/rawdb, miner: downgrade logs

- accounts/abi/bind/bind_test.go
- go.mod
- go.sum
this PR: https://github.com/bnb-chain/bsc/pull/936 upgraded the goleveldb indirectly, since it has dependency of prysm, which also depends on goleveldb indrectly.
But the new version has some performance issue on Database Close, see: https://github.com/syndtr/goleveldb/issues/434
So we need to rollback to the previous verison
The issue has been described in: https://github.com/bnb-chain/bsc/issues/1674
NA
NA
No impact to users.
> goleveldb: downgrade the version for performance

- cmd/utils/flags.go
- core/vote/vote_manager.go
- core/vote/vote_pool_test.go
- eth/backend.go
- miner/miner.go
voting can only be enabled when mining
The node operator generally starts two nodes with the same consensus key. After having ff, the node will configure the same vote key.
After startup, use miner.stop() and miner.start() in geth console to switch out block nodes.
If the --vote option is used when both nodes are started, conflicting votes will be cast, which will be judged as malicious voting.
the solution is as following:
neither mining decide voting, nor they are independent
Instead, let mining be a prerequisite of voting
* ...
> fix: voting can only be enabled when mining

- core/vm/lightclient/v2/lightclient.go
This pr will check the integer overflow when decoding the cross-chain payload for light client check.
Check integer overflow.
N/A
* check integer overflow when decode cross-chain payload
> fix: check integer overflow when decode cross-chain payload

- CHANGELOG.md
- accounts/abi/bind/bind_test.go
- go.mod
- go.sum
- params/version.go
Release v1.2.5 is a maintenance release, it only has one patch to fix a bug of node shutdown.
The bug could cause nodes take very long time to shutdown, for a validator it could increase its chance of been slashed.
It is suggested for validators to upgrade to this version.
BUGFIX
* [\#1675](https://github.com/bnb-chain/bsc/pull/1675) goleveldb: downgrade the version for performance
No API or Command changes.
N/A
> release: draft release v1.2.5

- core/chain_makers.go
- miner/worker.go
chain will be blocked upon london upgrade, failed to verify gaslimit 
gas limit doubled  by following code
`                       parentGasLimit := parent.GasLimit() * params.ElasticityMultiplier
header.GasLimit = CalcGasLimit(parentGasLimit, parentGasLimit)
`
failed to verify gas limit in func verifyCascadingFields
`
if uint64(diff) >= limit || header.GasLimit < params.MinGasLimit {
return fmt.Errorf("invalid gas limit: have %d, want %d += %d", header.GasLimit, parent.GasLimit, limit)
}
`
we may 
1. not need to double gaslimit of block upon London upgrade
2. or change logic of verify in func verifyCascadingFields
this PR choose first way to solve out, because base fee of bsc is always 0, 
no concept of `gas target`, so there is no need to double the gaslimit .
add an example CLI or API …
> fix: not double GasLimit of block upon London upgrade

- consensus/parlia/parlia.go
update signer of parlia after london upgrade
chain will be blocked when get a EIP1559 tx.
EIP1559 tx can be handled when generating a new block, 
because  func MakeSigner will return the newest signer
```
func (w *worker) makeEnv(parent *types.Block, header *types.Header, coinbase common.Address...
// Note the passed coinbase may be different with header.Coinbase.
env := &environment{
signer:    types.MakeSigner(w.chainConfig, header.Number),
state:     state,
coinbase:  coinbase,
...
}
```
but when a validator replay txs of blocks form others, it use the signer of parlia 
which is a EIP155Signer
```
func (p *Parlia) IsSystemTransaction(tx *types.Transaction, header *types.Header) (bool, error) {
// deploy a contract
if tx.To() == nil {
return false, nil
}
sender, err := …
```
> fix: set the signer of parlia to the most permissive one

- core/eip3529tests/eip3529_ethash_test.go
- core/eip3529tests/eip3529_parlia_test.go
- core/eip3529tests/eip3529_test_util.go
Refactor tests to avoid duplication of helper `testGasUsage` function by putting eip3529 tests in a new package.
> eip3529tests: refactor tests

- core/eip3529tests/eip3529_ethash_test.go
- core/eip3529tests/eip3529_parlia_test.go
- core/eip3529tests/eip3529_test_util.go
- core/parlia_tests/blockchain_eip_3529_test.go
- params/config.go
In this PR a test config `TestChainParliaConfig` that uses the Parlia engine is introduced for unit testing purposes.
This config is used to add unit tests for [EIP-3529/BEP-212](https://github.com/bnb-chain/BEPs/pull/212) . 
There are already tests for EIP-3529 targeting the  default `TestChainConfig` which uses a fake ethash engine. 
In this PR, additional test cases are included targeting `TestChainConfig`, and the same test cases are replicated for `TestChainParliaConfig`.
Since in the Hertz hard fork Berlin and London EIPs will be applied simultaneously, the expected gas usage values between the ethash unit tests and  Parlia config unit tests for EIP-3529 are different in some cases.
This is because of different VM instructionsets before the EIP-3529 is applied:
| Config  | …
> EIP-3529 (BEP-212) Unit tests for Parlia Config

- core/genesis.go
Refer: https://github.com/bnb-chain/bsc/issues/1625
Also refer: https://github.com/bnb-chain/bsc/issues/1625
With this PR, users no longer need to setup this section in config.toml:
```
[Eth.Genesis.Config]
...
```
But if he/she wanna to change the fork height in his QA env, still can set in config.toml
Only a UX improve, no other impact.
> config: use default fork config if not specified in config.toml

- core/blockchain_test.go
> test: Add EIP-2718 unit test for parlia ChainConfig

- core/state/statedb.go
always clear out access list when setting a new one
porting from 
https://github.com/ethereum/go-ethereum/commit/48605b5f61f7ce63cb3148099047309156c959a9
* ...
> core/statedb: always clear out access list when setting a new one

- core/genesis.go
- core/genesis_test.go
Set the deault block values of genesis config  using reflection, to avoid a long sequence of if-statements.
For more context:
https://github.com/bnb-chain/bsc/issues/1625
Maintaining a long sequence of if-statements with hardcoded block names is not scalable as more hard forks are introduced in BSC. Forgetting to update the code when a new hard fork happens would result in a wrong config. 
A more robust way is to use reflection to achieve the same result, without having to worry about keeping the file up-to-date every time there is a hard fork. This way the code is also kept short.
* `genesis.go` : replace long series of if-statements with a `setDefaultBlockValues` method which uses the `.*Block` regex and reflection to achieve the same result.
* `genesis_test.go`: add …
> core: use reflection to set default block values

- CHANGELOG.md
- params/config.go
- params/version.go
v1.2.6 is a hard-fork release for BSC testnet.
The testnet is expected to have a scheduled hardfork upgrade named `Hertz(London&Berlin)` at block height 31,103,030. The current block generation speed forecasts this to occur around 29th Jun 2023. 
The `Hertz` hardfork will port some of `London&Berlin` upgrades from Ethereum to BSC for compatiblity. But due to the difference between the 2 networks, there would inevitably has difference in implementation, especially the different in EIP-1559, the BaseFee will be zero on BSC, so this hard fork will not introduce new burn mechanism neither the concept of GasTip. In short words, it only provides the interface, but actually no change to the current BSC Gas mechanism.
Here is the list of `Hertz` upgrade:
- Berlin Upgrades Ported:
a.[BEP-225: …
> release: prepare for release v1.2.6

- eth/peerset.go
The `headPeers` method is introduced in #570, but in fact the passed `num` does not take effect, and always returns all peers
`ps.peers` will range all peers to the list.
n/a
* p2p
> p2p: fix length calculation for headPeers method

- consensus/parlia/parlia.go
add counter for voting status of whole network
need to monitor voting status of whole network
even not get metrics from all validators
* ...
> metrics: add counter for voting status of whole network

- cmd/geth/blsaccountcmd.go
1. support creating a bls keystore from a specified private key
2. support showing private keys in hex format when generating a new bls keystore
1. we may want to generate a keystore from a  specified private key
2. we may want to know the private key when generating a new bls keystore
two local flags for `geth bls account new` are added
> feat: support creating a bls keystore from a specified private key

- CHANGELOG.md
- params/version.go
v1.2.7 replaces [v1.2.6](https://github.com/bnb-chain/bsc/pull/1697) as the official **hertz** hard-fork release for BSC testnet.
It mainly add a bug fix on the precompiled contract(address: 103):
```
// before hertz
common.BytesToAddress([]byte{103}): &cometBFTLightBlockValidate{},
// after hertz
common.BytesToAddress([]byte{103}): &cometBFTLightBlockValidateHertz{},
```
FEATURE
* [\#1645](https://github.com/bnb-chain/bsc/pull/1645) lightclient: fix validator set change
* [\#1717](https://github.com/bnb-chain/bsc/pull/1717) feat: support creating a bls keystore from a specified private key
* [\#1720](https://github.com/bnb-chain/bsc/pull/1720) metrics: add counter for voting status of whole network
NA
The precompiled contract 103 is introduced by [Luban …
> release: prepare for release v1.2.7

- eth/protocols/bsc/peer.go
avoid to block the chain when failed to send votes 
fix issue: https://github.com/bnb-chain/bsc/issues/1732
when failed to `sendVotes`, votes in channel `voteBroadcast` will not be consumed
thus lead to stuck of `AsyncSendVotes` 
`putIntoVotePool` will stuck because  `pool.votesFeed.Send(voteEv)` stuck
then `chainHeadCh` will not be consumed in vote pool and vote manager,
then the chain is stuck
solve out:
1. when failed to `sendVotes`, drop new votes to avoid block the chain
2. add a buffer for channel `voteBroadcast` to avoid to drop votes by chance
* ...
> fix: avoid to block the chain when failed to send votes

- CHANGELOG.md
- params/version.go
Release v1.2.8 is a maintenance release, it mainly fixes a potential deadlock on FastFinality VotePool and provides 2 other features(FastFinality & Web3 API related).
FEATURE
* [\#1626](https://github.com/bnb-chain/bsc/pull/1626) eth/filters, ethclient/gethclient: add fullTx option to pending tx filter
* [\#1726](https://github.com/bnb-chain/bsc/pull/1726) feat: support password flag when handling bls keys
BUGFIX
* [\#1734](https://github.com/bnb-chain/bsc/pull/1734) fix: avoid to block the chain when failed to send votes
- usage of `eth_newPendingTransactionFilter` has been changed, it will return full transaction content, rather then pure hash
- a new flag: `--blsaccountpassword ` is provided to specify the password file to managing votes in fast_finality feature
N/A
> release: prepare for release v1.2.8

- CHANGELOG.md
- cmd/geth/blsaccountcmd.go
- eth/filters/api.go
- eth/filters/filter_system.go
- eth/filters/filter_system_test.go
- eth/protocols/bsc/peer.go
- ethclient/gethclient/gethclient.go
- ethclient/gethclient/gethclient_test.go
- params/version.go
Release v1.2.8 is a maintenance release, it mainly fixes a potential deadlock on FastFinality VotePool and provides 2 other features(FastFinality & Web3 API related).
FEATURE
* [\#1626](https://github.com/bnb-chain/bsc/pull/1626) eth/filters, ethclient/gethclient: add fullTx option to pending tx filter
* [\#1726](https://github.com/bnb-chain/bsc/pull/1726) feat: support password flag when handling bls keys
BUGFIX
* [\#1734](https://github.com/bnb-chain/bsc/pull/1734) fix: avoid to block the chain when failed to send votes
- usage of `eth_newPendingTransactionFilter` has been changed, it will return full transaction content, rather then pure hash
- a new flag: `--blsaccountpassword ` is provided to specify the password file to managing votes in fast_finality feature
N/A
> release: draft release v1.2.8

- consensus/parlia/parlia.go
- eth/handler.go
- eth/handler_bsc.go
- eth/protocols/bsc/peer.go
defend ddos voting attack with other mini fix according to audit
1. change type of collectAdditionalVotesRewardRatio to int from float
2. defend ddos voting attack by limit the arrival rate of votes from other peers
a. force only one vote sent every time, to avoid ddos attack, which batching a large number of votes
b. set a max number in every period, when extra it , votes will be dropped
* ...
> fix: defend ddos voting attack with other mini fix according to audit

- cmd/bootnode/main.go
- p2p/discover/common.go
- p2p/discover/table.go
- p2p/discover/table_util_test.go
- p2p/discover/v4_udp.go
- p2p/discover/v5_udp.go
The present discovery protocol employs a Distributed Hash Table (DHT), which is organized into "buckets." Each bucket presently stores 16 entries, and there is a total of 17 buckets. This configuration allows for a capacity of 272 node records per individual node.
```
bucketSize        = 16 // Kademlia bucket size
hashBits          = len(common.Hash{}) * 8
nBuckets          = hashBits / 15       // Number of buckets
```
I propose increasing the `bucketSize` value to 256, which is 16 times its current size. Since the bootnode binary is extremely lightweight, this change should not impact overall performance, and it could substantially enhance the discovery process.
> discov: increase bucket size for bootnodes

- CHANGELOG.md
- params/config.go
- params/version.go
Release v1.2.9 is a hard fork release for BSC mainnet.
It sets up the hard fork height for both Plato and Hertz(Berlin,London).
- Plato: fully enable FastFinality at block height: [30,720,096](https://bscscan.com/block/countdown/30720096), around Aug-10-2023
- Hertz: several customized EIPs of Berlin&London on BSC, at block height: [31,302,048](https://bscscan.com/block/countdown/31302048), around Aug-30-2023
The two hard forks have been running on Testnet for a while and their hard fork height are close, so we decide to put them within a single release to save the upgrade effort.
For the detail changes of the two hard fork, pls refer: https://forum.bnbchain.org/t/bnb-chain-upgrades-mainnet/936
FEATURE
* [\#1775](https://github.com/bnb-chain/bsc/pull/1775) upgrade: several hardfork block …
> release: prepare for release v1.2.9

- p2p/server.go
Our current ENR filtering will remove nodes, that do not report `eth` field, but that's not correct and we should keep them in  DHT.
With these changes we can connect to the bootnodes just fine
> discov: do not filter out bootnodes

- eth/handler_bsc.go
- eth/protocols/bsc/peer.go
reduce logs when receiving too much votes from a peer
some peers or peers at sometimes may import a batch blocks from others,
then will trigger votes transferring fro future queue to cur queue,
it may be quite a lot votes and extra the expected limit.
we can still drop these votes, because they are not timely and not useful,
but we should reduce logs as well.
* ...
> log: reduce logs when receiving too much votes from a peer

- consensus/parlia/parlia.go
- internal/ethapi/api.go
add GetFinalizedHeader/Block to simplify using the fast finality feature
the fast finality feature  may not work stable in early time or in some extreme scenes, 
then the chain will decade back to probabilistic finality.
we need more simple APIs to handle block finality easily regardless of the status of fast finality mechanism.
here comes in this PR
```
//  eth_getFinalizedHeader returns the requested finalized block header.
//   - probabilisticFinalized should be in range [2,21],
//     then the block header with number `max(fastFinalized, latest-probabilisticFinalized)` is returned
eth_getFinalizedHeader(probabilisticFinalized int64)
//  eth_getFinalizedBlock returns the requested finalized block.
//   - probabilisticFinalized should be in range [2,21],
//     then the block with …
```
> rpc: add GetFinalizedHeader/Block to simplify using the fast finality feature

- cmd/geth/config.go
- cmd/utils/flags.go
add TxPool info into metrics server
n/a
1. /debug/metrics/prometheus
* cmd/utils/flags.go
* cmd/geth/config.go
> metrics: add TxPool info into metrics server

- core/monitor/malicious_vote_monitor.go
- core/monitor/malicious_vote_monitor_test.go
fix: exclude same votes when doing malicious voting check
even we have used `receivedVotes` to mark votes received,
in a corner cases, a vote has been pruned, then a reorg to older block happened
so the pruned votes can be received again, this will lead to alert malicious vote in a wrong way
so add more check in monitor.
* ...
> fix: exclude same votes when doing malicious voting check

- core/vote/vote_manager.go
- core/vote/vote_pool.go
- core/vote/vote_signer.go
backup validator sync votes from corresponding mining validator
node operator often start two nodes, one is mining and the other one backup,
these two nodes have the same consensus address and voting key.
when switch the backup validator to mining, because of lacking of votes recently, It may violate voting rules.
this PR address this issue, and sync votes for backup validators from mining validators and write synced votes to `voteJournal`
* ...
> vote: backup validator sync votes from corresponding mining validator

- consensus/parlia/parlia.go
finality: add more check to ensure reuslt of assembleVoteAttestation
drop attestation when two same votes included or vote with invalid validator included
by the way, these two senses have been excluded by func basicVerify and verifyVote, 
but assembleVoteAttestation should depend them less
* ...
> finality: add more check to ensure reuslt of assembleVoteAttestation

- CHANGELOG.md
- params/version.go
Release v1.2.10 is a maintenance release for BSC mainnet and testnet.
It fixed one bug for bootnode and two bugs for FastFinality feature. And it did some enhancement to FastFinality feature, like less log, attestation check, rpc API.
Validators are encouraged to use this version, other full node operators can skip this version if they have already upgraded to v1.2.9
FEATURE
* [\#1780](https://github.com/bnb-chain/bsc/pull/1780) log: reduce logs when receiving too much votes from a peer
* [\#1788](https://github.com/bnb-chain/bsc/pull/1788) metrics: add txpool config into metrics server
* [\#1789](https://github.com/bnb-chain/bsc/pull/1789) rpc: add GetFinalizedHeader/Block to simplify using the fast finality feature
* [\#1791](https://github.com/bnb-chain/bsc/pull/1791) finality: add …
> release: prepare for release v1.2.10

- ethclient/ethclient.go
client: add FinalizedHeader/Block to use the fast finality
client code related [PR1789](https://github.com/bnb-chain/bsc/pull/1789)
* ...
> client: add FinalizedHeader/Block to use the fast finality

- core/rawdb/accessors_chain.go
Lagging nodes failed to sync, always reports error:
```
t=2023-08-17T13:03:54+0000 lvl=warn msg="Synchronisation failed, dropping peer" peer=3370c8d6dd40e099671c327795dc93286a1a80c330a28052cb9afedbb18e3225 err="retrieved hash chain is invalid: no peers available or all tried for download"
```
After investigation, it was caused by bigger block.Header for FastFinality.
Could refer: https://github.com/bnb-chain/bsc/issues/1830
FastFinality puts more information into the header.extra field to keep vote information. For mainnet, on epoch height, it could be 1526 bytes, which was 517 bytes before. So the hardcoded 700 bytes for header could be no longer enough, increase it by 2 times would be enough.
this bug could cause P2P sync failure for nodes that are lagging behind, since they would …
> fix: lagging nodes failed to sync

- CHANGELOG.md
- params/version.go
Release v1.2.11 is another maintenance release for BSC mainnet and testnet.
It mainly fixed a sync bug, for peers that are lagging behind too much blocks(>90,000), it may not be able to sync.
And it also provides a new option to disable attestation: `--disablevoteattestation` on some special cases and the option `--disablebscprotocol` was abandoned.
FEATURE
* [\#1797](https://github.com/bnb-chain/bsc/pull/1797) client: add FinalizedHeader/Block to use the fast finality
* [\#1805](https://github.com/bnb-chain/bsc/pull/1805) vote: remove DisableBscProtocol and add flag to skip votes assmebling
BUGFIX
* [\#1829](https://github.com/bnb-chain/bsc/pull/1829) fix: lagging nodes failed to sync
NA
NA
> release: prepare for release v1.2.11

- eth/fetcher/block_fetcher.go
- eth/fetcher/block_fetcher_test.go
- eth/handler.go
Currently, block fetcher would accept blocks with a limited distance, it is mainly for side chain.
As maxUncleDist = 11, maxQueueDist = 32, the acceptable block range is: [CurrentBlock - 11, CurrentBlock + 32]
But with FastFinality enabled, BSC has deterministic finality, it is no necessary to fetch block before or equal the finalized height.
This PR fixes: https://github.com/bnb-chain/bsc/issues/1847
NA
NA
No Impact To Users
> fetcher: no import blocks before or equal to the finalized height

- core/vm/logger.go
- eth/tracers/api.go
- eth/tracers/js/goja.go
- eth/tracers/logger/access_list_tracer.go
- eth/tracers/logger/logger.go
- eth/tracers/logger/logger_json.go
- eth/tracers/native/4byte.go
- eth/tracers/native/call.go
- eth/tracers/native/mux.go
- eth/tracers/native/noop.go
- eth/tracers/native/prestate.go
Fix https://github.com/bnb-chain/bsc/issues/1835.
Process system tx won't sub intrinsicGas, but when trace tx, it would sub intrinsicGas.
* add a new interface to edit trace call stack
* ...
> eth/tracers: trace system tx should add intrinsicGas

- cmd/geth/chaincmd.go
This PR modifies the behavior of the `init-network` command so that:
- it no longer writes the genesis config to the `config.toml` of the nodes, but writes it to `genesis.json` instead.
- nodes on the same host use different ports, while nodes in different hosts use the same port.
-  split the long function into smaller functions.
- Uses bootstrap nodes instead of static nodes to setup the p2p connections among nodes.
The `init-network` command is used by the [node-deploy](https://github.com/bnb-chain/node-deploy/) repository to generate the configs for a local cluster of BSC nodes. The command receives a size for the network and `config.toml` and `genesis.json` and produces a folder structure where the subfolders are the configurations for the individual nodes in the network.
The …
> Update init-network command

- CHANGELOG.md
- params/version.go
Release v1.2.12 is a maintenance release for BSC mainnet and testnet.
It mainly support BootNodes on BSC mainnet, it would be easier for user to sync with the BSC network.
And it also fixed three bugs to make the node more reliable, not critical bugs, pls check the change list for detail.
FEATURE
* [\#1852](https://github.com/bnb-chain/bsc/pull/1852) discov: add hardcoded bootnodes
BUGFIX
* [\#1844](https://github.com/bnb-chain/bsc/pull/1844) crypto: Update BLST to v0.3.11
* [\#1854](https://github.com/bnb-chain/bsc/pull/1854) fetcher: no import blocks before or equal to the finalized height
* [\#1855](https://github.com/bnb-chain/bsc/pull/1855) eth/tracers: trace system tx should add intrinsicGas
IMPROVEMENT
* [\#1839](https://github.com/bnb-chain/bsc/pull/1839) Update init-network …
> release: prepare for release v1.2.12

- build/ci.go
- cmd/devp2p/internal/ethtest/helpers.go
- cmd/devp2p/internal/ethtest/suite_test.go
- cmd/devp2p/internal/ethtest/types.go
- cmd/evm/t8n_test.go
run full unit test cases, except ./tests
in unit test CI,  in dir `cmd`, only test cases in `geth` is executed
some important cases in cmd/devp2p, cmd/evm are broken and ignored
this PR fix them, and let all cases in dir `cmd` are tested
```
cd cmd
go test ./... -v 
```
* ...
> build: run full unit test cases, except ./tests

- core/state/state_object.go
- core/state/statedb.go
handle account destruction after updating account state
1. `handleDestruction` depend on `accounts` and this map will be updated when `updateStateObject`,
so move `handleDestruction` after `updateStateObject`, otherwise will **pathdb** will behavior unexpectedly.
2. check err returned by `commmitTrie`
3. revert logic of New statedb to support new a statedb when OpenTrie failed(for example, no trie data)
1.  avoid copy accounts and storages twice in `copyInternal`
2. avoid both update accounts in `AccountsIntermediateRoot` and `StateIntermediateRoot`
3. make two funcs in `commitFuncs` run in parallel
use `types.EmptyRootHash` instead of `common.Hash{}` to express empty root hash of account
* …
> core/state: handle account destruction after updating account state

- go.mod
- p2p/discover/v4_udp.go
- p2p/enode/nodedb.go
As adding metrics is kind of complex thing for bootnode. Adding simple log will be enough. 
```
INFO [09-18|16:42:21.369] Current status                           table_size=889 pending_size=0 db_size=630,543
```
* ...
> discov: add status log for bootnode

- core/rawdb/freezer_table.go
This reverts commit [b9ba6f6e4d86d0ee86c63e8f4552e233fe0450aa](https://github.com/ethereum/go-ethereum/pull/26009).
dir `chaindata` generated by old version of geth(before big merge)  doesn't contain *meta files which are used to `tail deletion`.
so for back-compatible, still open meta file in append mode even readonly flagged.
* ...
> Revert "core/rawdb: open meta file in read only mode (#26009)"

- cmd/evm/t8n_test.go
- cmd/geth/consolecmd_test.go
- cmd/utils/flags.go
- consensus/parlia/parlia.go
- core/blockchain.go
- core/genesis.go
- core/state/snapshot/generate.go
- core/vote/vote_manager.go
- core/vote/vote_pool.go
- core/vote/vote_pool_test.go
- eth/backend.go
- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
- eth/handler_eth_test.go
- eth/sync.go
- les/client.go
- miner/worker.go
- trie/triedb/pathdb/database.go
consensus/parlia: reject header with WithdrawalsHash before shanghai fork
WithdrawalsHash is not need by bsc, ensure it to be nil
* add owner of some TODO
* show flag `miner.delayleftover` in help doc and shadow flag `miner.newpayload-timeout`,
disable warn log about `newpayloadTimeout`, because it's useless for bsc
* change way of dumping chainConfig
* delete useless param `chainconfig` for VotePool and VoteManager
* fix TestOptionMaxPeersPerIP failure of goroutine order
keep consistent with go-ethereum, miss them when big merge:
* use `LoadChainConfig` to replace `SetupGenesisBlockWithOverride`, the later func has been called in `NewBlockChain`
* rename `Synchronise` to `LegacySync`
> parlia: reject header with `WithdrawalsHash` before shanghai fork

- CHANGELOG.md
- params/version.go
Release v1.3.0 is a big maintenance release for BSC mainnet and testnet.
It mainly did a very big code sync with upstream go-thereum[v1.10.16, v1.12.2] to import new features, bugfix, code clear up from go-ethereum.
Since there are huge code changes on this release, there could have some unknown risks or bugs there. It is not encouraged to run this version in your crucial business, but it would be appreciated if you can help try it in some non-crucial business environment and report bugs that you find.
There is a very long change list, including modules like: RPC, Flag, GraphQL, Client, Tracer, Command, Hardfork, P2P...
For detail pls refer: https://github.com/bnb-chain/bsc/pull/1840
NA
This is a big maintenance release, no hard fork. So the behavior of the release should be almost same …
> release: prepare for release v1.3.0

- cmd/geth/chaincmd.go
cmd/geth: fix listern port when initNetwork
otherwise, nodes may can't link to each other
* ...
> cmd/geth: fix listern port when initNetwork

- core/state/statedb.go
core/state: ensure triedb Commit after Update
if Commit first, and then Update, trie nodes may not write into disk correctly
and it lead to memory leak in archive mode
* ...
> core/state: ensure triedb Commit after Update

- cmd/geth/chaincmd.go
- cmd/geth/initnetwork_test.go
- cmd/geth/testdata/config.toml
- cmd/geth/testdata/parlia.json
This PR adds unit tests for the `init-network` command.
Additionally the command is modified a bit so that the datadir of a new node is configured before the node is created. This ensures that the empty `bsc.log` files get created in the node's folder instead of the current directory (which requires a manual cleanup step by the user later).
Only two tests are added not to burden the test suite. The two tests cover the two major scenarios: 1. when the nodes in the cluster are all in the same machine, and 2. when the nodes will run in different IPs.
* cmd/geth/chaincmd.go
* cmd/geth/initnetwork_test.go
> cmd: add tests for init-network

- core/rawdb/bloblevel/crud.go
- core/types/data_blob.go
- core/types/receipt.go
- eth/fetcher/block_fetcher.go
- eth/fetcher/sidecar_fetcher.go
- eth/handler.go
- eth/handler_eth.go
- eth/protocols/eth/protocol.go
- eth/sync.go
Fetcher for sidecars which is almost code complete with some todos to be dealt with later:
- Sanity checks for sidecars
- Need to check if the sidecars are actually getting stored. 
- Why multiple transactions are present in the block even though only one blob tx was sent?
This code change doesn't give any error for a peer when it receives a sidecar. But more extensive checks are needed as evident from the above todos.
> Sidecar Fetcher initial code implementation

- core/vm/contracts.go
There was a known EVM bug of Geth, refer:
https://github.com/ethereum/go-ethereum/security/advisories/GHSA-69v6-xc2j-r2jf
https://gist.github.com/karalabe/e1891c8a99fdc16c4e60d9713c35401f
https://github.com/ethereum/go-ethereum/pull/25183
BSC has not applied the fix yet, and tend to fix it with a hard fork release.
Just leave it there,could to be fixed in the future.
NA
NA
> fix: skip a patch that could fork the chain

- metrics/registry.go
metrics: fix missing miner-info, build-info and node-info
resupport type Label in metrics, so miner-info, build-info and node-info can be shown
* ...
> metrics: fix missing miner-info, build-info and node-info

- cmd/geth/dbcmd.go
- cmd/utils/flags.go
- core/rawdb/accessors_state.go
- core/rawdb/ancient_utils.go
- core/rawdb/database.go
- core/rawdb/freezer_table.go
- trie/hbss2pbss.go
When trieNode is converted from hbss to pbss format, the historical state data also needs to be modified accordingly, otherwise the following error will occur:
```
t=2023-10-07T11:11:19+0800 lvl=eror msg="WriteStateHistory failed" err="the append operation is out-order: have 443956 want 0"
```
This PR modifies the meta of the freezer table to avoid the above error, and enables continued writing of historical state after block chasing.
```
./geth db hbss-to-pbss --datadir ./node 5000
```
* Refactor the hbss2pbss tools
* Add state ancient repair function
> cmd/geth: fix error when writing state history after covert from hbss to pbss

- .golangci.yml
- core/state/statedb.go
- core/state/statedb_fuzz_test.go
core/state: skip handleDestruction in hash based mode
1. storage deletion is useless for hash based db, so skip it.
2. `TestStateChanges` fails now, but it is designed for path based only,
and is fixed in https://github.com/bnb-chain/bsc/pull/1909,
so disable it for now.
* ...
> core/state: skip handleDestruction in hash based mode

- core/state/statedb.go
core/state: skip deleting storages for EmptyTrie
trie is EmptyTrie for fast node,
iterate it will cause panic
* ...
> core/state: skip deleting storages for EmptyTrie

- core/txpool/txpool.go
core/txpool: ignore nil sub when subpool have been shut down
keep continue subscribing result of txs, 
when stop geth, report error as following
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1003ea414]
goroutine 25748 [running]:
github.com/ethereum/go-ethereum/event.JoinSubscriptions.func1.2({0x0?, 0x0?})
github.com/ethereum/go-ethereum/event/multisub.go:34 +0x34
created by github.com/ethereum/go-ethereum/event.JoinSubscriptions.func1
github.com/ethereum/go-ethereum/event/multisub.go:32 +0x8c
```
It's caused by nil subscription when subpool has been shut down.
* ...
> core/txpool: ignore nil sub when subpool have been shut down

- .golangci.yml
- core/blockchain.go
- core/rawdb/accessors_trie.go
- core/rawdb/freezer_table.go
- core/rawdb/schema.go
- core/state/statedb.go
- core/state/statedb_fuzz_test.go
- core/state/statedb_test.go
- eth/protocols/eth/handler.go
- trie/sync.go
- trie/sync_test.go
- trie/triedb/pathdb/difflayer.go
- trie/triedb/pathdb/disklayer.go
- trie/triedb/pathdb/errors.go
- trie/triedb/pathdb/journal.go
- trie/triedb/pathdb/nodebuffer.go
This PR cherry-pick go-ethereum(v1.13.2) commits that about PBSS, the commits list:
* [trie/triedb/pathdb: make shutdown journal log friendlier](https://github.com/ethereum/go-ethereum/pull/27905)
* [core/rawdb: allocate database keys with explicit size to avoid slice growth](https://github.com/ethereum/go-ethereum/pull/27772)
* [eth/protocols/eth: stop advertising eth/66 for pathdb nodes](https://github.com/ethereum/go-ethereum/pull/28006)
* [core/state: implement fast storage deletion](https://github.com/ethereum/go-ethereum/pull/27955)
* [core/state: check err for iter.Error in fastDeleteStorage ](https://github.com/ethereum/go-ethereum/pull/28122)
* [core/rawdb: no need to run truncateFile for readonly mode](https://github.com/ethereum/go-ethereum/pull/28145)
* [trie: remove internal …
> feat: cherry-pick pbss patch commits from eth repo in v1.13.2 

- consensus/parlia/parlia.go
- core/forkid/forkid.go
consensus/parlia: fix nextForkHash in Extra filed of block header
when sync from old client with debug level log, msg reported
```
t=2023-10-17T07:36:46+0000 lvl=dbug msg="Inserted new block"                     number=208,366    hash=0x6323bffbbfec7c4fbb7762313f5ee9c6d550469f3a83d5ae84170847d702930b uncles=0 txs=0   gas=0         elapsed="213.385µs" root=0xd323557cb3d7f3de97d3726f5ba0e8d84ddd1792d0bab7fe78ff6310c7cdb2ee
t=2023-10-17T07:36:46+0000 lvl=dbug msg="there is a possible fork, and your client is not the majority. Please check..." nextForkHash=3f2e9ae4
```
the reason is that after big merge, use `NewID` to replace of func `NextForkHash`
this patch revert this modification
PS:
the `nextForkHash` logic first added [here](https://github.com/bnb-chain/bsc/pull/53/files#diff-77f77794b4 …
> consensus/parlia: fix nextForkHash in Extra filed of block header

- CHANGELOG.md
- params/version.go
Release v1.3.1 is a maintenance release to support PBSS on BSC.
PBSS stands for: Path-Based-Storage-Scheme, which is used to optimize the MPT trie tree access, to improve its efficiency and also brings the inline state prune. You could refer this post on how it works: [Geth Path-Based Storage Model and Newly Inline State Prune](https://nodereal.io/blog/en/geth-path-based-storage-model-and-newly-inline-state-prune/)
Currently, PBSS is disabled by default, use this new flag to enable it: `--state.scheme path`
**Important**
Before use PBSS, you need to make sure your MPT storage in levelDB are already in PBSS format. There are 2 options to get the PBSS storage:
- 1.Full sync from genesis with the flag: `--state.scheme path`.  // Not recommend, could take 3 months to catch up the latest …
> release: prepare for release v1.3.1

- core/state/statedb.go
In `StateDB::Commit()`, run `commmitTrie()` concurrently to improve the performance.
Previous commitTrie was changed to be run serially for `--pipecommit`, but actually, it is ok to run it concurrently.
It was broken after v1.3.0 due to a object concurrent access safety, to reenable it
the safety was about: `StateDB.storages`
```
type StateDB struct {
...
storages       map[common.Hash]map[common.Hash][]byte 
...
}
```
it is used to store the modified KV pair for each address on updateTrie which is called during block validation phase, the key is with Keccak hashed.
> performance: commitTire concurrently during Commit

- core/state/database.go
- core/state/state_object.go
- core/state/statedb.go
- light/trie.go
accountTrieCache and storageTrieCache were introduced in this PR: https://github.com/bnb-chain/bsc/pull/257, which is to improve performance. Actually the performance gain is quite limitted, as there is already dirty and clean cache for trie node.
And after big merge, these 2 cache can not be used when PBSS is enabled. So remove these code to simplify the logic.
NA
NA
NA
> code: remove accountTrieCache and storageTrieCache

- internal/ethapi/api.go
Fix: eth_getTransactionDataAndReceipt
Fix: eth_getTransactionReceiptsByBlockNumber
eth_getTransactionReceiptsByBlockNumber API return wrong data
* internal/ethapi/api.
> Fix receipts

- core/txpool/txpool.go
This pr is a fix for issue https://github.com/bnb-chain/bsc/issues/1942, when shutdown txpool, it will return nil instance, this fix will ignore them.
* txpool: fix a potential crash issue in shutdown;
> txpool: fix a potential crash issue in shutdown;

- core/state/state_object.go
Recently, we saw some nodes spent lots of time on block validation phase, could even longer than 6 seconds, which leads to slash of some validators. We found out it is caused by some giant transactions, like XenCrypto. Take this transaction for example: https://bscscan.com/tx/0x5d948f50b9f1245fc4c9feaff71e02c607468d9540c33606253fa89998e9b7d8, which consumed ~40M gas in a single transaction. 
It is quite unfriendly to the current trie prefetch logic, which is terminated right after entering validation phase, since `getTrie()` will stop the trie prefetch.
This PR tries to keep trie prefetch until validation phase is completed, which will call `StopPrefetcher()` at the end of `StateIntermediateRoot()`.
For these long time validation phase, the validation time could be reduced by more than …
> performance: keep trie prefetch during validation phase

- CHANGELOG.md
- core/state/state_object.go
- internal/ethapi/api.go
- params/version.go
Release v1.2.13 is a maintenance release, which only contains 2 PRs, one for performance enhancement, the other one fixes 2 RPC APIs.
IMPROVEMENT
* [\#1954](https://github.com/bnb-chain/bsc/pull/1954) performance: keep trie prefetch during validation phase
BUGFIX
* [\#1950](https://github.com/bnb-chain/bsc/pull/1950) fix: 2 APIs of get receipt related(#1950)
NA
NA
> draft release v1.2.13

- eth/backend.go
- eth/handler.go
- trie/triedb/pathdb/database.go
- trie/triedb/pathdb/database_test.go
- trie/triedb/pathdb/difflayer_test.go
- trie/triedb/pathdb/disklayer.go
- trie/triedb/pathdb/history.go
* [eth, trie/triedb/pathdb: reallocate excess memory to clean cache #27964](https://github.com/ethereum/go-ethereum/pull/27964/commits), Adjust the cache size settings according to the configuration to use pathdb more reasonably.
* [trie/triedb/pathdb: improve dirty node flushing trigger #28426](https://github.com/ethereum/go-ethereum/pull/28426), added precautions for flushing nodebuffer to ensure the reliability of state data
N/A
N/A
N/A
> cherry pick pbss patches from go-ethereum

- trie/trie.go
revert trie committed flag after delete statedb trie cache #1949 
The following scenarios were tested:
N/A
N/A
N/A
> fix: revert trie committed flag after delete statedb trie cache

- cmd/geth/main.go
- cmd/geth/snapshot.go
- cmd/utils/flags.go
- core/blockchain.go
- core/blockchain_insert.go
- core/blockchain_test.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/handler.go
- eth/state_accessor.go
- eth/tracers/api.go
- trie/database.go
- trie/triedb/hashdb/database.go
- trie/triedb/pathdb/asyncnodebuffer.go
- trie/triedb/pathdb/database.go
- trie/triedb/pathdb/difflayer.go
- trie/triedb/pathdb/disklayer.go
- trie/triedb/pathdb/errors.go
- trie/triedb/pathdb/journal.go
- trie/triedb/pathdb/layertree.go
- trie/triedb/pathdb/nodebuffer.go
This PR fixes the stability and performance of PBSS, opt the  add asyncnodebuffer option for flushing disk(it non-block state commit), fix rewind root hash mismatch.
* [fix: use the top root hash for rewinding under path schema](https://github.com/bnb-chain/bsc/commit/cf15dff4f0ebab0490bdf0f096a2109aaf32982e), on restart uses the top difflayer root hash for rewinding under path schema
* [feat: add async flush nodebuffer in path schema](https://github.com/bnb-chain/bsc/commit/d8a631f4ac66d99818047d49c7565202d3db27b0), add async flush node buffer in path schema, reduce the negative impact of nodebuffer is flushed to disk on block generation.
`--pathdb.sync` use the origin nodebuffer, the defaulte use the asyncnodebuffer.
* trie/triedb/pathdb
* core
> eth, trie/triedb/pathdb: pbss patches

- consensus/parlia/parlia.go
- params/config.go
consensus/parlia: hardfork block can be epoch block
shanghai hardfork will be enabled based on block time instead of block number
but hardfork block can't be epoch block when enable luban
this patch find the reason , fix it and remove the warning in comments
so no fear of shanghai hardfork time run into epoch block
* ...
> consensus/parlia: hardfork block can be epoch block

- core/blockchain.go
internal/ethapi: fix null effectiveGasPrice in GetTransactionReceipt
cached receipt miss the `field` effectiveGasPrice, fix it
* ...
> internal/ethapi: fix null effectiveGasPrice in GetTransactionReceipt

- cmd/utils/flags.go
Fix the node unable to start issue if `--pruneancient=true` by creating a non-read-only database. 
Refer to #1984 and #1982.
When initializing a readonly database, it will attempt to open a freezer file for read only (refer to code [here](https://github.com/bnb-chain/bsc/blob/v1.3.1-beta/core/rawdb/freezer_table.go#L147-L164)). Since ancient files are pruned and no longer exist, the read file operation will fail and return error. 
Refer to #1984 and #1982.
Create a non-read-only database if `--pruneancient=true`.
> fix: v1.3.1-beta cannot start with `--pruneancient=true`

- .github/workflows/unit-test.yml
- consensus/misc/eip1559/eip1559.go
- consensus/misc/eip1559/eip1559_test.go
- core/genesis.go
- core/vm/jump_table.go
- eth/filters/filter_test.go
- params/config.go
- tests/block_test.go
- tests/init_test.go
- tests/state_test.go
- tests/state_test_util.go
- trie/triedb/pathdb/database.go
core: enable Shanghai EIPs
more compatible with ethereum/evm, 6 points need to check
1. [BEP-216: Implement EIP 3855 PUSH0 instruction](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP216.md#bep-216-implement-eip-3855-push0-instruction)
2. [BEP-217: Implement EIP3860 Limit and meter initcode](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP217.md#bep-217-implement-eip3860-limit-and-meter-initcode)
3. [BEP-311: Implement EIP-3651 Warm COINBASE](https://github.com/bnb-chain/BEPs/pull/311)
4. [BEP-312: Announce EIP-6049 Deprecate SELFDESTRUCT](https://github.com/bnb-chain/BEPs/pull/312)
5. disable [EIP-4895](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4895.md) after code upstream
6. use time based hardfork
1. to disable EIP-4895, need confirm 3 points:
a. …
> core: enable Shanghai EIPs

- README.md
- cmd/utils/flags.go
- log/root.go
- tests/truffle/scripts/bsc-rpc.sh
- tests/truffle/scripts/bsc-validator.sh
Crash node and exit process if `--txlookuplimit` flag is set instead of `history.transactions`.
If users still use `--txlookuplimit` which is deprecated instead of `history.transactions`, then it maintains the default number of blocks to maintain the transaction index for. This may cause the node to unindex transactions, which would affect the performance.
Refer to #1999 for more details.
N/A
- Wait 3 seconds before `os.Exit(1)`, this ensures the log message is printed before exiting.
> cmd/utils: exit process if txlookuplimit flag is set

- consensus/parlia/parlia.go
consensus/parlia: increase size of snapshot cache in parlia
when distribute rewards for fast finality,
need to get snapshot for blocks in [currentNumber-200,currentNumber) 
but the size of `recentSnaps` is only 128, so many snapshots need to be inferred in place,
to get better performance, double 128 to 256
* ...
> consensus/parlia: increase size of snapshot cache in parlia

- consensus/parlia/parlia.go
- consensus/parlia/snapshot.go
consensus/parlia: recover faster when snapshot of parlia is gone in disk
snapshots of parlia will be stored into disk every 1024 blocks.
if they are missing, just create a new one before reaching `FullImmutabilityThreshold`
for bsc, 15 blocks is usually view as the probabilistic fanlity number. 
FullImmutabilityThreshold is 90000, too large,
so only in this case , we decrease ti by 10 times to 9000
* ...
>  consensus/parlia: recover faster when snapshot of parlia is gone in disk

- cmd/geth/blsaccountcmd.go
This pr is to add cmd `generate-proof` to geth.
After feynman upgrade, anyone who wants to create a validator should provide a bls proof of his vote address. This cmd is to facilitate that.
* add cmd `generate-proof` to geth
> feat: add `generate-proof` to geth cmd

- cmd/geth/blsaccountcmd.go
- cmd/geth/testdata/bls-account-usage-demo.sh
- cmd/utils/flags.go
- params/config.go
cmd/geth: standardize the action of importing bls account
there are 3 issues when using `geth bls account`
1.  no trim '\r\n' when read password from file.
when use vim or `echo` command to write password into a file, a '\r' or '\n' will be added automaticly
this PR will do the trim by following `geth account`
2. some related flags have not set field `Category`, so they will not be displayed in help info
this PR fix it
3. putting a bls private key into wallet viewed as a `new` action
only putting a keystore file into wallet will be viewed as a `import` action
but `geth account` can  put a private key into wallet by a `import` action
and others, in metamask, the import action both accept a file including a private key or a keystore file
so in this PR, putting a bls private key into wallet …
> cmd/geth: standardize the action of importing bls account

- CHANGELOG.md
- params/config.go
- params/version.go
Release v1.3.5 is a hard fork release for BSC.
It will enable the Kepler(Shanghai) hard fork on BSC testnet, for details of the hard fork, pls refer: [BSC Kepler Hard Fork](https://forum.bnbchain.org/t/bnb-chain-upgrades-mainnet/936#kepler-in-progress-10)
The target Kepler/Shanghai hardfork time will be:
- Testnet: Tuesday, December 19, 2023 8:00:00 AM UTC
- Mainnet: Tuesday, January 23, 2024 8:00:00 AM UTC
The validators and full node operators on Testnet/Mainnet should update their node to v1.3.5 before the respective hard fork time.
- [BEP-319: Optimize the incentive mechanism of the Fast Finality feature](https://github.com/bnb-chain/BEPs/pull/319)
- Part of Shanghai Upgrade: 
a.[BEP-216: Implement EIP-3855 PUSH0 instruction](https://github.com/bnb-chain/BEPs/pull/216)
b.[BEP-217: …
> release: prepare for release v1.3.5

- core/txpool/legacypool/legacypool.go
core/txpool/legacypool: respect nolocals-setting
details to https://github.com/ethereum/go-ethereum/pull/28435
* ...
> core/txpool/legacypool: respect nolocals-setting

- cmd/jsutils/README.md
- cmd/jsutils/gettxcount.js
- cmd/jsutils/getvalidatorversion.js
- cmd/jsutils/package.json
> cmd/jsutils: add 2 tools get validator version and block txs number

- consensus/parlia/feynmanfork.go
- consensus/parlia/parlia.go
- core/vm/contracts.go
This pr is to update logic of determining breathe block and returned data of `verifyDoubleSignEvidence`
* update logic of determining breathe block
* `verifyDoubleSignEvidence` will return block.number rather than block.timestamp now
> chore: update logic of determining breathe block and returned data of `verifyDoubleSignEvidence`

- core/vote/vote_manager.go
- core/vote/vote_pool_test.go
core/vote: wait some blocks beforing voting since mining begin
many validators have backup machines
when they shutdown their running node and start the validator on the backup machine,
the new started node may vote for blocks in the same height with the down node voted for.
so, this PR let node wait some blocks beforing voting since it's mining begin
* ...
> core/vote: wait some blocks beforing voting since mining begin

- core/genesis.go
- core/genesis_test.go
- params/config.go
Set default hardfork times 
hardfork transit to time based from shanghai
we should set default values for time based hardforks as we have done for block based hardforks.
* ...
> Set default hardfork times

- log/async_file_writer.go
- log/async_file_writer_test.go
- log/handler.go
- log/logger.go
- node/config.go
- node/node.go
log: support to disable log rotate by hours
https://github.com/bnb-chain/bsc/issues/114 suggest that
```
So would be nice to add an option into the config file to:
1. rotate by size
2. rotate by date (daily, hourly, weekly, monthly, etc)
3. disable rotation altogether
```
to support type 1, only rotate by size, 
we should have the ablitiy to disable the default one hour rotation, this PR add this support
by setting `RotateHours=0` in config.toml, rotate by hours is disabled 
* ...
> log: support to disable log rotate by hours

- node/node.go
log: limit rotateHours in range [0,23]
if rotateHours ==24, log engine will continue to recreate files every second
* ...
> log: limit rotateHours in range [0,23]

- cmd/utils/flags.go
Fixes #2052.
When users specify the `http.addr` and `ws.addr` command line flags, they will overwrite the HTTPHost and WSHost in the config file.
As a user, I would assume that specifying flags would overwrite the config files. While this is true for most flags, the behavior is the opposite for `http.addr` and `ws.addr`.
config.toml
```
[Node]
HTTPHost = "127.0.0.1"
WSHost = "127.0.0.1"
```
Command:
```
./geth --datadir node --mainnet --http --http.addr 0.0.0.0 --ws --ws.addr 0.0.0.0
```
Expected output:
```bash
...
INFO [12-12|14:17:21.325] HTTP server started                      endpoint=[::]:8545 auth=false prefix= cors= vhosts=localhost
INFO [12-12|14:17:21.326] WebSocket enabled                        url=ws://[::]:8546
...
```
Actual output:
```bash
...
INFO [12-12|14:16:47.073] …
```
> cmd/utils: allow HTTPHost and WSHost flags precede

- CHANGELOG.md
- params/version.go
**Important:**
Pls replace v1.3.5 with v1.3.6 for Kepler hard fork, otherwise your node will need to setup the Kepler hard fork timestamp in config.toml, which is inconvenient and not recommended.
Release v1.3.6 is a maintenance release, it mainly solved the default Kepler hard fork timestamp issue(https://github.com/bnb-chain/bsc/pull/2058).
Beside this important fix up, there are several other improvement, such as:
- support to disable log rotate by hours
- enable Pebble on 32 bits and OpenBSD
- change default network to BSC
- provide 2 JS tools for simple chain status analyze
- delay FastFinality vote on node start up, to avoid voting again the rule when node switch.
-  allow HTTPHost and WSHost flags precede
FEATURE
* [\#2012](https://github.com/bnb-chain/bsc/pull/2012) cmd, core, …
> release: prepare for release v1.3.6

- ethdb/pebble/pebble.go
Although pebble is initialized to level 7 by default, the configuration of level options does not take effect because the level option slices has no explicit initialization.
The option file content of the chain db  is as follows after fixed which  meet expected option (block size is 32kB, indexBlock size is 256KB , and enable bloom filter) :
```
[root@tf_nodereal_dev_bsc_new_feature_testing1_ec2 chaindata]# tail -40  OPTIONS-000013 
[Level "3"]
block_restart_interval=16
block_size=32768
block_size_threshold=90
compression=Snappy
filter_policy=rocksdb.BuiltinBloomFilter
filter_type=table
index_block_size=262144
target_file_size=16777216
[Level "4"]
block_restart_interval=16
block_size=32768
block_size_threshold=90
compression=Snappy
filter_policy=rocksdb.BuiltinBloomFilter …
```
> fix: fix the pebble config of level option

- cmd/geth/config.go
- cmd/utils/flags.go
- cmd/utils/flags_test.go
Provide explicit for which state scheme geth can use to start or init. And add check function to validate provided state scheme.
Users may add `StateScheme = "path"` in `config.toml` and want to start geth without persistent state in disk, but geth is started in `hash` mode. For solving these cases, add a function, obey the following rules:
1. If config isn't provided, write hash mode to config by default, so in current function, config is nonempty.
2. If persistent state and cli is empty, use config param.
3. If persistent state is empty, provide CLI flag and config, choose CLI to return.
4. If persistent state is nonempty and CLI isn't provided, persistent state should be equal to config.
5. If all three items are provided: if any two of the three are not equal, return error.
1. `nohup …
> cmd/geth: add check func to validate state scheme

- cmd/geth/config.go
- consensus/parlia/parlia.go
- core/genesis.go
- core/genesis_test.go
- core/systemcontracts/upgrade.go
- params/config.go
core: LoadChainConfig return the predefined config for built-in networks firstly
1. for the built-in networks, the predefined config is the standard
and they should not be configured in the `config.toml`
so return the predefined config
2. furtherly, for local test or private network, can use [`geth init`](https://geth.ethereum.org/docs/fundamentals/private-network) to upgrade the chain config,
so we just _**stop supporting read chain config from the `config.toml`.**_
by doing this, logic about chain config can be simplified.
* ...
> core: LoadChainConfig return the predefined config for built-in networks firstly

- CHANGELOG.md
- params/version.go
**Important:**
For Kepler hard fork, pls use v1.3.7.
Release v1.3.7 is another maintenance release, it mainly fixes an important ChainConfig issue and also provides the new RPC API: `eth_getBlockReceipts`, which was supported on Ethereum since Sep 2023.
For detail, pls refer the following change log.
FEATURE
* [\#2067](https://github.com/bnb-chain/bsc/pull/2067) cmd/geth: add check func to validate state scheme
* [\#2068](https://github.com/bnb-chain/bsc/pull/2068) internal/ethapi: implement eth_getBlockReceipts
BUGFIX
* [\#2035](https://github.com/bnb-chain/bsc/pull/2035) all: pull snap sync PRs from upstream v1.13.5
* [\#2072](https://github.com/bnb-chain/bsc/pull/2072) fix: fix the pebble config of level option
* [\#2078](https://github.com/bnb-chain/bsc/pull/2078) core: …
> release: prepare for release v1.3.7

- metrics/timer.go
- rpc/metrics.go
The rpc/duration/all meter was in nanoseconds, the individual meter in microseconds. This PR changes it so both of them use nanoseconds.
After Fix
* metrics/timer.go
* rpc/metrics.go
> rpc: fix ns/µs mismatch in metrics (#28649)

- core/genesis.go
- params/config.go
params/config: remove useless toml tag for hardforks
these tag is used to dump Genesis.ChainConfig into config.toml
because we stop reading ChainConfig from config.toml now, these tags become useless
* ...
> params/config: remove useless toml tag for hardforks

- consensus/parlia/parlia.go
This pr is to add check to avoid update validators on Feynman block
Updating validators on Feynman block will cause the chain down
* add check to avoid update validators on Feynman block
> fix: avoid update validators on Feynman block

- cmd/faucet/README.md
- cmd/faucet/faucet.go
In this update to the faucet client, the default functionality of the faucet binary has been altered. Previously, the faucet binary utilized the Light Ethereum Subprotocol (LES) for connecting to the BSC network. However, this update changes this behavior, making the faucet connect to an already running BSC node via WebSocket (WS) protocol. This modification is aimed to support faucet after LES deprecation. 
The motivation behind these changes includes:
- **Resource Efficiency**: By connecting to an existing node, we reduce the resource load on the system running the faucet, as it no longer needs to maintain a full LES client.
- **Enhanced Flexibility**: This approach allows for greater flexibility in network setups, as the faucet can connect to any accessible node on the network, not …
> new faucet client

- eth/ethconfig/gen_config.go
- trie/triedb/pathdb/asyncnodebuffer.go
- trie/triedb/pathdb/disklayer.go
- trie/triedb/pathdb/journal.go
- trie/triedb/pathdb/nodebuffer.go
When running `TestJournal` UT in `trie/triedb/pathdb`, there is a certain probability that this error will occur: `Invalid state, err: state 0xdda0214f6c0c6ea546cdbf3db74a31f8337a01b41908b3b8ea27a8fde0011294 is not available`. 
The reason of this error is that the journal loaded from disk is wrong, the error message of `loadJournal` function: `unmatched journal want c3bd21026750db0009399463f5947e1663c7057cb4aaabeb0b39ed68dedd4d0b got 6d574af1033459ae676316a1262a5d89edb7bbd515ecd253b4319a3161093153`.
When geth calls `Journal` function to commit entire diff hierarchy to disk into a single journal entry, the flush process of `asyncnodebuffer` maybe doesn't end, so we should stop, wait it and journal.
N/A
* N/A
> triedb/pathdb: fix async node buffer diskroot mismatches when journaling

- cmd/geth/dbcmd.go
- trie/inspect_trie.go
add inspect trie tool to analysis the trie tree more convenient.
TODO:
https://github.com/bnb-chain/bsc/issues/1305
```
./geth db inspect-trie --datadir server/data-seed/ latest 4000
```
* add inspect_trie impl
> cmd/dbcmd: add inspect trie tool

- ethdb/pebble/pebble.go
If mem table size  exceeds 4G, the memtable will be set to 4G in bsc code .  But Pebble has not handled this boundary well , it require less than 4G but not equal 4G . (https://github.com/cockroachdb/pebble/pull/3008)
solve issue(https://github.com/bnb-chain/bsc/issues/2091)
* ...
> fix:  fix pebble mem table size boundary error

- consensus/consensus.go
- consensus/parlia/parlia.go
- core/blockchain.go
- core/blockchain_reader.go
- core/headerchain.go
- core/vote/vote_manager.go
- core/vote/vote_pool_test.go
- light/lightchain.go
parlia: fix verifyVoteAttestation when verify a batch of headers
when full sync with other peers, it normally import a batch blocks in one time, so `VerifyHeaders` will be called.
suppose that there are N headers in headers: [header0,header1....hearderN-1],
when we do `verifyVoteAttestation` for headerM, 
headerM-1 is just verified and not written into db, so fail to get headerM-1
output errlog as following
[error detail](https://github.com/bnb-chain/bsc/issues/2119)
affect range:
1. validator not affected
2. few happens even when do a fullsync
and even it happens, the node will just drop the current peer and continue to sync with other peers.
so no emergency
* ...
> parlia: fix verifyVoteAttestation when verify a batch of headers

- core/blockchain.go
- core/genesis.go
core: fix systemcontracts.GenesisHash when run bsc firstly without init
after https://github.com/bnb-chain/bsc/pull/2015 and https://github.com/bnb-chain/bsc/pull/2100
bsc mainnet and chapel can run without `geth init`
but may lead a empty genesis hash when first startup, this PR is to fix it
* ...
> core: fix systemcontracts.GenesisHash when run bsc firstly without init

- eth/fetcher/tx_fetcher.go
- eth/fetcher/tx_fetcher_test.go
This PR cherrypicks a PR from the Geth upstream. The original description is as follows:
"This PR will allow a previously underpriced transaction back in after a timeout of 5 minutes. This will block most transaction spam but allow for transactions to be re-broadcasted on networks with less transaction flow."
Resolves #2084
We have some users saying that underpriced transactions were not able to be broadcast at all. This code change should help resolve that.
Special thanks to @terianil for sharing the info 😊
> eth/fetcher: allow underpriced transactions in after timeout (#28097)

- eth/downloader/queue.go
- p2p/discover/v4_udp.go
This PR improves user experience by modifying logs output, mainly on:
1. Do not show `Current status` for regular nodes, only used for bootnodes
2. Change log level for `Expired request does not exist` from `Error` to `Trace`
For the 1st log change, `Current status` log is meant for bootnodes to monitor the discovery status. For regular nodes, the information is not useful.
For the 2nd log change, when `*queue.Revoke()` and `*queue.expire()` happen concurrently, the resulting pending pool will no longer contain the peer request. Hence, `Expired request does not exist` will be shown. It's not a useful log for an average user, so its log level can be changed to `Trace`.
> p2p, eth: improve logs

- p2p/metrics.go
- p2p/server.go
This PR adds P2P serve metrics.
It'll be useful to understand why certain serve operations fail.
Some charts:
> p2p: add serve metrics

- p2p/server.go
This PR adds a feature to stop reconnecting to peers that were explicitly disconnected (i.e. using `admin_removePeer`).
In some cases when we run a cluster of nodes, we would want to avoid those nodes connecting to the same peers. Hence, we would do `admin_removePeer`) to disconnect the connections. However, the reality is that peers get reconnected almost immediately after executing `admin_removePeer`, as shown in the graph below:
Hence, this feature will put a restriction on the explicitly removed peers such that their connections are not accepted unless the node is restarted.
* add `disconnectEnodeSet` in the `Server` struct
* add new condition check in `Server.addPeerChecks`
> p2p: no peer reconnect if explicitly disconnected

- .github/workflows/evm-tests.yml
- consensus/misc/eip1559/eip1559.go
- core/chain_makers.go
- miner/worker.go
- tests/0001-diff-go-ethereum.patch
- tests/block_test.go
- tests/block_test_util.go
- tests/run-evm-tests.sh
- tests/state_test.go
tests: revive evm test cases
there are a ton of [evm test cases](https://github.com/ethereum/tests) maintained by ethereum office, but It's not run by bsc.
this PR is to revive these test cases and add them as a CI,
this will help a lot for quaility assurance.
PS: in block_test.go and state_test.go, the test scope is not less in go-thereum.
* ...
> tests: revive evm test cases

- core/vm/contracts.go
This pr is to fix an issue in `verifyDoubleSignEvidence`
* compare headers' number in Big.Int rather than Uint64
> fix: compare headers' number in Big.Int rather than Uint64

- p2p/server.go
Resolves #2149
Previously, when `NoDial` is set to true, then the maximum dial peers is always going to be 0. Hence, the node is never going to dial static nodes.
With this code change, when `NoDial` is set to true, the maximum dial peers will be set to the number of static peers. With this, the dial scheduler knows that there are available slots to dial the static peers.
One concern regarding this design is that, if the node doesn't dial the static nodes successfully, will it then dial the other peers, since there are available dial slots?
Fortunately, the answer is no. Based on the code [here](https://github.com/bnb-chain/bsc/blob/master/p2p/dial.go#L405-L414), it's guaranteed to return the number of static nodes. Therefore, there will be [no available …
> feat: enable NoDial should still dial static nodes

- miner/worker.go
- params/protocol_params.go
In mine phase, it is useless to check the passed hard fork, remove it could simplify the code.
Keep other hard fork checks in mine phase, like `IsLondon`, `IsEIP155`, as they are more complicated and could be used in some test environment.
To simplify the code.
NA
NA
> code: remove IsEuler check from worker.go

- core/blockchain.go
- miner/worker.go
SharedPool was introduced since [v1.1.9](https://github.com/bnb-chain/bsc/releases/tag/v1.1.9), but it has a potential bug and is no longer supported since [hertzFix](https://forum.bnbchain.org/t/about-the-hertzfix/2400).
This PR is to remove the sharedPool code in miner module, which was introduced in this PR https://github.com/bnb-chain/bsc/pull/818 and is useless now.
It has no impact to the current logic, but just code improve
NA
NA
NA
> improve: remove sharedpool from miner

- trie/inspect_trie.go
Refactor inspect trie cmd and add more output information
NA
NA
* refactor concurrency control 
* add eoa account statistics
> dbcmd: refactor concurrency Control and add EOA/Contract account stat

- core/state/pruner/pruner.go
Don't need to run `prune-block` if specified reserve blocks are the same to items in ancientdb
> core/state: no need to prune block if the same 

- p2p/server.go
Related to #2140.
This PR adds a small feature to reset the disconnect enode set by removing a peer (i.e. via `admin_removePeer`) using a hardcoded enode ID.
Previously, the only way to reset the disconnect enode set was to restart the node. This may not be very inconvenient. Hence, we need a mechanism to reset the set without restarting the node.
By sending a hardcoded "magic" enode ID as a parameter to `admin_removePeer`, the set will be reset. The hardcoded "magic" enode ID is referenced from the test cases.
> p2p: reset disconnect set with magic enode ID

- CHANGELOG.md
- params/version.go
Release v1.3.8 is a maintenance release with several enhancements, here is the summary of these updates that may interest the BSC users:
- Golang to v1.21 will be needed to compile
- a new tool to inspect the trie storage
- some improvements on P2P module
- some fix ups of RPC, PBSS, PebbleDB, consensus
- improve UX, sync with BSC mainnet by default, no need to init genesis block any more
- LES protocol has been removed, since light node can not work right now.
- increase the SystemTxsGas reservation from 1,500,000 to 5,000,000
FEATURE
* [\#2074](https://github.com/bnb-chain/bsc/pull/2074) faucet: new faucet client
* [\#2082](https://github.com/bnb-chain/bsc/pull/2082) cmd/dbcmd: add inspect trie tool
* [\#2140](https://github.com/bnb-chain/bsc/pull/2140) eth/fetcher: allow underpriced …
> release: prepare for release v1.3.8

- consensus/parlia/parlia.go
consensus/parlia: set nonce before evm run
It's strange to set nonce after execute tx, so align with it in TransitionDb
no need to use hardfork to control, there are 3 reasons:
```
1. The GetNonce function will not be invoked during the execution process of the virtual machine, so placing it before or after the call execution has no impact.
2. Modifications to the state occur on a per-block basis, so placing them after Finalise also does not affect the overall result of block execution.
3. The journal is used for rollback purposes; transactions in Parlia will not revert, so the impact can be ignored.
```
* ...
> consensus/parlia: set nonce before evm run

- core/txpool/legacypool/legacypool.go
This PR deprecates the usage of `ErrAlreadyKnown` in the `legacypool` package. Existing dependencies on this error type should use `txpool.ErrAlreadyKnown` instead.
Originally, upon triggering `legacypool.ErrAlreadyKnown`, this error will be propagated back to the initial caller functions.
For example, in [this code](https://github.com/bnb-chain/bsc/blob/master/eth/fetcher/tx_fetcher.go#L323), the expected behavior is that the metrics will be bumped if `txpool.ErrAlreadyKnown` function is used. However, `legacypool.ErrAlreadyKnown` and `txpool.ErrAlreadyKnown` are 2 different error types with the same error messages. Hence, the case of checking if the error is of `txpool.ErrAlreadyKnown` will not be triggered so it will go to the default case instead.
> txpool/legacypool: deprecate already known error

- log/async_file_writer.go
- log/async_file_writer_test.go
- log/handler.go
- log/logger.go
- node/config.go
- node/node.go
Add maxBackups in config.toml.  
MaxBackups means the log file that would be retained, by default it would be 0, which means there is no limitation.
If set MaxBackups = 240, only logs of the most recent 240 hours(10 days) would be kept, since the default rotate time is 1 hour.
See more: #2165.
Add a MaxBackups in Node.LogConfig. 
```
[Node.LogConfig]
FileRoot = ""
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
```
```
[Node.LogConfig]
FileRoot = ""
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
MaxBackups = 240
```
* log: add maxBackups in config.toml
> log: support maxBackups in config.toml

- eth/fetcher/tx_fetcher.go
This PR downgrades the `Peer delivering stale transactions` from `warn` to `debug`.
This log frequently appears in the node logs, but users can't do anything about it, so it's best to downgrade it and use it for debug purposes only.
> eth/fetcher: downgrade state tx log

- core/vm/contracts.go
- core/vm/contracts_lightclient.go
- params/protocol_params.go
This PR fix three things:
1. The wrong precompile contracts for Feyman upgrade;
2. Adjust the gas for doubleSignVerfify precompile contract;
3. Change the name of some const.
Fix the review comment.
None
None
> fix: change the wrong precompile contract

- cmd/geth/blsaccountcmd.go
- consensus/parlia/parlia.go
This pr is to update the bls generate-proof cmd
* update bls generate-proof cmd
> chore: update bls generate-proof cmd

- .github/workflows/nancy.yml
ci: add nancy job
integrate static analysis tools that can detect outdated and vulnerable libraries
Run locally
```bash
go list -json -deps ./... | nancy sleuth
```
* ci
> ci: add nancy job

- CHANGELOG.md
- params/version.go
Release v1.3.9 is a moderate maintenance release with some enhancements and one feature of how to keep the log, check out the change list bellow. 
FEATURE
* [\#2186](https://github.com/bnb-chain/bsc/pull/2186) log: support maxBackups in config.toml
BUGFIX
* [\#2160](https://github.com/bnb-chain/bsc/pull/2160) cmd: fix dump cli cannot work in path mode
* [\#2183](https://github.com/bnb-chain/bsc/pull/2183) p2p: resolved deadlock on p2p server shutdown
IMPROVEMENT
* [\#2177](https://github.com/bnb-chain/bsc/pull/0000) build(deps): bump github.com/quic-go/quic-go from 0.39.3 to 0.39.4
* [\#2185](https://github.com/bnb-chain/bsc/pull/2185) consensus/parlia: set nonce before evm run
* [\#2190](https://github.com/bnb-chain/bsc/pull/2190) fix(legacypool): deprecate already known error
* …
> release: prepare for release v1.3.9

- cmd/utils/flags.go
- cmd/utils/flags_test.go
- core/rawdb/accessors_trie.go
Optimize parse state scheme in cli and config.
Remove extra parsing `StateScheme` config param in some functions.
N/A
* N/A
> cmd: optimize parse state scheme in cli and config

- core/types/block.go
- core/types/block_test.go
- core/types/gen_header_json.go
- core/types/gen_header_rlp.go
types: fix header nil withdraw decode bug;
When `BlobGasUsed` is set but `WithdrawalsHash` is left nil, the error occurs `rlp:' is reported in deserialization. input string too short for common.Hash, decoding into (types.Header).WithdrawalsHash`.
Everything was fine after repair.
* types: fix header nil withdraw decode bug;
> types: fix header nil withdraw decode bug;

- CHANGELOG.md
- params/version.go
Release v1.3.10 is hard fork release for **BSC Chapel Testnet**, the HF name is: Feynman, it includes these 2 BEPs:
https://github.com/bnb-chain/BEPs/pull/294: BSC Native Staking after BC Fusion
https://github.com/bnb-chain/BEPs/pull/299: Token Migration after BC Fusion
The target Feynman hard fork time will be:
- Testnet: Monday, 2024-03-11 6:00:00 AM UTC
- Mainnet: To be determined, could be around  Mid of Apr 2024
Feynman hard fork is for BC(Beacon Chain) Fusion, which is critical upgrade for BNB Chain, for more about BC-Fusion, pls may refer:
https://www.bnbchain.org/en/bnb-chain-fusion
https://www.bnbchain.org/en/blog/bnb-chain-fusion-roadmap
It only includes 1 PR, which mainly upgrade some critical system contracts and also the Parlia consensus engine.
FEATURE
* …
> release: prepare for release v1.3.10

- eth/gasprice/feehistory.go
fix percentile validation in eth_feeHistory
the same bug fixed in go-ethereum: https://github.com/ethereum/go-ethereum/pull/28954/files
* ...
> eth/gasprice: fix percentile validation in eth_feeHistory

- cmd/geth/blsaccountcmd.go
This pr is to add a missing arg of `bls account generate-proof` cmd
* add missing arg of `bls account generate-proof` cmd
> fix: add missing arg of `bls account generate-proof` cmd

- core/blockchain.go
fast node doesn't have a state merkle trie
and when do inited snap sync,  `Snapshot maintenance disabled`
so `if !bc.HasState(root)` always return true
To solve this ,skip checking state root existence when do snapsync by fast node 
* ...
> core: skip checking state root existence when do snapsync by fast node

- cmd/geth/consolecmd_test.go
- common/bidutil/bidutil.go
- consensus/beacon/consensus.go
- consensus/clique/clique.go
- consensus/consensus.go
- consensus/ethash/consensus.go
- consensus/parlia/parlia.go
- consensus/parlia/snapshot.go
- core/types/bid.go
- core/types/bid_error.go
- eth/api_admin.go
- eth/api_backend.go
- ethclient/ethclient.go
- go.mod
- go.sum
- internal/ethapi/api_mev.go
- internal/ethapi/api_test.go
- internal/ethapi/backend.go
- internal/ethapi/transaction_args_test.go
- miner/bid_simulator.go
- miner/builderclient/builderclient.go
- miner/miner.go
- miner/miner_mev.go
- miner/worker.go
* core/types:  define Bid and related error message
* internal/eth_api: add MevAPI to receive bids from builder
* eth/api_admin: add API to support start and stop mev dynamically
* miner: add bidSimulator to maintain bid simulation and fetch best bid from
* consensus: add func to query the next inturn validator
* ethclient: add clients for MevAPI
https://github.com/bnb-chain/BEPs/pull/322#5-references
* ...
> feat: support MEV

- consensus/parlia/parlia.go
- core/chain_makers.go
- core/genesis.go
- core/state_processor_test.go
- miner/worker.go
fix: ensure EIP-4788 not supported with Parlia Engine
* ...
> fix: ensure EIP-4788 not supported with Parlia Engine

- cmd/geth/blsaccountcmd.go
- core/blockchain.go
fast node doesn't have a state merkle trie
and when do inited snap sync,  `Snapshot maintenance disabled`
so `if !bc.HasState(root)` always return true
To solve this ,skip checking state root existence when do snapsync by fast node 
* ...
> core: skip checking state root existence when do snapsync by fast node 

- CHANGELOG.md
- params/version.go
Release v1.4.1-alpha is a maintenance release, which only applies 2 fixes based on v1.4.0-alpha.
NA
NA
NA
* [\#2258](https://github.com/bnb-chain/bsc/pull/2258) core: skip checking state root existence when do snapsync by fast node
* [\#2252](https://github.com/bnb-chain/bsc/pull/2252) fix: add missing args of `bls account generate-proof` cmd (#2252)
NA
> draft release v1.4.1-alpha

- CHANGELOG.md
- params/version.go
Release v1.4.2-alpha is another maintenance release.
It mainly include three parts:
- 1.Second round of Cancun code sync with upstream go-thereum[v1.13.12, v1.13.14] to include some fix and improvements of EIP-4844.  https://github.com/bnb-chain/bsc/pull/2267
- 2.feat: support separate trie database. https://github.com/bnb-chain/bsc/pull/2021
- 3.feat: support MEV. https://github.com/bnb-chain/bsc/pull/2224
Same as previous v1.4.0-alpha, it could have some unknown risks or bugs there. It is not encouraged to run this version in your crucial business, but it would be appreciated if you can help try it in some non-crucial business environment and report bugs that you find.
Feature
* [\#2021](https://github.com/bnb-chain/bsc/pull/2021) feat: support separate trie database
* …
> release: prepare for release v1.4.2-alpha

- consensus/parlia/parlia.go
fix failed check for WithdrawalsHash
* ...
>  fix failed check for WithdrawalsHash

- core/state_processor.go
Make it part of the consensus rule that systemTx should be always at the end of block.
Currently, validator already put systemTx at the end of the block, this PR just add extra check on block import.
NA
NA
NA
> fix: systemTx should be always at the end of block

- core/types/tx_blob.go
- eth/api_backend.go
- ethclient/ethclient.go
- internal/ethapi/api.go
- internal/ethapi/api_test.go
- internal/ethapi/backend.go
- internal/ethapi/transaction_args_test.go
- internal/web3ext/web3ext.go
Implemet two method eth_getBlobSidecars && eth_getBlobSidecarByTxHash
support get BlobSidecars
* ...
> Implement eth_getBlobSidecars && eth_getBlobSidecarByTxHash

- core/state/statedb.go
Replaces `tastResult` with `taskResult`.
> core/state: fix taskResult typo

- core/blockchain.go
- internal/ethapi/api_test.go
Sidecars could be large, reduce the cache size to avoid too much memory usage.
NA
NA
NA
> config: reduce sidecar cache to 1024 and rename

- core/block_validator.go
> fix: Withdrawals turn into empty from nil when BlockBody has Sidecars

- CHANGELOG.md
- params/version.go
The current version number is not correct.
Update the patch version number to 12.
None
None
> fix: fix the wrong version number

- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- core/genesis.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
1. remove overridekepler and overrideshanghai , they are enabled on mainnet now
2. fix OverrideFeynman and OverrideFeynmanFix in gen_config.go
* ...
> eth/ethconfig: remove overridekepler and overrideshanghai

- Makefile
- cmd/utils/flags.go
- core/blockchain.go
- core/rawdb/accessors_trie.go
- graphql/graphql_test.go
- triedb/database.go
- triedb/pathdb/asyncnodebuffer.go
- triedb/pathdb/database.go
This PR flips the default state-scheme from hash to path, though it also adds a fallback for archive mode which force sets hash mode.
N/A
N/A
* N/A
> cmd/utils, core/rawdb, triedb/pathdb: flip hash to path scheme

- cmd/devp2p/internal/ethtest/suite.go
- cmd/evm/internal/t8ntool/execution.go
- common/types.go
- common/types_test.go
- consensus/misc/eip4844/eip4844.go
- consensus/misc/eip4844/eip4844_test.go
- core/blockchain.go
- core/chain_makers.go
- core/evm.go
- core/rawdb/accessors_chain.go
- core/txpool/blobpool/blobpool.go
- core/txpool/blobpool/blobpool_test.go
- eth/handler_test.go
- internal/ethapi/transaction_args.go
- miner/worker.go
- params/config.go
- params/protocol_params.go
- tests/state_test_util.go
> consensus/misc: rollback CalcBlobFee

- core/vm/contracts.go
- tests/0001-diff-go-ethereum.patch
- tests/init_test.go
1. fix PrecompiledContractsCancun
2. fix failed test cases about Cancun when running evm test CI
3. reorder PrecompiledContracts
* ...
> core/vm: fix PrecompiledContractsCancun

- cmd/geth/dbcmd.go
- core/genesis.go
- core/rawdb/database.go
This PR adds a feature to convert full node to fast node by introducing a new CLI tool called `delete-trie-state`. The tool will delete all PBSS key-value pairs and ancient state stores from the database.
This is particularly useful when users want to switch from full node to fast node by deleting the trie state from the database, reducing disk space occupied.
Usage: `./geth --datadir db delete-trie-state`
```
...
INFO [03-18|16:06:39.783] Opened ancient database                  database=/datadir_test/geth/chaindata/ancient/chain readonly=false frozen=909,979
INFO [03-18|16:06:43.759] Deleted trie state                       count=1,683,851 elapsed=3.971s
INFO [03-18|16:06:43.759] Removing ancient state database          path=/datadir_test/geth/chaindata/ancient/state
INFO …
```
> cmd/geth, core/rawdb: add dbDeleteTrieState

- cmd/evm/internal/t8ntool/execution.go
- core/chain_makers_test.go
- core/state_processor.go
- core/txpool/blobpool/blobpool.go
- core/txpool/blobpool/blobpool_test.go
- eth/catalyst/simulated_beacon.go
- eth/tracers/internal/tracetest/prestate_test.go
- eth/tracers/internal/tracetest/testdata/prestate_tracer/blob_tx.json
- eth/tracers/native/prestate.go
- ethclient/gethclient/gethclient.go
- internal/jsre/deps/web3.js
- params/config.go
- params/protocol_params.go
Port cancun related changes from unreleased v1.4.0
* ...
> Port cancun related changes from unreleased v1.4.0

- cmd/jsutils/README.md
- cmd/jsutils/gettxcount.js
- cmd/jsutils/getvalidatorversion.js
> cmd/jsutil: dump MinGasPrice for validator

- core/blockchain.go
This PR rephrases the log message of `TriesInMemory` when it differs from the default value.
The original intention is to inform users that they must use the same `TriesInMemory` value to prune data. However, with the introduction of PBSS, offline pruning is no longer required. Therefore, this log message should only be applied when users are running with hash-based state scheme.
> core: rephrase TriesInMemory log

- cmd/geth/genesis_test.go
- core/rawdb/database.go
- node/defaults.go
Switch to Pebble as the default db if none exists.
N/A
N/A
* N/A
> cmd/utils, node: switch to Pebble as the default db if none exists

- cmd/utils/flags.go
- core/remote_state_verifier.go
- triedb/pathdb/disklayer.go
This PR enforces a rule such that when `tries-verify-mode` is not `local`, it will always default to full sync instead of snap sync.
Snap sync is not supported on fast nodes.
```
INFO [03-13|13:52:26.157] Starting Geth on BSC mainnet...
INFO [03-13|13:52:26.157] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [03-13|13:52:26.159] Maximum peer count                       ETH=50 total=50
WARN [03-13|13:52:26.163] Only local TriesVerifyMode can support snap sync, resetting to full sync mode=none
...
```
- Fixed minor typo
> cmd/utils, core: only full sync for fast nodes

- internal/ethapi/api.go
This PR adds a new `net_nodeInfo` RPC method. It is the same as `admin_nodeInfo`.
The reason why `net_nodeInfo` is introduced even though `admin_nodeInfo` already exists is because some admin methods can control the behavior of the node. If a node were to be compromised with the admin namespace enabled, then the node could potentially stop functioning.
On the other hand, having access to retrieving the node information is extremely useful, especially when running an infrastructure. The content of the node info doesn't reveal sensitive information as well, so it could be added to the net namespace safely.
Another consideration is to remove `admin_nodeInfo` and replace with `net_nodeInfo`. This is possible, but this will contradict with the documentation of geth upstream. So in my opinion, …
> internal/ethapi: add net_nodeInfo

- miner/bid_simulator.go
- miner/worker.go
feat: add some metrics to monitor mev
> feat: mev metrics

- cmd/utils/flags.go
This PR adds a logic check such that if the node is fast node (i.e. `--tries-verify-mode` is not `local`), then it will disable the snap protocol by default.
When serving snap data (i.e. `AccountRange`, `StorageRange`, `TrieNodes`), access to a complete state trie is necessary. However, for fast nodes, since they only store the snapshot, they can't service these requests. Disabling this snap protocol by default may help reduce network calls and processing time for the nodes in general.
> cmd/utils: disable snap protocol for fast node

- cmd/geth/config.go
- core/block_validator.go
- core/blockchain.go
- core/rawdb/chain_freezer.go
- core/rawdb/freezer.go
- core/rawdb/freezer_table.go
- core/types/block.go
- eth/catalyst/api.go
- eth/downloader/downloader.go
- eth/downloader/queue.go
- eth/downloader/testchain_test.go
- graphql/graphql.go
- internal/ethapi/api.go
fix: fix some validation issues & ancient reset;
* fix: fix some validation issues & ancient reset;
* ...
> fix: fix some validation issues & ancient reset;

- CHANGELOG.md
- params/version.go
Release v1.4.3-alpha is a maintenance release, although it includes PR of Testnet FeynmanFix hard fork, but as 1.4.x is still at alpha status, for FeymanFix hard fork, you'd better try [v1.3.12](https://github.com/bnb-chain/bsc/releases/tag/v1.3.12)
v1.4.3-alpha mainly includes these parts:
- 1.Use PebbleDB as the default database
- 2.Use PBSS as the default state scheme
- 3.Some non-critical changes, like: no snap sync for fastnode; new flag: --instance; new cmd to delete trie state; some bugfix.
Same as previous v1.4.x-alpha, it could have some unknown risks or bugs there. It is not encouraged to run this version in your crucial business, but it would be appreciated if you can help try it in some non-crucial business environment and report bugs that you find.
* …
> release: prepare for release v1.4.3-alpha

- core/blockchain.go
- core/data_availability.go
- core/data_availability_test.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_chain_test.go
- core/rawdb/chain_freezer.go
- core/state/pruner/pruner.go
- core/types/block.go
- miner/worker.go
core: more check for validity of sidecars
core/rawdb: optimize write block with sidecars
core/rawdb: rollback interface freezeRange
* ...
> core/rawdb: optimize write block with sidecars

- .github/workflows/build-test.yml
- .github/workflows/commit-lint.yml
- .github/workflows/evm-tests.yml
- .github/workflows/integration-test.yml
- .github/workflows/lint.yml
- .github/workflows/unit-test.yml
- core/rawdb/ancient_scheme.go
- core/rawdb/chain_freezer.go
- core/rawdb/database.go
- core/rawdb/freezer.go
- core/rawdb/freezer_batch.go
- core/rawdb/freezer_table.go
- core/rawdb/freezer_test.go
- miner/bid_simulator.go
mev: add TxIndex for mev bid
rollback interface of NewFreezer
remove ci for blobtx
* ...
> mev: add TxIndex for mev bid

- core/blockchain.go
- core/rawdb/freezer_batch.go
- core/types/block.go
> format codestyle of WithSidecars

- tests/truffle/scripts/bootstrap.sh
- tests/truffle/scripts/bsc-rpc.sh
Trufle test would start a validator node and rpc node for smart contract test, but in snap mode path state scheme will need more time to prepare environment and it's unstable. Therefore, use full syncmode in path mode.
N/A
N/A
* N/A
> test: use full syncmode to run rpc node

- .github/CODEOWNERS
- consensus/parlia/parlia.go
- core/blockchain.go
- core/blockchain_reader.go
- core/data_availability.go
- core/data_availability_test.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_chain_test.go
- core/rawdb/chain_freezer.go
- core/rawdb/database.go
- core/rawdb/freezer.go
- core/rawdb/freezer_resettable.go
- core/rawdb/freezer_table.go
- core/rawdb/freezer_table_test.go
- core/rawdb/freezer_test.go
- core/rawdb/prunedfreezer.go
- core/rawdb/table.go
- core/state/pruner/pruner.go
- core/types/block.go
- eth/downloader/queue.go
- ethdb/database.go
- ethdb/remotedb/remotedb.go
- internal/ethapi/api_test.go
bugfix
1. DeleteBlobSidecars when setHeadBeyondRoot
2. fix blob number check when downloading block body
3. modify resetItems
a. add lock
b. remove all data files and prevent from overflow
c. set metadata
d. sync index file before reopen
4. only newSnapshot for genesis block
5. ResetEmptyBlobAncientTable in proper order
6. accept nil sidecars in block after cancun, but reset it to empty slices, this also solve the stuck issue in QA env
7.  fix EmptyBody
improvement
1. rename ReadRawBlobSidecars to ReadBlobSidecars
2. delete dead code in freezeRangeWithBlobs
3. narrow the semantics of resetItems and ResetTable
* ...
> 4844: bugfix and improve

- consensus/parlia/parlia.go
- core/chain_makers.go
- core/genesis.go
- core/types/block.go
- eth/catalyst/api.go
- graphql/graphql.go
- internal/ethapi/api.go
- miner/worker.go
This PR uses `types.EmptyWithdrawalsHash` as default empty withdrawal hash for parlia cancun.
* cancun: change empty withdrawHash value of header;
* ...
> cancun: change empty withdrawHash value of header;

- cmd/geth/config.go
- cmd/utils/flags.go
This PR adds additional fields (i.e. enodeID, ENR, ID) to the `node-info` metrics label.
It's useful to have that information visible at all times, instead of creating a custom script to pull that data.
> cmd: include more node info in metrics

- p2p/metrics.go
- p2p/server.go
This PR adds additional metrics to measure inbound and outbound peers.
Here's an example of the Grafana dashboard:
> p2p: add metrics for inbound/outbound peers

- core/blockchain.go
This pull request improves the chain rewinding mechanism a bit:
- use a more efficient approach for finding an available state in path scheme
- set a rewinding limit in hash scheme for preventing endless rewinding if the snapshot is above the head.
N/A
N/A
* N/A
> core: improve chain rewinding mechanism

- CHANGELOG.md
- params/version.go
This PR prepare for the release v1.3.13.
Change logs:
* [\#2358](https://github.com/bnb-chain/bsc/pull/2358) doc: add Feynman upgrade for mainnet
* [\#2335](https://github.com/bnb-chain/bsc/pull/2335) upgrade: update system contracts bytes code and hardfork time of Feynman upgrade
None
All client on BSC mainnet should upgrade to this version
> docs: add changelog and new version number

- core/types/bid.go
- internal/ethapi/api_mev.go
- miner/miner_mev.go
feat: add bid fee ceil in mev_params
> feat: add bid fee ceil in mev_params

- core/blockchain.go
core: fix block report when chain is not setHead
logInfo `Imported new chain segment` is misleading
to address issue https://github.com/bnb-chain/bsc/issues/2212
* ...
> core: fix block report when chain is not setHead

- CHANGELOG.md
- params/version.go
Release v1.4.4-beta mainly contains 2 parts:
- it supports mainnet Feynman hard fork
- it includes the code of BSC-4844, which will be enabled on Tycho hardfork after Feynman
However, it is still at beta phase, **for the upcoming mainnet Feynman hard fork, pls use stable release [v1.3.13](https://github.com/bnb-chain/bsc/releases/tag/v1.3.13)**
* [\#2279](https://github.com/bnb-chain/bsc/pull/2279) BlobTx: implement EIP-4844 on BSC
* [\#2337](https://github.com/bnb-chain/bsc/pull/2337) 4844: bugfix and improve
* [\#2339](https://github.com/bnb-chain/bsc/pull/2339) fix: missing block asigment WithSidecars
* [\#2350](https://github.com/bnb-chain/bsc/pull/2350) cancun: change empty withdrawHash value of header
* [\#2335](https://github.com/bnb-chain/bsc/pull/2335) upgrade: update system …
> release: prepare for release v1.4.4-beta

- eth/handler.go
- eth/sync.go
Noticed fast node printed this log and switched to snap sync:
```
Switch sync mode from full sync to snap sync reason="head state missing"
```
But fast node can not support snap sync, as it does not have trie node.
Actually it is bug caused by this commit, which removed the NoTrie() check by mistake: https://github.com/bnb-chain/bsc/pull/2200/commits/93d652bad37f6e5d369f2bf2dcdcbf1984f68e67
NA
NA
NA
> fix: don't switch to snapsync for fast node

- triedb/database.go
- triedb/pathdb/database.go
This PR fixes a bug on v1.4.x BSC version where a pruned fast node cannot be initialized properly.
State freezer is introduced in PBSS. When a full node is converted to a fast node (i.e. via prune state), state freezer is no longer needed. However, the current implementation still opens a state freezer even though it's a fast node, which immediately throws an error and causes the node to not be able to start at all. This fix adds a rule such that if the configuration states that `NoTries = true`, then the node doesn't need to open the state freezer.
> triedb: do not open state freezer under notries

- core/blockchain_reader.go
- core/state/statedb.go
This PR adds a check to `Blockchain.StateAt()` such that if the node is a fast node (i.e. NoTrie = true) and the snap layer cannot be found, then it will return an error. 
Refer to #2331.
By default, a fast node will have an empty trie for any state. Retrieving a value from an empty trie will give `0x00...00`. It may be confusing for users as `0x00...00` could also be the actual value. Hence, it's more useful to throw an error when the state is not available. 
Command
```
curl -H 'Content-Type: application/json'  -X POST --data '{"jsonrpc":"2.0", "method": "eth_getStorageAt", "params": ["0x00020F14443e103A0B72F1f2DFDaac07DDAa6Df5", "0x0", "0x237f199"], "id": 1}' http://127.0.0.1:8545
```
Output
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"state is not available"}}
```
- …
> core: stateDb has no trie and no snap return err

- params/config.go
For Tycho hard fork, pls refer: https://forum.bnbchain.org/t/bnb-chain-upgrades-testnet/934#h-4tycho-wip-21
The expected hard fork date, Testnet: 2024-04-17 05:07:22 AM UTC
NA
NA
NA
> config: setup Testnet Tycho(Cancun) hardfork date

- CHANGELOG.md
- accounts/keystore/account_cache_test.go
- consensus/clique/snapshot_test.go
- core/blockchain_reader.go
- core/state/statedb.go
- eth/fetcher/block_fetcher_test.go
- eth/filters/bench_test.go
- p2p/discover/v5_udp_test.go
- params/config.go
- params/version.go
- tests/state_test.go
- triedb/database.go
- triedb/pathdb/database.go
Release v1.4.5 is a hard fork release for **BSC Chapel Testnet**, the HF name is: Tycho, it mainly support Cancun EIPs on BSC:
- a.[BEP-336: Implement EIP-4844: ProtoDanksharding](https://github.com/bnb-chain/BEPs/pull/336)
- b.[BEP-343: Implement EIP-1153: Transient storage opcodes](https://github.com/bnb-chain/BEPs/pull/343)
- c.[BEP-344: Implement EIP-6780: SELFDESTRUCT only in same transaction](https://github.com/bnb-chain/BEPs/pull/344)
- d.[BEP-342: Implement EIP-5656: MCOPY](https://github.com/bnb-chain/BEPs/pull/342)
- e.[BEP-345: Implement EIP-7516: BLOBBASEFEE opcode](https://github.com/bnb-chain/BEPs/pull/345)
But BSC won’t support “EIP-4788: BeaconRoot”, as there is no CL on BSC.
The target Tycho hard fork time will be:
- Testnet: 2024-04-17 05:07:22 AM UTC
- Mainnet: To be …
> Draft release v1.4.5

- core/data_availability_test.go
- core/rawdb/accessors_chain.go
- core/rawdb/chain_freezer.go
- core/rawdb/freezer.go
blobtx: fix some found issues;
The newly added freezer table(BlobTable) relies on `FreezerEnv`, so add some code to detect that scenario.
* freezer: fix some env missing issues;
* logs: downgrade some info level logs;
* da: add some DA benchmark;
* ...
> blobtx: fix some found issues;

- consensus/parlia/parlia.go
- core/block_validator.go
- core/chain_makers.go
- core/types/block.go
- eth/downloader/queue.go
- eth/fetcher/block_fetcher.go
- eth/protocols/eth/handlers.go
- graphql/graphql.go
- miner/worker.go
fix: ensure empty withdrawals after cancun
* ...
> fix: ensure empty withdrawals after cancun

- eth/fetcher/block_fetcher.go
- eth/protocols/eth/handlers.go
fix: set withdrawals properly when fetching empty blocks
* ...
> fix: set withdrawals properly when fetching empty blocks

- internal/ethapi/api_mev.go
- miner/bid_simulator.go
- miner/miner.go
- miner/miner_mev.go
- miner/worker.go
- params/protocol_params.go
1. enable greedy merge tx in bid
2. fix several bugs
* ...
>  feat: greedy merge tx in bid

- params/config.go
fix: print value instead of pointer in ConfigCompatError
two errors in func ConfigCompatError as error info in the above picture
1. RewindToTime overflow
for dev testnet, often set timebased hardfork to `0`, so they will be enabled same with London Block at genesis
for example in genesis.json
`
"shanghaiTime": 0,
`
then we change it 
`
"shanghaiTime": 1712889032,
`
and run `geth --datadir ./ init ./genesis.json,  then RewindToTime will overflow to the max of uint64 type
2.  err.StoredTime and err.NewTime are pointers, print them is meaningless, their value are desired
* ...
> fix: print value instead of pointer in ConfigCompatError

- cmd/geth/chaincmd.go
This PR fixes a bug when importing blocks in an offline manner (i.e. `./bsc import block_data`).
Command: `./bsc import block_data`
```
...
INFO [02-29|15:00:58.337] Importing blockchain                     file=0_1000000
INFO [02-29|15:00:58.343] Generated state snapshot                 accounts=13 slots=0 storage=843.00B dangling=0 elapsed=9.620ms
INFO [02-29|15:01:06.365] Imported new chain segment               number=805 hash=544976..99b62e miner=0x685B1ded8013785d6623CC18D214320b6Bb64759 blocks=805 txs=25 mgas=4.490 elapsed=8.$
INFO [02-29|15:01:14.371] Imported new chain segment               number=1600 hash=05b2b9..f21f4e miner=0x35E7a025f4da968De7e4D7E4004197917F4070F1 blocks=795 txs=12 mgas=1.240 elapsed=8$
INFO [02-29|15:01:22.376] Imported new chain segment …
```
> cmd/geth: fix importBlock

- triedb/pathdb/database.go
- triedb/pathdb/difflayer_test.go
- triedb/pathdb/journal.go
If trieJournal is stored in the database, it retains the old journal format; if trieJournal writes to the journal file using the new journal format;
* ...
> fix: trieJournal format compatible old db format

- eth/fetcher/block_fetcher.go
fix: no import blocks before or equal to the finalized height
[Block imported below final block](https://github.com/bnb-chain/bsc/issues/2212) reported
this PR is to solve it
* ...
> fix: no import blocks before or equal to the finalized height

- core/blockchain.go
fix: allow fast node to rewind after abnormal shutdown
* ...
> fix: allow fast node to rewind after abnormal shutdown

- cmd/geth/chaincmd.go
- cmd/geth/config.go
- cmd/geth/dbcmd.go
- cmd/geth/pruneblock_test.go
- cmd/geth/snapshot.go
- cmd/utils/flags.go
- core/blockchain.go
- core/blockchain_reader.go
- core/blockchain_repair_test.go
- core/blockchain_sethead_test.go
- core/chain_indexer.go
- core/genesis.go
- core/headerchain.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_indexes.go
- core/rawdb/ancient_utils.go
- core/rawdb/chain_freezer.go
- core/rawdb/chain_iterator.go
- core/rawdb/database.go
- core/rawdb/schema.go
- core/rawdb/table.go
- eth/backend.go
- eth/catalyst/api.go
- ethdb/database.go
- ethdb/remotedb/remotedb.go
- node/errors.go
- node/node.go
This pull request uses the finalized block tag as the indicator for chain freezing and introduces the separation of block data into a dedicated blockdb. The principle support of PR: [BEP-365: Support multi-database based on data pattern](https://forum.bnbchain.org/t/bep-365-support-multi-database-based-on-data-pattern/2655)
Originally, the latest 90K blocks will be retained in the key-value store by default, which is regarded as "non-finalized" in the context of Proof-of-work. However, in Proof-of-Stake, we do have the concrete finalized block tag from the consensus client. Therefore, it makes more sense to directly rely on the Finalized for chain freezing.
By deploying it on a full node, we can see there are only 23 blocks left in the key-value store.
* Background
recent blocks are first …
> core: separated databases for block data

- cmd/geth/main.go
- cmd/utils/flags.go
- p2p/server.go
This PR adds a new feature to filter peers by their names based on a set of customized regex patterns.
Some outdated versions of nodes running on BSC may keep connecting to a healthy set of peers and only consume information, but not return any useful data. Such nodes should be filtered out to save network bandwidth.
In the config file:
```
...
[Node.P2P]
PeerFilterPatterns = ["(?!)geth"]
...
```
An example of a false regexp pattern error message:
```
t=2024-04-18T06:02:10+0000 lvl=error msg="Failed to compile peer filter patterns" err="error parsing regexp: missing closing ): `abc(def`"
```
> cmd, p2p: filter peers by regex on name

- core/blockchain.go
- eth/backend.go
- triedb/pathdb/database.go
- triedb/pathdb/difflayer_test.go
- triedb/pathdb/journal.go
During loading, If it is not necessary to judge based on --journalfile, handle it based on the existence of journalkv or journalfile;
* If trieJournal exists in the database, load it from the database first;
* If the journal file exists, load it from the journal file;
* If neither exists, treat it as a kv;
During persistence:
Handle it based on --journalfile, without considering whether it was journalkv or journalfile before;
Verification cases:
* Start and shut down using the kv method; Verify (type: journal kv);
* Start by specifying --journalfile to use journal file, and verify if it can start (type: journal kv), then shut down to save (type: journal file); Verify block tracking;
* Start using the kv method again (type: journal file); Verify block tracking; then shut down to save …
> feat: adaptive for loading journal file or journal kv during loadJournal

- miner/bid_simulator.go
This pr is to fix an issue within `BidRuntime.commitTransaction`
* fix wrong way to get blob tx sidecar
> fix: wrong way to get blob tx sidecar in `BidRuntime.commitTransaction`

- miner/bid_simulator.go
> Revert "fix: wrong way to get blob tx sidecar in `BidRuntime.commitTransaction`"

- eth/gasprice/feehistory.go
Add query limit to defend DDoS attack. Max allow 100 different percentiles in rewardPercentiles.
More bigger rewardPercentiles will enough to crash the serve. 
* eth/gasprice/feehistory.go: add maxQueryLimit
> Add query limit to defend DDoS attack

- core/blockchain_insert.go
- core/data_availability.go
- miner/worker.go
chore: add metric & log for blobTx;
The `IsDataAvaliblity` method costs fixed time for a certain node. However, the time may vary from machine to machine, adding the cost time metric for tracking. 
This PR also adds the number of blobs in the insert log.
* chore: add metric & log for blobTx;
* ...
> chore: add metric & log for blobTx;

- cmd/geth/chaincmd.go
- cmd/geth/dbcmd.go
- cmd/geth/snapshot.go
- cmd/utils/flags.go
A new JournalFilePath configuration has been added to triedb.Config, fix some code to adapt this config to cmd;
* ...
> fix: adapt journal for cmd

- miner/bid_simulator.go
- miner/worker.go
recommit bid when newBidCh is empty to maximize mev reward
* ...
> feat: recommit bid when newBidCh is empty to maximize mev reward

- consensus/parlia/parlia.go
- core/vm/contracts.go
double sign counter metric
* ...
> metrics: add doublesign counter

- .github/CODEOWNERS
- CHANGELOG.md
- consensus/parlia/parlia.go
- params/version.go
Release v1.4.6 is a maintenance release. It mainly includes 2 features and several enhancements.
The 2 features are:
- feature 1: [separated databases for block data](https://github.com/bnb-chain/bsc/pull/2227), it is an experimental feature for performance,  it is disabled by default.
- feature 2: [p2p: filter peers by regex on name](https://github.com/bnb-chain/bsc/pull/2404), it is for P2P connection,  to filter unwanted peers based on their names.
You may check the Change Log for detail.
FEATURE
* [\#2227](https://github.com/bnb-chain/bsc/pull/2227) core: separated databases for block data
* [\#2404](https://github.com/bnb-chain/bsc/pull/2404) cmd, p2p: filter peers by regex on name
IMPROVEMENT
* [\#2201](https://github.com/bnb-chain/bsc/pull/2201) chore: render system bytecode by …
> release: prepare for release v1.4.6

- triedb/pathdb/database.go
- triedb/pathdb/journal.go
The load journal function reads the TrieJournal from the database multiple times, which consumes a considerable amount of time. To optimize this, we only need to read the TrieJournal once and save the result into the database.
* ...
> fix: performance issue when load journal

- cmd/geth/main.go
- core/txpool/blobpool/blobpool.go
- core/txpool/legacypool/legacypool.go
- core/txpool/subpool.go
- core/txpool/txpool.go
- core/txpool/validation.go
- eth/api_miner.go
- miner/miner.go
- miner/worker.go
This PR tries to add a max gas limit in txpool when mining is enabled. It will drop the txs that the miner cannot package.
It will reduce pending txs in txpool, and reduce mem, CPU usage too.
* txpool: limit max gas when mining is enabled;
* ...
> txpool: limit max gas when mining is enabled;

- params/config.go
expected hard fork date:
Mainnet: 2024-06-20 06:05:00 AM UTC
NA
NA
NA
> config: setup Mainnet Tycho(Cancun) hardfork date

- CHANGELOG.md
- eth/ethconfig/config.go
- params/version.go
Release v1.4.7 is a hard fork release for **BSC Mainnet**, the HF name is: Tycho, it mainly support Cancun EIPs on BSC:
- a.[BEP-336: Implement EIP-4844: ProtoDanksharding](https://github.com/bnb-chain/BEPs/pull/336)
- b.[BEP-343: Implement EIP-1153: Transient storage opcodes](https://github.com/bnb-chain/BEPs/pull/343)
- c.[BEP-344: Implement EIP-6780: SELFDESTRUCT only in same transaction](https://github.com/bnb-chain/BEPs/pull/344)
- d.[BEP-342: Implement EIP-5656: MCOPY](https://github.com/bnb-chain/BEPs/pull/342)
- e.[BEP-345: Implement EIP-7516: BLOBBASEFEE opcode](https://github.com/bnb-chain/BEPs/pull/345)
But BSC won’t support “EIP-4788: BeaconRoot”, as there is no CL on BSC.
The target Tycho hard fork time will be:
- Mainnet:  2024-06-20 06:05:00 AM UTC
After `Tycho` hard fork, …
> release: prepare for release v1.4.7

- eth/filters/api.go
This PR adds a limit of 1000 to the "inner" topics in a filter-criteria
* ...
> eth/filters: enforce topic-limit early on filter criterias (#29535)

- eth/handler.go
eth/handler: check blobs before broadcast blocks
when nodes get  a new block from other peers, 
It will broadcast blocks directly to part peers after only `verifyHeader`
here add a more check before broadcasting.
* ...
> eth/handler: check blobs before broadcast blocks

- ethdb/pebble/pebble.go
- go.mod
- go.sum
Current version of pebble used is  v0.0.0-20230928194634-aa077af62593 adnd pebble vesion v1.10 Is stable and being used in production. And  go-ethereum has upgrade the version to pebble v1.10.
The following is a comparison of the two full nodes performance  before and after the upgrade. The height is about 3725w to 3800w.   Performance has no impact after upgrade. 
* ...
> db: upgrade  pebble version

- core/block_validator.go
- eth/handler.go
eth/handler: check lists in body before broadcast blocks
* ...
> eth/handler: check lists in body before broadcast blocks

- cmd/geth/dbcmd.go
- trie/inspect_trie.go
This pr fix memory leak when inspect trie with big dataset(more than 300M account and 100M contract)
Bug fix for memory leak
```
./geth db inspect-trie latest 5000 10
```
This command will inspect the latest state tree with a concurrency of 5000 trie, and finally print out the account tree and top 10 contract tree statistics.
* add topN for print top n storage trie
* refactor for calc topN
* fix memory leak
> cmd: fix memory leak when big dataset

- core/blockchain_reader.go
- core/rawdb/freezer.go
- eth/downloader/downloader.go
When user prunes block too much, the node will not sync again. This PR reset the sync `floor`, and fixed the ancient query bug.
* freezer: fix offset issues when query ancient;
* sync: opt pruned node sync logic;
> sync: fix some sync issues caused by prune-block.

- ethclient/ethclient.go
- internal/ethapi/api.go
- internal/ethapi/api_test.go
- internal/web3ext/web3ext.go
Make the param showBlob optional, user don't need change the way to query blobs, even if they don't add the bool param it work as before.
The two way both works now.
```
{"jsonrpc":"2.0","method":"eth_getBlobSidecars","params":["latest", false],"id":1}]'
{"jsonrpc":"2.0","method":"eth_getBlobSidecars","params":["latest"],"id":1}]'
```
* ...
> internal/ethapi: add optional parameter for blobSidecars

- eth/api_admin.go
- eth/api_miner.go
- internal/web3ext/web3ext.go
I think the mev commands are much more related to miner group, not admin group.
The command JS is missing so I made it up
`add mev operation to console`
```js
miner.mevRunning()
miner.startMev()
miner.stopMev()
miner.addBuilder("0xadd", "http://")
miner.removeBuilder("0xadd")
```
NA
NA
NA
> fix: add mev method to console

- miner/bid_simulator.go
- miner/miner.go
fix: imit the gas price of the mev bid
* ...
> fix: limit the gas price of the mev bid

- core/types/bid.go
- miner/bid_simulator.go
This commit introduces a NonRevertible hash list within the RPC to address potential inconsistencies between the builder and validator during bundle operations. The builder sends a list of transaction hashes, which must be successfully executed, to the validator. If the validator cannot accurately execute the bundle, it refrains from packing that block. This mechanism ensures that both components maintain output consistency under the same input conditions, thereby preventing financial losses for searchers due to incorrect block inclusion.
This happened on BloxRoute builder before. The simulation runs fine on builder but one transaction in bundle somehow couldn't pass on validator, which costs searcher $$$$$
The builder sends the list of hashes from bundle txs that is no-revertible, to …
> dev: ensure consistency in BPS bundle result

- cmd/geth/chaincmd.go
- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- core/genesis.go
- core/vm/contracts.go
- core/vm/evm.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
- params/config.go
core/vm: add secp256r1 into PrecompiledContractsHaber
* ...
> core/vm: add secp256r1 into PrecompiledContractsHaber

- CHANGELOG.md
- params/version.go
Release v1.4.8 is a cut-in **hard fork release for BSC Testnet and Mainnet**, the HF name is: [Haber](https://forum.bnbchain.org/t/bnb-chain-roadmap-mainnet/936#h-4haber-wip-25), it only supports one BEP: [BEP-381: Precompile for secp256r1 Curve Support](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-381.md)
As there is strong demand for supporting of secp256r1 pre-compile contract, we decide to move it faster.
And BSC would use address 0x100, which is same as other major chains to make it easier for developers. 
Developers may refer this code on how to use this pre-compile contract: https://github.com/getclave/clave-contracts/blob/master/contracts/helpers/VerifierCaller.sol
The target Haber hard fork time will be:
- Testnet:  2024-05-29 06:07:00 AM UTC
- Mainnet:  2024-06-20 …
> release: prepare for release v1.4.8

- cmd/jsutils/faucet_request.js
Calculate number of successful faucent transactions.
For monitoring puposes.
This kind of request can be made in the private faucet machine: 
`node cmd/jsutils/faucet_request.js --rpc https://data-seed-prebsc-1-s1.bnbchain.org:8545 --startNum 40528221`
* Extra file in jsutils
> jsutils: faucet successful requests within blocks

- core/rawdb/database.go
- core/rawdb/table.go
- ethdb/database.go
- ethdb/remotedb/remotedb.go
When executing inspect, an error in judgment causes block data to be repeatedly traversed, resulting in a large amount of data being marked as unaccounted.
In Go, directly comparing two interface values for equality is generally unsafe, especially for complex types like the database interface ethdb.Database. This is because interface comparison checks not only their values but also whether their dynamic types match.
Add the `HasSeparateBlockStore` interface to indicate whether a separate block store is enabled.
* ...
> fix: fix inspect database error

- cmd/geth/pruneblock_test.go
- cmd/geth/snapshot.go
- cmd/utils/flags.go
- cmd/utils/history_test.go
- core/blockchain_repair_test.go
- core/blockchain_sethead_test.go
- core/blockchain_test.go
- core/rawdb/accessors_chain_test.go
- core/rawdb/chain_freezer.go
- core/rawdb/database.go
- core/state/pruner/pruner.go
- core/txindexer_test.go
- eth/downloader/downloader_test.go
- eth/handler_test.go
- node/node.go
- triedb/pathdb/database_test.go
- triedb/pathdb/journal.go
After introducing the feature to **use the finalized block as the chain freeze indicator** for the multiDatabase feature, the kv database only contains **a few dozen blocks**. Performing prune block operations and then force-killing the process can lead to the blockchain rewinding to a non-existent block. To address this issue, the prune block will by default retain 90,000 blocks in the ancient database.
Other Changes:
1. **Finalized Block as Chain Freeze Indicator**: The feature to use the finalized block as the chain freeze indicator for the multiDatabase feature will only be effective when the multiDatabase is enabled.
2. **Prune Block Fix**: Fixed the bug where prune block operations could not execute when the trie journal was set to use journal file.
3. **Journal Optimization**: …
> fix: keep 9W blocks in ancient db when prune block

- cmd/geth/chaincmd.go
- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- core/genesis.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
- params/config.go
params/config: add Bohr hardfork
* ...
> params/config: add Bohr hardfork

- cmd/geth/dbcmd.go
- core/rawdb/database.go
Some db CLI cannot be used in pruned disk db. Therefore, add a empty freeze db to support some CLIs: `./geth db metadata`, `./geth db inspect-reserved-oldest-blocks` and `./geth db inspect`.
N/A
N/A
* N/A
> fix: add an empty freeze db

- miner/bid_simulator.go
- miner/worker.go
fix: waiting for the last simulation before pick best bid
The final round of bid simulation is often interrupted by stopTimer and not fully packed, making it less competitive than local miner and degrading the mev experience.
So we take two steps to optimize it:
1. do not set a stop timer when the bid is packaged;
2. when the local miner fetches the best bid, wait a while for the bid that is being packaged at the time to finish job.
This is a short-term solution. It will be addressed in the long run with a more formal fix and be put into the next stable release.
* ...
> fix: waiting for the last simulation before pick best bid

- CHANGELOG.md
- params/version.go
v1.4.9 is a maintenance release,  which mainly addressed some issues about: **prune-block**, **multi-database** and **MEV** 
There is no compatible change, to upgrade to v1.4.9 from v1.4.x, simply replace the binary should work.
**FEATURE**
* [\#2463](https://github.com/bnb-chain/bsc/pull/2463)  utils: add check_blobtx.js
* [\#2470](https://github.com/bnb-chain/bsc/pull/2470)  jsutils: faucet successful requests within blocks
* [\#2467](https://github.com/bnb-chain/bsc/pull/2467)  internal/ethapi: add optional parameter for blobSidecars
**IMPROVEMENT**
* [\#2462](https://github.com/bnb-chain/bsc/pull/2462)  cmd/utils: add a flag to change breathe block interval for testing
* [\#2497](https://github.com/bnb-chain/bsc/pull/2497)  params/config: add Bohr hardfork
* …
> release: prepare for release v1.4.9

- core/types/bid.go
- eth/api_backend.go
- ethclient/ethclient.go
- go.mod
- internal/ethapi/api_mev.go
- internal/ethapi/api_test.go
- internal/ethapi/backend.go
- internal/ethapi/transaction_args_test.go
- miner/miner_mev.go
feat: add mev helper params and func
> feat: add mev helper params and func

- core/blockchain.go
- core/genesis.go
- core/headerchain.go
- core/rawdb/chain_iterator.go
- core/rawdb/database.go
In a multi-database, the performance of the chain commit process degrades. The chain commit process mainly involves writing data; the performance drops when using multiple databases.
Optimization
* The BlockStore makes multiple calls to the rawdb interface, performing multiple batch writes. Encapsulating these into a single batch will improve performance.
* Currently, the process writes to BlockStore first and then to chaindb in a sequential manner. Parallelizing these two database writes using go routines will optimize the write process.
Impact
These optimizations result in a 10% performance improvement during the commit phase in a multi-database setup.
* ...
> perf: optimize chain commit performance for multi-database

- core/forkchoice.go
core/forkchoice: improve stablity when inturn block not generated
* ...
> core/forkchoice: improve stability when inturn block not generated

- internal/ethapi/transaction_args.go
- internal/ethapi/transaction_args_test.go
This is subtle change to remove the zero gasprice check on BSC  to fix issue: https://github.com/bnb-chain/bsc/issues/2517
Before signing a transaction, there is gasPrice check. For Ethereum zeroGasPrice is unacceptable since London hard fork. But for BSC, zero gasprice is still acceptable.
note: blobGasFeePrice can not be zero right now.
NA
NA
Before this PR, sign a zero gasprice BSC transaction will be failed, but after this PR it will be success.
> fix: remove zero gasprice check for BSC

- eth/handler_eth_test.go
- eth/sync_test.go
To fix issue: https://github.com/bnb-chain/bsc/issues/2489
this case failed randomly in github CI, the ratio of around 20%.
but it can not be reproduced locally:
```
cd eth
go test -p 1 -v -run TestSnapSyncWithBlobs -count 100
```
There could be a potential risk between `runEthPeer` and `runSnapExtension`, as  they shared the `handler.peers`. Add extra wait time for `runEthPeer`
And also same for UT TestBroadcastBlock3Peers:
```
--- FAIL: TestBroadcastBlock3Peers (0.24s)
handler_eth_test.go:672: broadcast count mismatch: have 0, want 1
```
NA
NA
NA
> UT: random failure of TestSnapSyncWithBlobs

- eth/fetcher/block_fetcher.go
fix: ensure empty withdrawals after cancun before broadcast
no matter get a new block directly or by fetching
both need to ensure empty withdrawals after cancun before broadcast
* ...
> fix: ensure empty withdrawals after cancun before broadcast

- CHANGELOG.md
- params/version.go
**Notice:**
v1.4.10 solved the ["BAD BLOCK"](https://github.com/bnb-chain/bsc/issues/2522) issue after Haber hard fork, pls use this version if your node has the BAD BLOCK issue.
v1.4.10 is a maintenance release,  which has several improvements and fixes:
- improve: performance, MEV-API, less-reorg
- fix: ethapi, UT failure, rpc:getBlobSidecars, BAD BLOCK caused by nil withdrawals.
There is no compatible change, to upgrade to v1.4.10 from v1.4.x, simply replace the binary should work.
* NA
* [\#2512](https://github.com/bnb-chain/bsc/pull/2512) feat: add mev helper params and func
* [\#2508](https://github.com/bnb-chain/bsc/pull/2508) perf: speedup pbss trienode read
* [\#2509](https://github.com/bnb-chain/bsc/pull/2509) perf: optimize chain commit performance for multi-database
* …
> release: prepare for release v1.4.10

- CHANGELOG.md
- core/blockchain.go
- core/forkchoice.go
- core/genesis.go
- core/headerchain.go
- core/rawdb/chain_iterator.go
- core/rawdb/database.go
- core/types/bid.go
- eth/api_backend.go
- eth/backend.go
- eth/fetcher/block_fetcher.go
- eth/handler_eth_test.go
- eth/sync_test.go
- ethclient/ethclient.go
- internal/ethapi/api_mev.go
- internal/ethapi/api_test.go
- internal/ethapi/backend.go
- internal/ethapi/transaction_args.go
- internal/ethapi/transaction_args_test.go
- miner/miner_mev.go
- params/version.go
- triedb/pathdb/difflayer.go
- triedb/pathdb/disklayer.go
- triedb/pathdb/layertree.go
- triedb/pathdb/metrics.go
**Notice:**
v1.4.10 solved the ["BAD BLOCK"](https://github.com/bnb-chain/bsc/issues/2522) issue after Haber hard fork, pls use this version if your node has the BAD BLOCK issue.
v1.4.10 is a maintenance release,  which has several improvements and fixes:
- improve: performance, MEV-API, less-reorg
- fix: ethapi, UT failure, rpc:getBlobSidecars, BAD BLOCK caused by nil withdrawals.
There is no compatible change, to upgrade to v1.4.10 from v1.4.x, simply replace the binary should work.
* NA
* [\#2512](https://github.com/bnb-chain/bsc/pull/2512) feat: add mev helper params and func
* [\#2508](https://github.com/bnb-chain/bsc/pull/2508) perf: speedup pbss trienode read
* [\#2509](https://github.com/bnb-chain/bsc/pull/2509) perf: optimize chain commit performance for multi-database
* …
> Draft release v1.4.10

- miner/bid_simulator.go
fix: nil pointer when clear simulating bid
* ...
> fix: nil pointer when clear simulating bid

- CHANGELOG.md
- params/config.go
prepare for the v1.4.11
add change logs
* [\#2534](https://github.com/bnb-chain/bsc/pull/2534) fix: nil pointer when clear simulating bid
* [\#2535](https://github.com/bnb-chain/bsc/pull/2535) upgrade: add HaberFix hardfork
None
None
> doc: add changelog for v1.4.11

- params/version.go
Bump the version from 1.4.10 to v1.4.11
None
None
None
> release: bump version to 1.4.11

- cmd/jsutils/README.md
- cmd/jsutils/get_perf.js
cmd/jsutils: add a tool to get performance between a range of blocks
node get_perf.js --rpc http:/127.0.0.1:8545 --startNum 19470 --endNum 19670
```
Get the performance between [ 19470 , 19670 )
txCountPerBlock = 3142.81 txCountTotal = 628562 BlockCount = 200 avgBlockTime = 3.005 inturnBlocksRatio 0.975
txCountPerSecond = 1045.8602329450914 avgGasUsedPerBlock = 250.02062627 avgGasUsedPerSecond =  83.20153952412646
```
* ...
> cmd/jsutils: add a tool to get performance between a range of blocks

- go.mod
- go.sum
to fix: https://github.com/bnb-chain/bsc/issues/2544
`github.com/wercker/journalhook@v0.0.0-20180428041537-5d0a5ae867b3` was imported indirectly by `github.com/prysmaticlabs/prysm@v0.0.0-20220124113610-e26cde5e091b`.
but the `commit: 5d0a5ae867b3` was deleted, so the compile would failed for the first time.
Actually journalhook is not used in BSC, the latest prysm also removed the dependency of journalhook.
Just replace it with the latest commit should be fine.
NA
NA
NA
> go.mod: update missing dependency

- .nancy-ignore
> nancy: ignore go-retryablehttp@v0.7.4

- core/rawdb/ancient_utils.go
The files of  freezer ancient state folder will be empty after running "db delete-trie-state" command in pbss mode and the inspectFreezers function need to judge this situation to avoid inspecting the empty state freezer. 
fix issue:[issue]( https://github.com/bnb-chain/bsc/issues/2543)
* ...
> fix: fix inspect after delete-trie-state 

- core/rawdb/prunedfreezer.go
The first time you run with the --pruneancient option, a BAD BLOCK error may occur.
When pruneancient is enabled, it deletes the CanonicalHash previously stored in the ancient database. This results in the loss of some CanonicalHash entries in the range [first, frozen) during the subsequent loop.
In gcKvStore, when attempting to delete CanonicalHash and Header, the ancients and numbers do not match, preventing the proper deletion.
> For example, if first in the loop is 60002, the range being traversed is [60002, 90003). Due to the deletion of CanonicalHash in the range [60002, 61298], the data in ancients is actually [61299, 90003).
In gcKvStore, the number range [60002, 88706) is being deleted, while the corresponding hash range is [61299, 90003), causing the construction of incorrect …
> fix: online prune of ancient delete unexpected blocks

- cmd/jsutils/README.md
- cmd/jsutils/getslashcount.js
add a tool to get validators slash count.  Need use archive rpc.
* ...
> cmd/jsutils: add a tool to get slash count

- cmd/geth/chaincmd.go
- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- core/genesis.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
core: clearup testflag for Cancun and Haber
mainnet has passed  Cancun and Haber fork
* ...
> core: clearup testflag for Cancun and Haber

- core/blockchain.go
core: avoid to cache block before wroten into db
let's see the `GetBlock` interface, it's used to get block from db
after add func `cacheBlock`, block not wroten into db also will be add into bc.blockCache.
so this destroy the semitics of `GetBlock`, and will lead to potential issue
```
// GetBlock retrieves a block from the database by hash and number,
// caching it if found.
func (bc *BlockChain) GetBlock(hash common.Hash, number uint64) *types.Block {
// Short circuit if the block's already in the cache, retrieve otherwise
if block, ok := bc.blockCache.Get(hash); ok {
return block
}
block := rawdb.ReadBlock(bc.db, hash, number)
if block == nil {
return nil
}
// Cache the found block for next time and return
bc.blockCache.Add(block.Hash(), block)
return block
}
```
for example, if a …
> core: avoid to cache block before wroten into db

- core/state/statedb.go
In the force-kill test scenario, it was found that rewind failed. The specific reason was that the data format of the state's undolog was incorrect. Failed to rollback state, error like this:
`
invalid account index, len: 0
`
https://github.com/bnb-chain/bsc/blob/a5810fefc90de206459cca4c24e5946670f532da/miner/worker.go#L1434-L1437
Miner inner workflow uses statedb copy function, but the copy function loses the state's origin fields, so the written undo log is wrong and fails to rollback.
N/A.
* Statedb: copy function
> fix: fix statedb copy

- miner/bid_simulator.go
- miner/worker.go
* mev_sendBid replies current bestBid reward if it's discard due to low reward (but it still cost 1 submit chance for builder).
* The thread safe transaction set is no need for GreedyMergeTx. The change will lift extensive locking mechanisms.
Add builder bid arriving and comparing log into standard log output.
* Simplified bidRuntime comparison by moving comparing function into bidRuntime.
* add bid arrive/comparsion detail logs,  helps validator records the builder bid operation, to better understand and get involve the BPS mechanisms.
> feat: enhance bid comparison and reply bidding results && detail logs

- core/blockchain.go
- core/forkchoice.go
core: adapt highestVerifiedHeader to FastFinality
* ...
> core: adapt highestVerifiedHeader to FastFinality

- consensus/parlia/parlia.go
- core/vote/vote_manager.go
core/vote: not vote if too late for next in turn validator
Assume that at block height N, validator Va mines a large block BN, broadcasts it, and votes immediately. Due to the block's large size, other validators (such as Vb, Vc, and Vd) take a longer time to import BN, resulting in Vc and Vd voting for BN later. As a result, at block height N+1, Vb fails to collect enough votes for BN and mines and broadcasts a block BN1 without vote proof. Subsequently, backup validator Vc collects enough votes for BN, mines, and broadcasts a block BN1' with vote proof, causing other validators to experience a block reorganization (reorg).
this PR suggest not to vote if too late for next in turn validator
* …
> core/vote: not vote if too late for next in turn validator

- cmd/jsutils/README.md
- cmd/jsutils/getslashcount.js
add print validator name 
Use latest block default. can use `--Num` to query at any block height
* cmd/jsutill: print validator name in log
> cmd/jsutill: add log about validator name

- cmd/faucet/faucet.go
- cmd/utils/history_test.go
- signer/fourbyte/abi.go
> chore: fix some comments

- core/blockchain.go
- core/events.go
- eth/handler.go
- miner/worker.go
miner/worker: broadcast block immediately once sealed
state.commit and write down some block may cost more than 700+ms
this PR is to reduce the unnecessary delay
* ...
> miner/worker: broadcast block immediately once sealed

- cmd/geth/pruneblock_test.go
- core/blockchain_repair_test.go
- core/blockchain_sethead_test.go
- core/rawdb/chain_freezer.go
This PR adds a silent logic. For scenarios that require Freezer Env, `SetupFreezerEnv` should be called to initialize. For other scenarios, Freezer will silently wait 3 times and return, and will no longer execute freeze.
Using silent logic effectively avoids large-scale API modifications and unnecessary DB initialization operations.
It fixed this issue, https://github.com/bnb-chain/bsc/issues/2570
* freezer: opt freezer env check logic;
* ...
> freezer: Opt freezer env checking

- core/rawdb/freezer_table.go
- core/rawdb/prunedfreezer.go
The first time online pruning is enabled, the freeze() process starts from 0, leading to a large number of log.Error("Canonical hash missing, can't freeze", "number", f.frozen) logs.
In the freezer's database, record FrozenOfAncientFreezer. When online pruning is enabled for the first time, it will continue to freeze from the previous position.
* ...
> fix: pruneancient freeze from the previous position when the first time

- core/rawdb/freezer.go
When using the freezer deletion strategy, some side chain blocks are not yet finalized and might still be subject to reorganization (reorg). Therefore, they cannot be deleted at this time.
* ...
> fix: remove delete and dangling side chains in prunefreezer

- CHANGELOG.md
- params/version.go
it is a maintenance release with some bug fix and enhancement.
NA
* [\#2557](https://github.com/bnb-chain/bsc/pull/2557) fix: fix state inspect error after pruned state
* [\#2562](https://github.com/bnb-chain/bsc/pull/2562) fix: delete unexpected block
* [\#2566](https://github.com/bnb-chain/bsc/pull/2566) core: avoid to cache block before wroten into db
* [\#2567](https://github.com/bnb-chain/bsc/pull/2567) fix: fix statedb copy
* [\#2574](https://github.com/bnb-chain/bsc/pull/2574) core: adapt highestVerifiedHeader to FastFinality
* [\#2542](https://github.com/bnb-chain/bsc/pull/2542) fix: pruneancient freeze from the previous position when the first time
* [\#2564](https://github.com/bnb-chain/bsc/pull/2564) fix: the bug of blobsidecars and downloader with multi-database
* …
> release: prepare for release v1.4.12

- cmd/jsutils/README.md
- cmd/jsutils/get_perf.js
- consensus/parlia/api.go
consensus/parlia: add GetJustifiedNumber and GetMinerHistory
```
curl http://127.0.0.1:8545/ \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"parlia_getJustifiedNumber","params":["0x116"],"id":1,"jsonrpc":"2.0"}'
```
``` json
{"jsonrpc":"2.0","id":1,"result":277}
```
```
curl http://127.0.0.1:8545/ \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"parlia_getFinalizedNumber","params":["0x116"],"id":1,"jsonrpc":"2.0"}'
```
``` json
{"jsonrpc":"2.0","id":1,"result":276}
```
* ...
> consensus/parlia: add GetJustifiedNumber and GetFinalizedNumber

- consensus/consensus.go
- consensus/parlia/parlia.go
- core/blockchain.go
- core/blockchain_reader.go
- core/chain_makers.go
- core/data_availability_test.go
- core/events.go
- core/headerchain.go
- core/vote/vote_manager.go
- core/vote/vote_pool.go
core/vote: vote before committing state and writing block
* ...
> core/vote: vote before committing state and writing block

- consensus/parlia/parlia.go
- core/chain_makers.go
- core/genesis.go
- core/types/block.go
- miner/worker.go
[BEP-402: Complete Missing Fields in Block Header to Generate Signature](https://github.com/bnb-chain/BEPs/pull/402)
* ...
> BEP-402: Complete Missing Fields in Block Header to Generate Signature

- consensus/parlia/snapshot.go
[BEP-404: Clear Miner History when Switching Validators Set](https://github.com/bnb-chain/BEPs/pull/404)
* ...
> BEP-404: Clear Miner History when Switching Validators Set

- core/forkchoice.go
core: improve the network stability when double sign happens
for example, 3 validator(vb, vc, vd) do an double sign attack together,
they can easily spilt the network into 8 subnets, then the whole chain stops
to solve this issue, we should give a definited rule to select forks.
in additon, this change is back compatible
* ...
> core: improve the network stability when double sign happens

- core/blockchain.go
core: cache block after wroten into db
[PR 2566](https://github.com/bnb-chain/bsc/pull/2566) fix a potential bug, but may downgrade the performance,
this PR is to recovery the performance
* ...
> core: cache block after wroten into db

- core/blockchain.go
- miner/bid_simulator.go
To address and fix the issue described in [hash schema: prune state failed #2588](https://github.com/bnb-chain/bsc/issues/2588)
The prune-state command, when specifying --triesInMemory 32, results in a "no snapshot paired state" error, while the command runs successfully with the default value.
Previously, the fixed value of TriesInMemory was set to 128 and then changed to a configurable value. However, there are still some references in the code that have not been updated. For example, during persistence in (bc *BlockChain) Stop(), the constant value 128 is still being used instead of the configurable bc.TriesInMemory().
* ...
> fix: prune-state when specify `--triesInMemory 32`

- consensus/parlia/parlia.go
consensus/parlia: modify mining time for last block in one turn
the last block in one turn is too small, so revert it
compared to logic before BEP-341, just modify the delay for front blocks in one turn
* ...
> consensus/parlia: modify mining time for last block in one turn

- cmd/geth/chaincmd.go
- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- core/genesis.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
cmd/utils: add new flag OverridePassedForkTime
reth client not accept hardfork time equal to `0`
* ...
> cmd/utils: add new flag OverridePassedForkTime

- miner/bid_simulator.go
- miner/miner.go
define bidGasPrice as sum of (gas used * gas price ) for every non-mempool tx / by the sum of gas used for non-mempool tx.
In current implementation, when a builder receive a bundle, it will simulate all txs within the bundle. Bundle price = sum( gas price * gas used ) /sum(gas used ) , ensure bundle price > = 1 gwei. It seems not a good solution. Consider the following example:
There is a public mempool tx with 100 gwei, gas usage 21,000 and its a simple transfer tx. A malicious actor can submit a 0 gas price tx to bundle it up with the public mempool tx, this tx has 0 gwei gas price, it can involve very complex smart contract calls and it has a gas usage of 1,000,000. 
In that case, it will be (100\*21000+0\*1000000)/(21000+1000000)=2.05 gwei. This means this bundle can be included by …
> fix: only take non-mempool tx to calculate bid price

- tests/0001-diff-go-ethereum.patch
- tests/run-evm-tests.sh
tests: fix evm-test CI
the current evm-test ci workflow will pass even error happens
for example, https://github.com/bnb-chain/bsc/actions/runs/10140582505/job/28036084839?pr=2618
this PR is to fix it
* ...
> tests: fix evm-test CI

- consensus/parlia/parlia.go
consensus/parlia: exclude in turn validator when calculate backoffTime for backup validators
when calculate backoffTime for backup validators, in turn validator should be excluded.
otherwise, the min delay for backup validators may will be 2 seconds, 
but actually,1 second is expected.
* ...
> consensus/parlia: exclude inturn validator when calculate backoffTime

- core/state_processor.go
core: not record `zero hash` beacon block root
* ...
> core: not record `zero hash` beacon block root with Parlia engine

- Makefile
Makefile: use docker compose v2 instead of v1
truffle-test CI failed
https://github.com/bnb-chain/bsc/actions/runs/10242044173/job/28331648481?pr=2627
because the latest ubuntu has dropped supporting `docker compose v1`
[[Ubuntu, Windows] Docker Compose v1 will be removed from images on July, 29](https://github.com/actions/runner-images/blob/ubuntu22/20240730.2/images/ubuntu/Ubuntu2204-Readme.md)
so we switch to use `docker compose v2`
* ...
> Makefile: use docker compose v2 instead of v1

- CHANGELOG.md
- go.sum
- params/version.go
Release v1.4.13 is a **hard fork release for BSC Testnet**, the HF name is: [Bohr](https://forum.bnbchain.org/t/bnb-chain-roadmap-mainnet/936#h-5bohr-wip-26), there are 4 BEPs in Bohr:
- [BEP-341: Validators can produce consecutive blocks](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-341.md)
- [BEP-402: Complete missing fields in Block Header to generate Signature](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-402.md)
- [BEP-404: Clear Miner History when Switching Validators Set](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-404.md)
- [BEP-410: Add Agent for Validators](https://github.com/bnb-chain/BEPs/pull/410)
Among these BEPs, **BEP-341** holds the most significance as it proposes a change to the block production protocol. However, BEP-341 will only come …
> release: prepare for release v1.4.13

- core/blockchain.go
core: remove wrong cache for receipts
receipt.EffectiveGasPrice and receipt.Logs has the wrong value when a new block mined
* ...
> core: fix cache for receipts

- eth/api_backend.go
- internal/ethapi/api.go
- internal/ethapi/api_test.go
- internal/ethapi/backend.go
- internal/ethapi/transaction_args_test.go
internal/ethapi: make GetFinalizedHeader monotonically increasing
* ...
> internal/ethapi: make GetFinalizedHeader monotonically increasing

- core/forkchoice.go
core: improve readability of the fork choice logic
* ...
> core: improve readability of the fork choice logic

- core/rawdb/prunedfreezer.go
fix #2642 
If the dataset has been pruned, when set `--pruneancient` the offset value of the freezer will be incorrect;
* ...
> fix: update prunefreezer’s offset when pruneancient and the dataset has pruned block

- core/types/blob_sidecar.go
- ethclient/ethclient.go
Fix the APIs response of BlobSidecars and BlobSidecarByTxHash
Recently, I used the APIs above but they didn't work, and I found the response has the wrong structure. So I fixed it.
> ethclient: fix BlobSidecars api

- params/config.go
`HaberFix` is a bugfix hard fork, which mainly enhances the network's stability in some corner cases, so we decide to support it along with `Bohr` hard fork on mainnet to avoid too frequent node upgrade.
The 2 hard fork will be enabled subsequently, i.e. `Bohr` will be a few minutes after `Haberfix`
The expected hard fork date:
- Mainnet-HaberFix: 2024-09-26 02:02:00 AM UTC
- Mainnet-Bohr:     2024-09-26 02:20:00 AM UTC
NA
NA
NA
> config: setup 2 Mainnet hardfork date: HaberFix & Bohr

- Makefile
- cmd/faucet/faucet.go
The faucet service is not stable, sometimes it got stuck for quite a long time and can only be recovered by restarting the process.
After some investigation, found it could be caused by transaction lost, there are various cases that a transaction can be dropped, such as network issue or discarded when TxPool is full. One lost transaction could cause the stuck of faucet service, due to the nonce gap issue.
This PR will check for each new imported block, if the faucet transaction got stuck for a certain time, trigger a resend operation, so it will not block the faucet service.
NA
NA
NA
> faucet: bump and resend faucet transaction if it has been pending for a while

- CHANGELOG.md
- params/version.go
**v1.4.14** is a hard fork release for BSC mainnet, which mainly supporst the **Bohr** hard fork.  The expected hard fork date:
- Mainnet-Bohr:     2024-09-26 02:20:00 AM UTC
There are 4 BEPs for Bohr hard fork:
- [BEP-341: Validators can produce consecutive blocks](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-341.md)
- [BEP-402: Complete missing fields in Block Header to generate Signature](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-402.md)
- [BEP-404: Clear Miner History when Switching Validators Set](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-404.md)
- [BEP-410: Add Agent for Validators](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-410.md)
* [\#2643](https://github.com/bnb-chain/bsc/pull/2643)core: fix cache for receipts
* …
> release: prepare for release v1.4.14

- CHANGELOG.md
- Makefile
- cmd/faucet/faucet.go
- cmd/geth/main.go
- core/blockchain.go
- core/forkchoice.go
- core/rawdb/prunedfreezer.go
- core/systemcontracts/upgrade.go
- core/systemcontracts/upgrade_test.go
- core/types/blob_sidecar.go
- eth/api_backend.go
- ethclient/ethclient.go
- go.mod
- go.sum
- internal/debug/flags.go
- internal/ethapi/api.go
- internal/ethapi/api_test.go
- internal/ethapi/backend.go
- internal/ethapi/transaction_args_test.go
- params/config.go
- params/version.go
Release v1.4.14 is a **hard fork release for BSC Mainnet**, the HF name is: [Bohr](https://forum.bnbchain.org/t/bnb-chain-roadmap-mainnet/936#p-1418-h-5bohr-wip-target-20240926-27), there are 4 BEPs in Bohr:
- [BEP-341: Validators can produce consecutive blocks](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-341.md)
- [BEP-402: Complete missing fields in Block Header to generate Signature](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-402.md)
- [BEP-404: Clear Miner History when Switching Validators Set](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-404.md)
- [BEP-410: Add Agent for Validators](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-410.md)
Among these BEPs, **BEP-341** holds the most significance as it proposes a change to the block production …
> Draft release v1.4.14

- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
- eth/handler.go
- eth/sync.go
Add some log to tack issue:https://github.com/bnb-chain/bsc/issues/2646
Dump peer name and its TD(total difficulty) could give some useful information
NA
NA
NA
> log: add some p2p log

- beacon/fakebeacon/api_func.go
- beacon/fakebeacon/handlers.go
- beacon/fakebeacon/server.go
- beacon/fakebeacon/server_test.go
- beacon/fakebeacon/utils.go
- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
We want to deploy a new chain like OP Mainnet/Testnet with OP-Stack for BSC Mainnet/Testnet, but OP-Stack uses some APIs of the beacon chain to fetch blobs' info. The problem is that our BSC doesn't have a chain like the beacon chain, and blobs on the BSC are associated with the transaction itself. 
[FakeBeacon]
Enable = true
Addr = "0.0.0.0"
Port = 8686
OR
geth  ....   
--fake-beacon 
--fake-beacon.addr="0.0.0.0" 
--fake-beacon.port=8686
* ...
> fakebeacon: a fake beacon api server for op-stack.

- cmd/geth/main.go
- eth/api_miner.go
Apply `Eth.Miner.GasCeil` to TxPool even the node did not enable `--mine` option. Otherwise, there could be accmulated pending transactions in txpool.
Take an example:
- Currently, BSC testnet's block gaslimit is 70M, as 20M gas is reserved for
SystemTxs, the maximum acceptable GasLimit for transaction is 50M.
- TxPool recevied a transaction with GasLimit 60M, it would be accepted in TxPool but it
will never be accepted by validators. Such kinds of transactions will be kept in txpool
and gradually make the txpool overflowed
Here is part of the TxPool status dumped from one mainnet p2p node(current mainnet block gaslimit 140M): transactions with GasLimit(133000000) will always in pending state and it also blocks its following transactions
```
{
pending: { …
```
> txpool: apply miner's gasceil to txpool

- cmd/faucet/faucet.go
In light of the recent surge in tBNB requests, we are considering implementing a mainnet minimum BNB balance check before granting tBNB to prevent abuse.
This practice is quite common in the Ethereum ecosystem, as seen with the [Alchemy Ethereum Faucet](https://www.alchemy.com/faucets/ethereum-sepolia) and the [Base Faucet](https://portal.cdp.coinbase.com/products/faucet). The proposed minimum balance will be set at 0.002 BNB, which is approximately $1, ensuring it remains affordable for users, such as students.
NA
NA
NA
> faucet: with mainnet balance check, 0.002BNB at least

- eth/sync.go
Add to the broadcasted "Current" block the Sidecars, when available.
The Sidecars were missing in this case, leading to invalid `NewBlockPacket` being propagated
> eth: Add sidecars when available to broadcasted current block

- cmd/geth/config.go
- cmd/utils/flags.go
- core/blockchain.go
metrics: add some extra feature flags in node info;
* metrics: add some extra feature flags in node info;
* ...
> metrics: add some extra feature flags as node stats;

- miner/miner.go
This PR tries to improve https://github.com/bnb-chain/bsc/pull/2680
If the node did not set `Eth.Miner` in config.toml, the default GasCeil will be 30000000, it is not an accurate number for both BSC mainnet and testnet. Set it to 0 means disable the transaction GasLimit check, i.e. the TxPool will accept transactions with any GasLimit size.
NA
NA
NA
> txpool: set default GasCeil from 30M to 0

- cmd/geth/chaincmd.go
- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- core/genesis.go
- core/systemcontracts/upgrade.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
- params/config.go
config: fix default value for PascalTime and add OverridePascal
* ...
> config: fix default value for PascalTime and add OverridePascal

- eth/protocols/eth/protocol.go
- miner/bid_simulator.go
- miner/worker.go
- params/protocol_params.go
miner: limit block size to eth protocol msg size
* ...
> miner: limit block size to eth protocol msg size

- consensus/parlia/parlia.go
consensus/parlia: wait more time when processing huge blocks
* ...
> consensus/parlia: wait more time when processing huge blocks

- crypto/bn256/cloudflare/gfp12.go
- crypto/bn256/cloudflare/gfp2.go
- crypto/bn256/cloudflare/gfp6.go
- crypto/bn256/google/gfp12.go
- crypto/bn256/google/gfp2.go
- crypto/bn256/google/gfp6.go
These codes appear to come from Go's crypto library, and upstream has fixed these comments
* ...
> chore: add missing symbols in comment

- CHANGELOG.md
- params/version.go
**v1.4.15** is a maintenance release, which mainly has some enhancement on P2P and TxPool module, it also provides some Restful API for L2 and support customized token on BSC faucet.
* [\#2680](https://github.com/bnb-chain/bsc/pull/2680) txpool: apply miner's gasceil to txpool
* [\#2688](https://github.com/bnb-chain/bsc/pull/2688) txpool: set default GasCeil from 30M to 0
* [\#2696](https://github.com/bnb-chain/bsc/pull/2696) miner: limit block size to eth protocol msg size
* [\#2684](https://github.com/bnb-chain/bsc/pull/2684) eth: Add sidecars when available to broadcasted current block
* [\#2672](https://github.com/bnb-chain/bsc/pull/2672) faucet: with mainnet balance check, 0.002BNB at least
* [\#2678](https://github.com/bnb-chain/bsc/pull/2678) beaconserver: simulated beacon api …
> release: prepare for release v1.4.15

- README.md
others changes, besides beacon chain:
- remove bsc-docker, as it is broken
- remove light client, as it is no longer supported
NA
NA
NA
> doc: update readme to remove Beacon chain part

- core/block_validator.go
- eth/handler.go
eth/handler: remove duplicate check for lists in body
in this PR(https://github.com/bnb-chain/bsc/pull/2461),
check for 3 lists `Uncles`, `Transactions`, `Withdrawals` is added.
but indeed, most of them are useless, because 
if block recieved by `handleBlockBodies`, 
`Uncles` and `Transactions` have been checked  at https://github.com/bnb-chain/bsc/blob/master/eth/fetcher/block_fetcher.go#L718
if block recieved by `handleNewBlock`
`Uncles` and `Transactions` have been checked at https://github.com/bnb-chain/bsc/blob/master/eth/protocols/eth/handlers.go#L316
so only add check for Withdrawals` is ok.
the check for `Transactions` cost not a little time when block is huge,
by removing the dupicate check, a better performance can be acheived
so this PR have 2 commits,
the first one is to …
> eth/handler: remove duplicate check for lists in body

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
upload-artifact and download-artifact must use same version, otherwise release workflow will fail.
https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md
* ...
> github: upgrade artifact from v3 to v4.1.7

- cmd/geth/chaincmd.go
- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- core/genesis.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
- params/config.go
feat: add Prague hardfork
* ...
> feat: add Prague hardfork

- consensus/parlia/parlia.go
Enhance the independence of distribute incoming tx. 
Don't need a temp value of balance between two system tx. To make exec one tx only need world state.
* concensus/parlia.go
> concensus/parlia.go: make distribute incoming tx more independence

- cmd/geth/main.go
- cmd/utils/flags.go
- core/block_validator.go
- core/blockchain.go
- core/blockchain_diff_test.go
- core/blockchain_reader.go
- core/blockchain_test.go
- core/error.go
- core/state/snapshot/difflayer.go
- core/state/snapshot/difflayer_test.go
- core/state/snapshot/disklayer.go
- core/state/snapshot/disklayer_test.go
- core/state/snapshot/iterator_test.go
- core/state/snapshot/journal.go
- core/state/snapshot/snapshot.go
- core/state/snapshot/snapshot_test.go
- core/state/statedb.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
- miner/worker.go
- triedb/hashdb/database.go
feat: remove pipecommit
`pipecommit` is brought in [[[R4R] implement State Verification && Snapshot Commit pipeline](https://github.com/bnb-chain/bsc/pull/668/files#top)](https://github.com/bnb-chain/bsc/pull/668) 
1. this feature is broken now
2. not easy to recover, and no plan to rework it
3. this feature changed some interfaces, make code upstream a bit more difficulty
* ...
> feat: remove pipecommit

- cmd/jsutils/getchainstatus.js
add a tool and some update
NA
NA
NA
> jsutils: add tool GetKeyParameters

- .nancy-ignore
This security issue is caused by mishandling the error code when paring JWT token. It is not an issue for BSC as BSC does not check the detail error code. Right now, would prefer to ignore this nancy warning against upgrade the JWT version as BSC would likely to upgrade it in the future.
NA
NA
NA
> nancy: ignore github.com/golang-jwt/jwt/v4 4.5.0 in .nancy-ignore

- cmd/pyutils/reorg_analyzer.py
Run this script to get stats of reorgs. Especially the validators responsible for it in some way. 
To understand reorgs. 
Example commands: (You can either given path to the directory which has all the .log files or just one .log file name)
`python reorg_analyzer.py /path/to/logs_directory`
or
`python reorg_analyzer.py bsc.log`
Example output is given at the end of the code.
> util: python script to get stats of reorg

- core/rawdb/chain_freezer.go
- eth/backend.go
When multi-database (multi-db) mode is enabled, the freezer's environment (env) is not properly set for the multi-db configuration. This prevents the multi-db chain_freezer from moving block data from the database (db) to the ancient storage (ancient).
* ...
> fix: fix multi-db env

- core/rawdb/database.go
Currently, in db inspect, blockBlobSidecars are treated as unaccounted data and not recognized properly.
Example error log:
`t=2024-11-21T08:48:10+0000 lvl=error msg="Database contains unaccounted data" size="3.16 GiB" count=90065`
This issue leads to incomplete or incorrect accounting for BlobSidecars during database inspection.
This PR updates the db inspect tool to include BlobSidecars in its statistical output, ensuring all database data is correctly accounted for.
* ...
> fix: add blobSidecars in db inspect

- core/txpool/legacypool/legacypool.go
- core/txpool/legacypool/legacypool_test.go
- core/txpool/legacypool/tx_overflowpool.go
- core/txpool/legacypool/tx_overflowpool_test.go
**Description**
This PR simplifies the logic by doing the checks regarding availability of slots in the Add() function of the OverflowPool rather than before where this logic was outside. 
This also addressed an edge case where if the OverflowPool is full, we simply take out one transaction and put the new one in. But this might result in the pool size exceeding its limit because the new transaction might have more slots than the older transaction. 
Also fix the bug: we were comparing number of transactions with number of slots here: 
`if uint64(len(tp.txHeap)) >= tp.maxSize`
Slots should be compared with slots. 
Added TestTxOverflowPoolSlotCalculation() to capture the bug in the previous code. 
The current change ensures we never exceed the set total size of the overflow pool.
> core/txpool: improve Add() logic, handle edge case

- triedb/pathdb/database.go
- triedb/pathdb/difflayer.go
- triedb/pathdb/difflayer_test.go
- triedb/pathdb/disklayer.go
- triedb/pathdb/layertree.go
- triedb/pathdb/metrics.go
- triedb/pathdb/reader.go
> chore: enable difflayer hashcache by resolved interface conflict

- core/rawdb/database.go
fix a issue in inspect blobsidecars
* After the modification, the inspect command now displays the count of BlobSidecars.
* The updated unaccounted data size is shown as follows:
`lvl=error msg="Database contains unaccounted data" size="922.00 B" count=18  `
* ...
> fix: add blobsidecar

- core/tracing/hooks.go
- eth/tracers/api.go
- eth/tracers/js/goja.go
- eth/tracers/logger/access_list_tracer.go
- eth/tracers/logger/logger.go
- eth/tracers/logger/logger_json.go
- eth/tracers/native/4byte.go
- eth/tracers/native/call.go
- eth/tracers/native/call_flat.go
- eth/tracers/native/mux.go
- eth/tracers/native/noop.go
- eth/tracers/native/prestate.go
eth/tracers: add onSystemTxEnd hook for system transaction gas used.
system transaction don't include intrinsic gas
* eth/tracers
> eth/tracers: add onSystemTxEnd hook for system tx gasused.

- CHANGELOG.md
- params/version.go
v1.4.16 is a maintenance release, which mainly include:
- Fix a multi-DB bug, which failed to prune historical data from main db after BSC support 4844
- Add the framework of BSC next hardfork: Pascal
- Systemcontract code cleanup, which will be enabled after Pascal hard fork
- Implement new feature: [overflowpool](https://github.com/bnb-chain/bsc/pull/2660), it tries to enhance the current TxPool to support large traffic.
-  Add some tool for trouble shoot, JSTool and PythonTool
NA
NA
NA
> release: prepare for release v1.4.16

- core/txpool/legacypool/legacypool_test.go
The TestTransferTransactions test expects the `TransferTransactions()` function to run in the background. But there isn't enough time for it to go through and the transaction to end up in the pending list. So a small waiting will ensure the async process finishes and the test becomes deterministic. 
* ...
> core: fix the transfer test and make deterministic

- core/blockchain.go
- core/state/statedb.go
core/state: revert the interface of StateDB.Commit
the param `postCommitFuncs` is used to work with pipecommit,
now the pipecommit feature is removed, so just delete it
* ...
> core/state: revert the interface of StateDB.Commit

- core/forkchoice.go
- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
- eth/downloader/modes.go
- eth/downloader/testchain_test.go
- eth/handler.go
eth, eth/downloader: remove references to LightChain, LightSync
lightclient is not supported in bsc now, so we can remove `LightChain` and `LightSync `
in geth, this has been done
https://github.com/ethereum/go-ethereum/pull/29711
* ...
> eth, eth/downloader: remove references to LightChain, LightSync

- consensus/parlia/parlia.go
- core/state/database.go
- core/state/statedb.go
- core/state/trie_prefetcher.go
core: fix snapshot update for fast node sync
make fast node work
I do fast node sync with node-deploy, it passes with this PR
* ...
> core: fix snapshot update for fast node sync

- cmd/utils/flags.go
- p2p/discover/node.go
- p2p/discover/table.go
- p2p/discover/table_reval.go
- p2p/discover/table_test.go
- p2p/discover/v5_udp.go
Reintroducing ENR filtering back. This allows discv4 ENR filtering and add small support for discv5 that could be enabled later on based on testing.
> p2p/discover: fix ENR filtering

- consensus/parlia/parlia.go
- core/chain_makers.go
- core/state_processor.go
- core/systemcontracts/upgrade.go
- core/systemcontracts/upgrade_test.go
- eth/state_accessor.go
- eth/tracers/api.go
- miner/worker.go
- params/config.go
[BEP-440: Implement EIP-2935: Serve historical block hashes from state](https://github.com/bnb-chain/BEPs/pull/440)
use node-deploy(bfc5db87b54db995ac06dd3b38d40a2a77bd89a8) to test
1. modify `bsc_cluster.sh`, then set up the cluster
2. cat log, if prague is enabled at `blockNumber=13`
get blockhash of `blockNumber=11`
```
curl http://127.0.0.1:8545/ --data '{
"jsonrpc": "2.0",
"id": 0,
"method": "eth_call",
"params": [ {
"to": "0x0aae40965e6800cd9b1f4b05ff21581047e3f91e",
"data": "0x000000000000000000000000000000000000000000000000000000000000000B"
}, "latest"]
}'  -H "Content-Type: application/json"  -X POST
```
get zero hash
```
{"jsonrpc":"2.0","id":0,"result":"0x0000000000000000000000000000000000000000000000000000000000000000"}
```
get blockhash of …
> BEP-440: Implement EIP-2935: Serve historical block hashes from state

- CHANGELOG.md
- params/version.go
v1.5.1-alpha is a maintenance release, which mainly include the code sync with upstream([Go-Ethereum](https://github.com/ethereum/go-ethereum)).It involves quite a lot of commits, will summary the change list below.
[eth: make transaction propagation paths in the network deterministic (#29034)](https://github.com/ethereum/go-ethereum/pull/29034)
[core/state: parallelise parts of state commit (#29681)](https://github.com/ethereum/go-ethereum/pull/29681)
Load trie nodes concurrently with trie updates, speeding up block import by 5-7% ([#29519](https://github.com/ethereum/go-ethereum/pull/29519), [#29768](https://github.com/ethereum/go-ethereum/pull/29768), [#29919](https://github.com/ethereum/go-ethereum/pull/29919)).
[core/vm: reject contract creation if the storage is non-empty …
> release: prepare for release v1.5.1-alpha

- CHANGELOG.md
- params/version.go
v1.5.1-alpha is a maintenance release, which mainly include the code sync with [Go-Ethereum [v1.13.15, v1.14.11]](https://github.com/ethereum/go-ethereum/releases).
As it involves quite a lot of commits, needs more effort and time to verify its quality, mark it as alpha release and would not recommend to use it in product environments.
[eth: make transaction propagation paths in the network deterministic (#29034)](https://github.com/ethereum/go-ethereum/pull/29034)
[core/state: parallelise parts of state commit (#29681)](https://github.com/ethereum/go-ethereum/pull/29681)
Load trie nodes concurrently with trie updates, speeding up block import by 5-7% ([#29519](https://github.com/ethereum/go-ethereum/pull/29519), [#29768](https://github.com/ethereum/go-ethereum/pull/29768), [#29919](https: …
> release: prepare for release v1.5.1-alpha (#2789)

- .github/workflows/build-test.yml
- core/types/gen_tx_opts_json.go
ci: do more test in build ci
do the following test in the build ci
```
check_tidy
check_generate
check_baddeps
```
if any one fails , the `Build Test` will fail
if some one forget to modify `gen_config.go` after modifying `eth/ethconfig/config.go`,
`Build Test` will fail now
if some one forget to do `go mod tidy` after change `go.mod`,
`Build Test` will also fail
* ...
> ci: check generate and tidy in 'Build Test' ci

- consensus/beacon/consensus.go
- consensus/clique/clique.go
- consensus/consensus.go
- consensus/ethash/consensus.go
- consensus/parlia/parlia.go
- core/block_validator.go
- core/blockchain_test.go
- core/chain_makers.go
- core/state_processor.go
- core/types/block.go
- eth/handler_test.go
- miner/worker.go
[BEP-466: Make the block header format compatible with EIP-7685](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-466.md)
* ...
> BEP-466: Make the block header format compatible with EIP-7685

- cmd/utils/flags.go
- core/rawdb/database.go
This PR fixes some pruneancient some issues, and it could improve UX;
* stats: support to parse pruneancient feature;
* pruneancient: force to full sync;
* freezer: fix pruned ancient checking;
> fix: Opt pruneancient issues;

- eth/fetcher/block_fetcher.go
- eth/fetcher/block_fetcher_test.go
- eth/handler.go
eth/fetcher: remove light mode in block fetcher
bsc no longer support light client any more, so remove light mode in block fetcher.
by the way, in go-ethereum client, `BlockFetcher` has been removed totally, 
so changes in this PR will not cause more conflicts when do upstream.
* ...
> eth/fetcher: remove light mode in block fetcher

- .gitignore
- core/state/access_list.go
- core/state/statedb_test.go
- eth/gasestimator/gasestimator.go
- eth/tracers/api.go
- eth/tracers/api_test.go
- graphql/graphql.go
- internal/ethapi/api.go
- internal/ethapi/api_test.go
- internal/ethapi/override/override.go
- internal/ethapi/override/override_test.go
- internal/ethapi/simulate.go
- internal/ethapi/simulate_test.go
- internal/ethapi/transaction_args.go
- internal/web3ext/web3ext.go
- p2p/dial.go
- p2p/dial_test.go
- p2p/enode/node.go
- p2p/enode/node_test.go
- p2p/enode/urlv4.go
- p2p/enode/urlv4_test.go
- p2p/peer.go
- p2p/peer_error.go
- p2p/peer_test.go
- p2p/transport.go
- p2p/transport_test.go
upstream: merge geth date 1213
prepare to merge commit 7702
* ...
> upstream: merge geth date 1213

- CHANGELOG.md
- version/version.go
v1.5.2-alpha is another maintenance release for upstream code sync, it catches up with [go-ethereum release [v1.14.12]](https://github.com/ethereum/go-ethereum/releases/tag/v1.14.12) and supported 4 BEPs for BSC Pascal hard fork.
- BEP-439: Implement EIP-2537: Precompile for BLS12-381 curve operations
- BEP-440: Implement EIP-2935: Serve historical block hashes from state
- BEP-441: Implement EIP-7702: Set EOA account code
- BEP-466: Make the block format compatible with EIP-7685
- [upstream: merge geth v1.14.12](https://github.com/bnb-chain/bsc/pull/2791)
- [upstream: merge geth date 1210](https://github.com/bnb-chain/bsc/pull/2799)
- [upstream: merge geth date 1213](https://github.com/bnb-chain/bsc/pull/2806)
- [BEP-441: Implement EIP-7702: Set EOA account …
> release: prepare for release v1.5.2-alpha

- ethdb/pebble/pebble.go
ethdb/pebble: roll back sync mode when write
introduced by ‘[core, ethdb/pebble: run pebble in non-sync mode](https://github.com/ethereum/go-ethereum/pull/30573)’
roll back it for now, it may be enabled after more tests by storage team in the future.
* ...
> ethdb/pebble: roll back sync mode when write

- core/blockchain.go
This PR changes some timer's type back to `NewRegisteredTimer`, it is more friendly for production scenarios.
* metric: rollback some metric timer types;
* ...
> metric: rollback some metric timer types;

- cmd/jsutils/getchainstatus.js
> jsutil: dump more about slash status

- cmd/geth/config.go
- cmd/utils/flags.go
- core/vote/vote_manager.go
- eth/backend.go
- metrics/exp/exp.go
- metrics/label.go
- metrics/prometheus/collector.go
metrics: fix Label type
type `Label` in metrics is only defined bsc,
after recently sync, the code of it is not compatible with other similar in metrics.
It lead to the info carried by the `lable` type is lost, this PR is to fix it.
* ...
> metrics: fix Label type

- core/txpool/legacypool/legacypool.go
core/txpool: accept SetCodeTxType transactions for test purpose
support SetCodeTxType txs in pool is [not done ](https://github.com/ethereum/go-ethereum/pull/30949)
for testing, we follow [prague-devnet-4](https://github.com/ethereum/go-ethereum/compare/master...lightclient:go-ethereum:prague-devnet-4#diff-3b03ebf997a1699ce8e84a53a4b3981e403e74e2f90128eb188ad4226703970c): add it into legacypool for simplicity.
* ...
> core/txpool: accept SetCodeTxType transactions for test purpose

- core/txpool/legacypool/legacypool.go
core/txpool: reject SetCodeTxType txs before prague
the release version may replace some nodes of mainnet and chapel net,
we should reject SetCodeTxType txs before prague
* ...
> core/txpool: reject SetCodeTxType txs before prague

- eth/backend.go
eth: override chainconfig before create engine for testing
when create parlia engine, the signer will depend on the hardfork settings,
so override them before create engine
```
func LatestSigner(config *params.ChainConfig) Signer {
var signer Signer
if config.ChainID != nil {
switch {
case config.PragueTime != nil:
signer = NewPragueSigner(config.ChainID)
case config.CancunTime != nil:
signer = NewCancunSigner(config.ChainID)
case config.LondonBlock != nil:
signer = NewLondonSigner(config.ChainID)
case config.BerlinBlock != nil:
signer = NewEIP2930Signer(config.ChainID)
case config.EIP155Block != nil:
signer = NewEIP155Signer(config.ChainID)
default:
signer = HomesteadSigner{}
}
} else {
signer = HomesteadSigner{}
}
return signer
}
```
Notable …
> eth: override chainconfig before create engine for testing

- core/blockchain.go
- triedb/pathdb/buffer.go
- triedb/pathdb/journal.go
This PR fixes a legacy journal format issue, it tries to load an async buffer in a legacy journal file.
When the PR is enabled, the node can read the async buffer correctly.
```bash
logs/bsc.log.2024-12-20_11:t=2024-12-20T11:15:10+0000 lvl=info msg="New async node buffer" limit="256.00 MiB" layers=44221
logs/bsc.log.2024-12-20_12:t=2024-12-20T12:15:37+0000 lvl=info msg="Failed to load journal, discard it" err="unexpected journal version want 2 got 0"
```
It will fix the issue https://github.com/bnb-chain/bsc/issues/2796.
* pbss: support to load legacy async buffer format;
* ...
> pbss: support to load legacy async buffer format

- triedb/pathdb/asyncnodebuffer.go
- triedb/pathdb/disklayer.go
triedb/pathdb: fix copyNodeCache for asyncnodebuffer
* ...
>  triedb/pathdb: fix copyNodeCache for asyncnodebuffer

- triedb/pathdb/journal.go
triedb/pathdb: fix nil field for stateSet
fix the issue [The Node panic by assignment to entry in nil map](https://github.com/bnb-chain/bsc/issues/2826)
decoding `stateSet` may be skipped, leading to nil field.
* ...
> triedb/pathdb: fix nil field for stateSet

- core/blockchain.go
- core/blockchain_reader.go
- core/state/snapshot/journal.go
This PR tries to solve issue https://github.com/bnb-chain/bsc/issues/2829, the fast node reports `Failed to journal in-memory trie nodes` when stopping the node, reports `Head state missing, repairing` when restarting the node.
* fastnode: fix some pbss saving&rewind issues;
> fastnode: fix some pbss saving&rewind issues;

- eth/backend.go
- eth/handler.go
- eth/handler_eth.go
- eth/handler_eth_test.go
- eth/sync.go
fix https://github.com/bnb-chain/bsc/issues/2783
* ...
> eth: make transaction acceptance depends on syncing status

- ethclient/ethclient.go
- internal/ethapi/api.go
internal/ethapi: support GetFinalizedBlock by common ratio validators
the number of validators may change in one network,
and the number may be different in different networks.
but the user want to use the api `GetFinalizedBlock` at some fixed ratio of validators, such as opBNB.
* ...
> internal/ethapi: support GetFinalizedBlock by common ratio validators

- consensus/consensus.go
- consensus/parlia/parlia.go
- consensus/parlia/snapshot.go
- eth/backend.go
- miner/miner.go
- miner/minerconfig/config.go
- miner/worker.go
The PR aims to avoid validator being slashed when restarting the node, the node will propose multi blocks after enabling the https://github.com/bnb-chain/bsc/pull/2482.
So the PR will wait for the multi-block proposals to be done to avoid the slashing when restarting, and the node will wait `MaxWaitProposalInSecs`.
The default value of `MaxWaitProposalInSecs` is set to 30 seconds.   Because the average restart time in mainnet is around 30s, so the node try to wait for the next multi-proposals to be done.
> Attention: if you maintain the node with `systemd`, pls set `TimeoutStopSpec` >= 60s, it will allow the node shutdown safely when enabling the `MaxWaitProposalInSecs` > 0.
* feat: wait miner finish the later multi-proposals when restarting the node;
* ...
> feat: wait miner finish the later multi-proposals when restarting the node;

- consensus/beacon/consensus.go
- consensus/clique/clique.go
- consensus/consensus.go
- consensus/ethash/consensus.go
- consensus/parlia/feynmanfork.go
- consensus/parlia/parlia.go
- consensus/parlia/parlia_test.go
- core/blockchain_test.go
- core/chain_makers.go
- core/state_processor.go
- core/tracing/hooks.go
- eth/handler_test.go
- eth/tracers/api.go
- eth/tracers/logger/logger.go
- eth/tracers/native/call.go
- eth/tracers/native/call_flat.go
- eth/tracers/native/mux.go
- eth/tracers/native/noop.go
- miner/worker.go
See #2768 for context and details.
This introduced `OnSystemTxStart/OnSystemTxEnd` and renamed `OnSystemTxEnd` to `OnSystemTxFixIntrinsicGas` (so `OnSystemTxEnd` can be re-used for other purposes).
The Parlia engine is now tracing it's system transaction properly which was not the case before.
This PR ensure that system transactions are properly tested when using live tracers.
Consensus engine is now receiving a `tracer *tracing.Hooks` that Parlia engine then uses when needing to apply system transactions.
> Push tracing of Parlia system transactions so that live tracers can properly traces those state changes

- CHANGELOG.md
- core/tracing/gen_balance_change_reason_stringer.go
- version/version.go
**v1.5.3-beta** is a maintenance release, which mainly include a few bug fixes, dependency update and some improvements of node shutdown, tracing API...
* [\#2827](https://github.com/bnb-chain/bsc/pull/2827) triedb/pathdb: fix nil field for stateSet
* [\#2830](https://github.com/bnb-chain/bsc/pull/2830) fastnode: fix some pbss saving&rewind issues
* [\#2835](https://github.com/bnb-chain/bsc/pull/2835) dep: fix nancy issues
* [\#2836](https://github.com/bnb-chain/bsc/pull/2836) Revert "internal/ethapi: remove td field from block (#30386)"
NA
* [\#2834](https://github.com/bnb-chain/bsc/pull/2834) eth: make transaction acceptance depends on syncing status
* [\#2844](https://github.com/bnb-chain/bsc/pull/2844) internal/ethapi: support GetFinalizedBlock by common ratio validators
* …
> release: prepare for release v1.5.3-beta

- consensus/parlia/feynmanfork.go
- consensus/parlia/parlia.go
- consensus/parlia/parlia_test.go
Passing `*tracing.Hooks` makes the intent clearer and ensure the `applyTransaction` controls the creation of the `vm.Config`.
Follow-up of https://github.com/bnb-chain/bsc/pull/2772.
https://github.com/bnb-chain/bsc/pull/2772#discussion_r1905052594.
> tracing: pass `*tracing.Hooks` around instead of `vm.Config`

- eth/tracers/native/call_flat.go
- eth/tracers/native/mux.go
- eth/tracers/native/noop.go
eth/tracers: fix call nil OnSystemTxFixIntrinsicGas
1. FlatCallTracer.OnSystemTxFixIntrinsicGas=CallTracer.OnSystemTxFixIntrinsicGas
2. ensure OnSystemTxFixIntrinsicGas not equal to nil before call it
3. remove useless empty func `OnSystemTxFixIntrinsicGas` in noopTracer
* ...
> eth/tracers: fix call nil OnSystemTxFixIntrinsicGas

- cmd/jsutils/getchainstatus.js
add a tool to analyze Eip-7623 affect, query gasused change after EIP-7623
* cmd/jsutils/getchainstatus.js: add getEip7736
> cmd/jsutils/getchainstatus.js: add GetEip7623

- CHANGELOG.md
- cmd/jsutils/getchainstatus.js
- version/version.go
It is a hard fork release to support BSC Pascal on BSC testnet, which includes 5 BEPs:
- [BEP-439: Implement EIP-2537: Precompile for BLS12-381 curve operations](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-439.md)
- [BEP-440: Implement EIP-2935: Serve historical block hashes from state](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-440.md)
- [BEP-441: Implement EIP-7702: Set EOA account code](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-441.md)
- [BEP-466: Make the block format compatible with EIP-7685](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-466.md)
- [ BEP-496: Implement EIP-7623: Increase calldata cost](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-496.md)
Most of these BEPs are compatible with Ethereum Praque hard fork. The …
> release: prepare for release v1.5.5

- triedb/pathdb/database_test.go
Fix `TestDisable` UT failure.
Trie uses `bytesPool` to improve updateTrie performance to avoid extra memory allocation. However, PBSS uses asyncnodebuffer to store data which is a async operation. So `TestDisable` UT cannot pass due to the data in PBSS is async mode and in UT use force flush.
N/A
* N/A
> fix: fix pbss async node buffer force flush buffer

- core/txpool/legacypool/legacypool_test.go
core/txpool/legacypool: fix TestTransactionPendingReannouce
* ...
> core/txpool/legacypool: fix TestTransactionPendingReannouce

- tests/run-evm-tests.sh
tests: fix evm tests CI
when run `run-evm-tests.sh` locally, there are 518641 cases are run
but in CI `https://github.com/bnb-chain/bsc/actions/runs/13255495909/job/37001551107`
even it shows that it succeed, but only 212204 case are run 
the reason is that a timeout is trigged
in this PR, the flag `short` is added following to `geth`, 
for one json test file, one of the four modes `[path/snap, path/trie, hash/snap, hash/trie]` will be selected randomly.
```
if testing.Short() {
snapshotConf = []bool{snapshotConf[rand.Int()%2]}
dbschemeConf = []string{dbschemeConf[rand.Int()%2]}
}
```
* ...
> tests: fix evm tests CI

- CHANGELOG.md
- cmd/jsutils/getchainstatus.js
- params/config.go
- version/version.go
It is a hard fork release to support BSC Pascal on BSC testnet, hard fork date will be: `2025-02-20 03:18:00 AM UTC`, pls upgrade your testnet node to v1.5.6 before the hard fork time.
Pascal hard fork includes 5 BEPs:
- [BEP-439: Implement EIP-2537: Precompile for BLS12-381 curve operations](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-439.md)
- [BEP-440: Implement EIP-2935: Serve historical block hashes from state](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-440.md)
- [BEP-441: Implement EIP-7702: Set EOA account code](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-441.md)
- [BEP-466: Make the block format compatible with EIP-7685](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-466.md)
- [ BEP-496: Implement EIP-7623: Increase calldata …
> release: prepare for release v1.5.6

- params/config.go
update Testet Pascal&Praque hard fork date to 2025-02-25 03:08:00 AM UTC
* ...
> config: update BSC Testnet hardfork date: Pascal & Praque

- cmd/jsutils/getchainstatus.js
> tool: update jsutils tool

- consensus/parlia/parlia.go
consensus/parlia: improve performance of func IsSystemTransaction
when use v1.5.x to do benchmark before prague hardfork, strange things happen: the performance downgrades a lot.
Reason is that, when importing a block, for every txs, need to apply func `IsSystemTransaction`.
In func `IsSystemTransaction`, use `p.signer` which is a `pragueSigner`,
but when getting `Sender` for txs, use signer `cancunSigner`,
different type of signers lead to cache missing.
so in this PR, avoid to get sender in `IsSystemTransaction` when possible.
* ...
> consensus/parlia: improve performance of func IsSystemTransaction

- miner/worker.go
miner: avoid to collect requests when getting pending blocks
now `requestsHash` is the `EmptyRequestsHash`
* ...
> miner: avoid to collect requests when getting pending blocks

- core/vm/contracts_test.go
- core/vm/testdata/precompiles/blsSignatureVerify.json
- core/vm/testdata/precompiles/fail-blsSignatureVerify.json
core/vm: add basic test cases for blsSignatureVerify
add basic test cases for blsSignatureVerify, to find issue early when update bls libs
* ...
> core/vm: add basic test cases for blsSignatureVerify

- core/txpool/legacypool/legacypool.go
If we're reorging an old state, reinject all dropped transactions, there are MEV transaction have zero gas price. They should not add to the txpool.
* ...
> core/txpool/legacypool/legacypool.go: add gasTip check when reset

- cmd/geth/chaincmd.go
- cmd/utils/flags.go
- node/config.go
- node/defaults.go
- node/node.go
- vdn/config.go
- vdn/connection_gater.go
- vdn/crypto.go
- vdn/gossip_scoring_params.go
- vdn/pubsub.go
- vdn/server.go
vdn: support init network, add event loop;
* vdn: support init network, add event loop;
* ...
> vdn: support init network, add event loop;

- miner/worker.go
miner: fix commitWork not interrupted properly
a validator is mining block `N`, but not in turn.
an in turn block with Number `N` arrived, so a chainHeadCh event trigged.
but this validator is not allowed to mine block `N+1`,
in this senario, the `commitwork` for Number `N` will not be interrupted properly!
* ...
> miner: fix commitWork not interrupted properly

- core/txpool/errors.go
- core/txpool/legacypool/legacypool.go
- core/txpool/legacypool/legacypool_test.go
- core/txpool/validation.go
- core/types/transaction.go
- eth/gasprice/feehistory.go
- signer/core/apitypes/types.go
- signer/core/signed_data_test.go
upstream: pick bug fix from latest geth
* ...
> upstream: pick bug fix from latest geth

- params/config.go
Expected BSC Mainnet Pascal&Praque hard fork date will be: `2025-03-20 02:10:00 AM UTC`
NA
NA
NA
> config: update BSC Mainnet hardfork date: Pascal & Praque

- CHANGELOG.md
- version/version.go
v1.5.7 is for BSC mainnet [Pascal hard fork](https://forum.bnbchain.org/t/bnb-chain-roadmap-mainnet/936#p-1418-h-1pascal-wip-8), which will be enabled at: `2025-03-20 02:10:00 AM UTC`, all BSC mainnet nodes need to upgrade to v1.5.7 before the hard fork time. For this upgrade, simply binary replacement should be enough.
Besides hard fork, v1.5.7 also include one bugfix and some improvements:
- 1.fix the windows binary release, which is caused by a mismatched dependency.
- 2.increase the efficient GasLimit by reducing the gas reserved for systemTx, after v1.5.7 blocks can almost reach 140M GasLimit target now(previously it was 120M), which would increase the network throughput.
- 3.performance improvement by removing unnecessary signer recover code.
- 4.update the TxPool gastip check …
> release: prepare for release v1.5.7

- common/format.go
- core/blockchain.go
- core/blockchain_reader.go
- core/vote/vote_manager.go
- core/vote/vote_pool.go
- eth/backend.go
- eth/handler_eth.go
- miner/worker.go
- p2p/peer.go
This PR will add more metrics for later shorter block interval. It can monitor the block/vote delay between validators, it help to monitor the validator network, and optimizes the p2p msg forward efficient.
Here are some metrics examples, it can help to optimize the network and find msg broadcast issues.
* metrics: add some block/vote metrics;
* ...
> metrics: add more block/vote stats;

- miner/minerconfig/config.go
- rpc/handler.go
"GreedyMergeTx" was introduced previously by https://github.com/bnb-chain/bsc/pull/2363/ to maximum the validator's reward and also increase the block space utilization rate.
It should be enabled by default, as it is a desired feature for validators.
And also clear up a duplicated log message.
> Notice: pls ignore the nancy check failure, as it will be fixed in https://github.com/bnb-chain/bsc/pull/2951
NA
NA
> pbs: enable GreedyMergeTx by default

- miner/bid_simulator.go
This PR only change the misleading log, like:
```
t=2025-03-11T11:17:47+0000 lvl=info msg="[BID ARRIVED]" ...
...
t=2025-03-11T11:17:48+0000 lvl=info msg="Successfully sealed new block"...
t=2025-03-11T11:17:48+0000 lvl=info msg="[BID RESULT]" win=true[first]...
```
Sometimes "bestBid == nil" does not mean it is the first bid, if new block was just imported during the bid simulation, the bestBid will be cleared as well. In this case, the bid is stale and useless.
Keep the SetBestBid right now, as it will be cleared later anyway. Once we have more confidence, it can be removed
NA
NA
NA
> pbs: fix an inaccurate bid result log

- core/txpool/legacypool/tx_overflowpool.go
Addresses https://github.com/bnb-chain/bsc/issues/2945 
No need to warn when overflowpool is full. It can be a debug log only. 
* ...
> pool: debug log instead of warn

- miner/bid_simulator.go
- miner/worker.go
miner: stop GreedyMergeTx before worker picking bids
* ...
> miner: stop GreedyMergeTx before worker picking bids

- core/blockchain.go
- eth/backend.go
This PR will add new metrics about block txsize, gasused. It can help to monitor the traffic of the chain.
Add new metrics:
```bash
chain_insert_txsize{job=~"$jobs"}
chain_insert_gasused{job=~"$jobs"}
```
* metric: add more block monitor metrics;
* ...
> metric: add more block monitor metrics;

- core/types/bid.go
- miner/bid_simulator.go
This is an improvement to the current MEV logic, especially on large traffic to avoid too frequent bid interrupt that could lead to no bid can be simulated.
with 3s block interval, if there is a simulating bid and with a short time left for simulate, then don't interrupt the current simulating bid. The new bid will be pending and can still run once the current simulating bid completes
NA
NA
NA
> mev: no interrupt if it is too later

- miner/worker.go
miner: add metrics for bid simulation
* ...
> miner: add metrics for bid simulation

- CHANGELOG.md
- version/version.go
> notice: v1.5.8 is for validator only, other full nodes can ignore this version.
v1.5.8 is a maintenance release for BSC mainnet validators to improve the current the PBS(MEV) mechanism.
Here are key points of this release:
- enabled GreedyMergeTx by default
- fix a critical error on GasUsed check: bids with full GasUsed was marked as invalid by mistake
- improvement: add a stop timer, so the last simulating bid would have more chance to be selected
- improvement: do not interrupt the simulating if new bid was arrived too later.
* [\#2955](https://github.com/bnb-chain/bsc/pull/2955) pbs: enable GreedyMergeTx by default
* [\#2967](https://github.com/bnb-chain/bsc/pull/2967) fix: gas compare in bid simulator
* [\#2951](https://github.com/bnb-chain/bsc/pull/2951) bump golang.org/x/net from …
> release: prepare for release v1.5.8

- core/types/bid.go
- core/vote/vote_pool.go
- miner/bid_simulator.go
- miner/miner_mev.go
- miner/minerconfig/config.go
1.update some log
2.to address latest comments from: https://github.com/bnb-chain/bsc/pull/2971/files
there will be a new option in config.toml:
```
[Eth.Miner.Mev]
NoInterruptLeftOver = 400000000
```
by default it will be 400ms
NA
NA
NA
> mev: some code improvements

- core/txpool/blobpool/blobpool_test.go
- core/types/tx_setcode.go
remove redundant words in comment
* ...
> chore: remove redundant words in comment

- core/state/statedb.go
core/state: fix concurrent map read and write for stateUpdate.accounts
[v1.5.7 crashed via log](https://github.com/bnb-chain/bsc/issues/2981)
read path is as shown in the above picture
write path:
```
commitAndFlush
-->err := snap.Cap(ret.root, snap.CapLimit())
-->persisted := t.cap(diff, layers)
-->flattened := parent.flatten().(*diffLayer)
-->	for hash, data := range dl.accountData {
parent.accountData[hash] = data
}
```
* ...
> core/state: fix concurrent map read and write for stateUpdate.accounts

- CHANGELOG.md
- build/ci.go
- core/rawdb/freezer.go
- version/version.go
v1.5.9 is for BSC Testnet [Lorentz hard fork](https://forum.bnbchain.org/t/bnb-chain-upgrades-testnet/934#p-1416-h-2lorentz-wip-3), which is expected to be enabled at: `2025-04-08 07:33:00 AM UTC`, all BSC testnet nodes need to upgrade to v1.5.9 before the hard fork time. For this upgrade, simply binary replacement should be enough.
Besides hard fork setup, v1.5.9 also include one bugfix and some improvements, pls check the change log for detail.
[\#2932](https://github.com/bnb-chain/bsc/pull/2932) BEP-520: Short Block Interval Phase One: 1.5 seconds
[\#2991](https://github.com/bnb-chain/bsc/pull/2991) config: update BSC Testnet hardfork time: Lorentz
[\#2990](https://github.com/bnb-chain/bsc/pull/2990) core/state: fix concurrent map read and write for stateUpdate.accounts …
> release: prepare for release v1.5.9

- p2p/nat/stun_test.go
p2p/nat: remove test with default servers (#31225)
pick from go-etherreum https://github.com/ethereum/go-ethereum/pull/31225
* ...
> p2p/nat: remove test with default servers (#31225)

- miner/bid_simulator.go
- miner/minerconfig/config.go
mev: make max bids per builder per block configurable
when block interval reduced to 1.5s, 
may limit  max bids per builder to 2 from 3,
before do that, make it configurable is better.
* ...
> mev: make max bids per builder per block configurable

- cmd/jsutils/.prettierrc
- cmd/jsutils/getchainstatus.js
- cmd/jsutils/package.json
- core/rawdb/chain_freezer.go
- core/txpool/blobpool/priority.go
- core/vm/memory_table.go
- eth/protocols/bsc/peer.go
- internal/ethapi/api.go
- internal/web3ext/web3ext.go
- miner/bid_simulator.go
- miner/minerconfig/config.go
- p2p/nat/stun_test.go
merge several non-critical commit into master branch for next release v1.5.9
NA
NA
NA
> Merge: from develop to master branch for v1.5.9

- cmd/jsutils/getchainstatus.js
cmd/jsutils: add more builders
according to https://github.com/bnb-chain/bsc-mev-info/tree/main/testnet/builders
instead of https://github.com/bnb-chain/good-will-alliance/tree/main/mev-info
* ...
> cmd/jsutils: add more builders

- params/config.go
Expected Mainnet Lorentz hard fork time: 2025-04-29 05:05:00 AM UTC
NA
NA
NA
> config: update BSC Mainnet hardfork time: Lorentz

- metrics/exp/exp.go
- metrics/label.go
- metrics/prometheus/collector.go
metrics: fix panic for cocurrently accessing label
metrics.Label is only defined in bsc, a panic was found for it
* ...
> metrics: fix panic for cocurrently accessing label

- .nancy-ignore
- add nancy ignore: golang/golang.org/x/net@v0.36.0, it is indirectly included by devp2p can bd upgraded in the future with devp2p
- remove several fixed nancy vulnerabilities: jwt, go-retryablehttp, golang.org/x/net v0.29
NA
NA
NA
> nancy: update nancy ignore

- cmd/geth/config.go
- cmd/utils/flags.go
- eth/ethconfig/config.go
- miner/bid_simulator.go
- miner/miner.go
- miner/miner_mev.go
- miner/minerconfig/config.go
- miner/worker.go
apply the default value of these elemnents, mainly for MEV:
```
[Eth.Miner]
DelayLeftOver=50000000
[Eth.Miner.Mev]
GreedyMergeTx = true
ValidatorCommission = 100
BidSimulationLeftOver = 50000000
NoInterruptLeftOver = 400000000
MaxBidsPerBuilder = 3
```
This is part of the original PR:https://github.com/bnb-chain/bsc/pull/2987/, in this PR, we only address the 6 elements listed above for simplicity.
As the gentool does not support recursive element, refer: https://github.com/bnb-chain/bsc/pull/3024
We have to support it manually.
NA
NA
> config.toml: default value of [Eth.Miner] and [Eth.Miner.Mev]

- core/types/bid.go
- miner/miner_mev.go
Notice: this will change the return value of miner API: miner.MevParams()
NA
NA
NA
> mev: include MaxBidsPerBuilder in MevParams

- CHANGELOG.md
- version/version.go
v1.5.11 is a maintenance release, mainly to support PBS(MEV) after BSC activate [BEP-520: shorter block interval phase one: 1.5 seconds](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-520.md) after Lorentz hard fork. PBS(MEV) is quite sensitive to the block timing, to make it more stable under 1.5 seconds block interval, it is necessary to update several MEV parameters.
v1.5.11 updates the two MEV parameters:
- defaultMaxBidsPerBuilder from 3 to 2
- defaultNoInterruptLeftOver  from 400ms to 250
equal to config.toml:
```
[Eth.Miner.Mev]
MaxBidsPerBuilder = 2
NoInterruptLeftOver = 250000000
```
For this upgrade, simply binary replacement should be enough.
[\#3008](https://github.com/bnb-chain/bsc/pull/3008) params: add MaxwellTime
[\#3025](https://github.com/bnb-chain/bsc/pull/3025) …
> release: prepare for release v1.5.11

- core/blockchain.go
- core/headerchain.go
- miner/bid_simulator.go
miner: optimize clear up logic for envs
In `bid_simulator.go`, the `bid.discard` function conflicts with `worker.commit()`, resulting in a panic.  
Specifically:
- At line 304, `s.db.prefetcher` is not `nil`.
- But at line 305, it suddenly becomes `nil`, causing a panic.
This happens due to concurrent modification of `s.db.prefetcher`.
Based on code analysis, this issue only occurs when a miner selects a bid as the final work to commit. There are two scenarios where this can happen *after* the worker calls `GetBestBid`:
- (a) `bidSimulator.SetBestBid` is invoked, or  
- (b) a new `chainHead` event is received, triggering `clearFn` in `bidSimulator.clearLoop`.
This PR resolves the issue by **delaying the discard action** to avoid the race condition.
---
Previously, environment discards …
> miner: optimize clear up logic for envs

- README.md
- rpc/json-rpc-api.md
Add a rpc doc to list all support rpc lists. 
* rpc: add json-rpc-api.md
* ...
> feat: add json-rpc-api.md 

- params/network_params.go
params: double FullImmutabilityThreshold for BEP-520 & BEP-524
`FullImmutabilityThreshold` is now applied to block freezing, block pruning, and state history.
When the block interval is reduced, the default value of `FullImmutabilityThreshold` is increased accordingly to ensure consistent behavior.
this PR will solve issue https://github.com/bnb-chain/bsc/issues/3042
**Note:**  
The `TransactionHistory` threshold remains unchanged. Its original default value is `2,350,000`, which is sufficiently large even with a shorter block interval.  
If a node requires transaction indexing over a larger number of blocks, please use the `history.transactions` flag to configure it explicitly.
* ...
> params: double FullImmutabilityThreshold for BEP-520 & BEP-524

- rpc/json-rpc-api.md
rpc/json-rpc-api.md: add eth_simulateV1 
* ...
> rpc/json-rpc-api.md: add eth_simulateV1 

- core/blockchain_test.go
- core/state_processor_test.go
- ethclient/ethclient.go
- ethclient/gethclient/gethclient.go
- interfaces.go
- internal/ethapi/api_test.go
This PR adds the `AuthorizationList` field to the `CallMsg` interface to support `eth_call` and `eth_estimateGas` of set-code transactions.
picked from go-ethereum [31198](https://github.com/ethereum/go-ethereum/pull/31198)
[issue 3047](https://github.com/bnb-chain/bsc/issues/3047) solved
* ...
> ethclient: allow passing AuthorizationList to calls (#31198)

- eth/backend.go
- eth/downloader/downloader.go
- eth/fetcher/block_fetcher.go
- eth/fetcher/block_fetcher_test.go
- eth/handler.go
- eth/handler_eth.go
- eth/protocols/bsc/dispatcher.go
- eth/protocols/bsc/handler.go
- eth/protocols/bsc/handler_test.go
- eth/protocols/bsc/peer.go
- eth/protocols/bsc/protocol.go
- node/config.go
This PR will implement https://github.com/bnb-chain/BEPs/pull/564.
It supports fast fetching of newly generated blocks, avoids validators and full nodes from lagging behind in the subsecond block interval, and especially improves the validator consensus efficiency, which can produce the next block or send vote faster.
If you want to use new block fetching mechanism, you need modify the config:
```toml
[Node]
EnableQuickBlockFetching = true
```
* bsc: add BlocksByRange msgs;
* block_fetcher: support quick block fetching;
> bsc: add new block fetching mechanism;

- ethclient/gethclient/gethclient.go
- ethclient/gethclient/gethclient_test.go
ethclient/gethclient: add deduplication and max keys limit to GetProof
- Add deduplication of storage keys in GetProof to avoid redundant proofs
- Add MaxGetProofKeys constant (512) to limit the number of keys
- Add validation to reject requests with more than 512 keys
- Add tests for deduplication and max keys limit functionality
> ethclient/gethclient: add deduplication and max keys limit to GetProof

- node/api.go
- node/config.go
- node/node.go
- node/rpcstack.go
- rpc/client_test.go
- rpc/handler.go
- rpc/json.go
- rpc/websocket.go
- rpc/websocket_test.go
This PR introduces two important improvements to the RPC system:
1. Method Name Length Limit
- Adds a limit of 256 characters for RPC method names to prevent potential abuse
- Prevents large method names from leading to excessive response sizes
- Limit is enforced in:
* handleCall for regular RPC method calls
* handleSubscribe for subscription method calls
- Added tests in websocket_test.go to verify the length limit functionality
2. Configurable WebSocket Message Size Limit
- Adds support for configuring message size limits on both client and server sides
- Previously, server side used a fixed default limit while client side supported configurable limits
- Changes include:
* Modified WebsocketHandler to accept a messageSizeLimit parameter
* Added messageSizeLimit field to wsConfig struct …
> rpc: add method name length limit and configurable message size limit

- CHANGELOG.md
- version/version.go
v1.5.12 was a hotfix release on a separate branch, based on v1.5.11, see: https://github.com/bnb-chain/bsc/pull/3058
merge the v1.5.12 change log to develop branch.
NA
NA
NA
> release: prepare for release v1.5.12

- consensus/parlia/stakehub.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
This PR adds support for removing node IDs from the StakeHub contract, complementing the existing node ID registration functionality. The changes include both the contract interaction layer and the configuration management.
1. Added `RemoveNodeIDs` function to Parlia consensus engine
- Creates and signs transactions to remove node IDs from StakeHub
- Handles gas estimation and transaction creation
- Includes proper error handling and logging
2. Refactored node ID management in Ethereum backend
- Split `registerNodeID` into `handleRemovals` and `handleAdditions`
- Added support for wildcard removal (removing all node IDs)
- Improved efficiency with map-based lookups
- Added deduplication logic to prevent redundant operations
3. Updated configuration
- Renamed `ValidatorNodeIDsToAdd` to …
> evn: add support for node id removal

- cmd/geth/chaincmd.go
- cmd/utils/flags.go
- eth/handler.go
This PR supports more scenarios for local/QA testing, it can create fullnode, enable more EVN features for testing, and refactor some code.
```bash
./bin/geth init-network -h                              
NAME:
geth init-network - Bootstrap and initialize a new genesis block, and nodekey, config files for network nodes
USAGE:
geth init-network [command options] <genesisPath>
CATEGORY:
BLOCKCHAIN COMMANDS
DESCRIPTION:
The init-network command initializes a new genesis block, definition for the network, config files for network nodes.
It expects the genesis file as argument.
OPTIONS:
--init.dir value                                                      
the direction to store initial network data
--init.evn-sentry-register          (default: false)                  
whether to add evn …
```
> chore: support more evn configuration in tool;

- cmd/utils/flags.go
- cmd/utils/flags_legacy.go
- miner/minerconfig/config.go
- miner/worker.go
- miner/worker_test.go
**1.Apply default value for `Recommit` and `MaxWaitProposalInSecs`**
```
[Eth.Miner]
GasCeil = 70000000
GasPrice = 100000000
VoteEnable = true
```
with this configuration, `Eth.Miner.Recommit` & `Eth.Miner.MaxWaitProposalInSecs` will be 0, while their default value should be 3000000000 and 30 respectively.
This PR it to fix the default value issue of these 2 options.
**2.Change the default value of the two options.**
It would be more reasonable to change default value these 2 options:
- Recommit: from 3000000000(3 seconds) to 10000000000(10 seconds)
Notice: `Recommit` is a experimental value, it could be removed, but leave it for now as it has not big side effect.
- MaxWaitProposalInSecs: from 30s to 45s
Node restart could take ~40second
Here if one of the restart log from a BSC full …
> config: apply two default miner option

- core/state_processor.go
Large tx could be one of the performance bottleneck, add log to track txs with GasUsed > 10M
log will be like:
```
t=2025-05-12T00:50:47+0000 lvl=info msg="LargeTX execution time" block=49511908 tx=0x47561786e7e5799af82bce56ac49ce6448fe7e24fdc7b185b6ebe3d5f3a11a12 gasUsed=10823496 elapsed=38.719084ms
t=2025-05-12T00:51:17+0000 lvl=info msg="LargeTX execution time" block=49511928 tx=0xa59a28c7be3198184308fc7001f7d0704899be81554fea01b3094b16bbac83b3 gasUsed=11245831 elapsed=45.162283ms
t=2025-05-12T01:00:06+0000 lvl=info msg="LargeTX execution time" block=49512281 tx=0xdabb2a40304787bfce1b61c4235b95734996c25d5d0a1e9a473a09a749e05310 gasUsed=16727624 elapsed=140.572166ms
t=2025-05-12T01:04:35+0000 lvl=info msg="LargeTX execution time" block=49512460 …
```
> performance: track large tx execution cost

- cmd/jsutils/getchainstatus.js
> jsutils: add tool GetLargeTxs

- miner/bid_simulator.go
- miner/worker.go
**1.for metrics: `"bid/err/<...>"`**
```
// reportIssue reports the issue to the mev-sentry
func (b *bidSimulator) reportIssue(bidRuntime *BidRuntime, err error) {
metrics.GetOrRegisterCounter(fmt.Sprintf("bid/err/%v", bidRuntime.bid.Builder), nil).Inc(1)
...
}
```
The error of "simulation abort due to better bid arrived" should not be taken as bid error, otherwise the metrics would be useless, as there would be lots of such kind of errors(hundreds per hour)
**2.for metrics: `"block/from/<...>"`**
```
metrics.GetOrRegisterCounter(fmt.Sprintf("block/from/%v", from), nil).Inc(1)
```
a.it is inaccurate, as blocks that are committed in `commitWork()` does not mean it is a valid one, it could be rejected later in `taskLoop()` as block seal failed, like:
```
"Block sealing failed" …
```
> metrics: optimize mev metrics

- miner/worker.go
For historical reasons, `the reset timer` was added to fix a corner case issue, that the chain could be stuck.
The recommit code was kept, mainly because it has no obvious side-effect and the corner could is still there?(Personally, I prefer to keep right now, but also ok to remove it in the future.)
But it should be reseted on new block, this PT just do it.
* ...
> miner: reset recommit timer on new block

- eth/backend.go
- Add proper error slice handling for txPool.Add operations
- Improve removal logic to only remove registered node IDs
> evn: improve node ID management with better error handling

- eth/fetcher/block_fetcher.go
- eth/handler.go
- eth/peerset.go
- p2p/peer.go
This PR adds more monitor metrics for EVN, it can be used for monitor the network improvement from EVM.
1. Monitor new block fetching feature:
```bash
eth_fetcher_block_legacy_cost{job=~"$jobs",quantile=~"$percentile"}
eth_fetcher_block_quick_cost{job=~"$jobs",quantile=~"$percentile"}
eth_fetcher_block_quick_success{job=~"$jobs"}/(eth_fetcher_block_quick_success{job=~"$jobs"}+eth_fetcher_block_quick_err{job=~"$jobs"})
eth_fetcher_block_quick_fallback{job=~"$jobs"}/(eth_fetcher_block_quick_success{job=~"$jobs"}+eth_fetcher_block_quick_err{job=~"$jobs"})
```
2. EVN Peer Monitor
```bash
p2p_peers{job=~"$jobs"}
evn_peer_proxed{job=~"$jobs"}
evn_peer_ onchainValidator{job=~"$jobs"}
evn_peer_ whiteList{job=~"$jobs"}
```
You can also query the peers RPC to get the detailed EVN feature flags for …
> metrics: add more monitor metrics for EVN;

- eth/handler.go
This PR fixes a panic issue, if the remote peer does not support the BSC extension protocol, including bsc/1, bsc/2 protocols, it will cause a panic.
This is a quick fix, only effect quick block fetching feature.
* p2p: fix bscExt checking logic;
* ...
> p2p: fix bscExt checking logic;

- consensus/parlia/stakehub.go
- eth/protocols/bsc/dispatcher.go
- eth/protocols/bsc/handler.go
- eth/protocols/bsc/peer.go
This PR will fix several occasional issues for EVN.
1. Failed to call getValidators
It reports this error log occasionally, which is caused by unstale chain state, here will use default `rpc.LatestBlockNumber`.
```bash
t=05-15|02:08:49.023 lvl=error msg="Failed to call getValidators" error="header not found"
t=05-15|02:08:49.023 lvl=error msg="Failed to get validators" error="failed to call getValidators: header not found"
```
2. New Block fetching request timeout
3. 
It reports this error log occasionally, which is caused by sending first.
```bash
t=05-15|06:21:04.069 lvl=debug msg="Quick block fetching" peer=56cee43c4bd981efba088f3b6360e0621e8f68c0ac0b4ae4fdeb2e78e8d2d523 hash=0x8720c104038d9798844732d7bf0d69134a27880ccbca0f018362b012736949c9
t=05-15|06:21:04.074 lvl=debug msg="receive …
```
> chore: fix several occasional issues for EVN;

- params/config.go
Maxwell hard fork will include 3 BEPs, mainly to reduce block interval to 0.75 seconds:
- [BEP-524: shorter block interval phase two: 0.75 seconds](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-524.md)
- [ BEP-563: add Enhanced Validator Network proposal](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-563.md)
- [BEP-564: add New Block Fetching Messages proposal](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-564.md)
The  expected Testnet Maxwell hard fork time: 2025-05-26 07:05:00 AM UTC
NA
NA
NA
> config: update BSC Testnet hardfork time: Maxwell

- CHANGELOG.md
- version/version.go
v1.5.13 is for BSC Testnet [Maxwell hard fork](https://forum.bnbchain.org/t/bnb-chain-upgrades-testnet/934#p-1416-h-3-maxwell-wip-4), which is expected to be enabled at: `2025-05-26 07:05:00 AM UTC`, all BSC Testnet nodes need to be upgraded to v1.5.13 before the hard fork time. For this upgrade, simply binary replacement should be enough.
Maxwell includes 3 BEPs, mainly to reduce block interval from 1.5 seconds to 0.75 seconds:
- [BEP-524: shorter block interval phase two: 0.75 seconds](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-524.md)
- [ BEP-563: add Enhanced Validator Network proposal](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-563.md)
- [BEP-564: add New Block Fetching Messages proposal](https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-564.md)
Besides …
> release: prepare for release v1.5.13

- eth/backend.go
This PR will fix too large block handle delay metrics.
Current, the mining block time is too large, because of the most time of it is 0, so this metrics is so confusing.
This PR also optimizes other block handle delay times to avoid a large number when restarting.
Bad Metrics:
Optimized Metrics:
* metric: fix too large block handle delay metrics;
* ...
> metric: fix too large block handle delay metrics;

- common/bitutil/bitutil.go
- common/hexutil/hexutil.go
- common/hexutil/json.go
use the built-in max/min to simplify the code
* ...
> refactor: use the built-in max/min to simplify the code

- cmd/geth/chaincmd.go
- eth/protocols/bsc/dispatcher.go
This PR fixes bsc dispatcher request initial issue. This will cause the read of the underlying connection to be blocked, indirectly causing a protocol timeout or EOF error.
The code will block here.
Especially in the intranet environment, the latency is very low and the messages are sent very fast. At this time, the parallel timing is random, and the use of uninitialized chan may cause blocking problems.
* tool: fix fullnode forward tx issue;
* p2p: fix bsc dispatcher request initial issue;
> p2p: fix bsc dispatcher request initial issue;

- consensus/parlia/parlia.go
adjust timeForMining from 2/3 to 4/5, 1/5 is enough for block finalize
* parlia.go: adjust timeForMining
> parlia.go: adjust timeForMining to 4/5 second

- metrics/label.go
- rpc/client_opt.go
- rpc/http.go
- rpc/websocket.go
Optimize code using a more modern writing style.
* ...
> refactor: use maps.copy for cleaner map handling

- cmd/geth/dbcmd.go
- core/bench_test.go
- core/blockchain.go
- core/blockchain_repair_test.go
- core/blockchain_sethead_test.go
- core/blockchain_snapshot_test.go
- core/blockchain_test.go
- core/headerchain.go
- core/rawdb/chain_freezer.go
- core/rawdb/database.go
- core/rawdb/freezer.go
- core/rawdb/freezer_memory.go
- core/rawdb/freezer_resettable.go
- core/rawdb/freezer_test.go
- core/rawdb/prunedfreezer.go
- core/rawdb/table.go
- ethdb/database.go
- ethdb/leveldb/leveldb.go
- ethdb/memorydb/memorydb.go
- ethdb/pebble/pebble.go
- ethdb/pebble/pebble_test.go
- ethdb/remotedb/remotedb.go
- node/database.go
- trie/trie_test.go
- triedb/pathdb/buffer.go
- triedb/pathdb/database.go
core, ethdb: introduce database sync function
new release v1.5.13 will sync from block 0 after `force killed`
try to fix this by cherry-picking https://github.com/ethereum/go-ethereum/pull/31703
* ...
> core, ethdb: introduce database sync function (#31703)

- params/config.go
expected Mainnet Maxwell hard fork time: 2025-06-30 02:30:00 AM UTC
NA
NA
NA
> config: update BSC Mainnet hardfork time: Maxwell

- cmd/utils/flags.go
In the bsc code, the parameter settings for gogc are relatively strict, which will greatly waste memory space for the currently recommended configuration.
In the current code, if a 256GB machine is set to `--cache 64000`, then `gogc=20`, which will trigger gogc very frequently and affect performance.
In this PR, the parameter conditions of gogc are optimized. When the machine memory is large enough, the current threshold is 64GB, and gogc will use the default value.
In actual tests, on the i7i.8xlarge machine, removing the gogc restriction improves the performance of daily traffic in mainnet by ~10%.
At the same time, the performance jitter of the program is less when restarting.
In addition, based on this PR, users can still use GOGC=100 to continue optimizing gogc parameters.
As shown …
> feat: remove gc restriction for large mem;

- miner/bid_simulator.go
miner: simplify code for simulating bids
mini logic changes, clear more than 20+ lines code
* ...
> miner: simplify code for simulating bids

- .github/workflows/release.yml
From https://musl.cc/:
`2025-05-27: GitHub Actions has been blocked wholesale due to [abuse similar to this](https://github.com/orgs/community/discussions/27906#discussioncomment-3332440).`
Github action failed to download musl-cross, which blocks the release workflow.
comparing to other solutions like: Git Large File Storage(LFS), uploaded the musl-cross to S3 could be an easy solution.
NA
NA
> ci: update musl-cross download link

- .github/workflows/release.yml
- CHANGELOG.md
- version/version.go
v1.5.14 release failed due to a CI issue.
v1.5.15 is exactly same as v1.5.14, but fixed the CI issue.
NA
NA
NA
> release: bump v1.5.15

- .github/workflows/release.yml
- CHANGELOG.md
- version/version.go
v1.5.14 & v1.5.15 release failed due to a CI issue.
v1.5.16 is exactly same as v1.5.14 & v1.5.15, but fixed the CI issue.
NA
NA
NA
> release: bump v1.5.16

- .github/workflows/docker-release.yml
- Dockerfile
This PR adds multi-arch docker image build using native arm64 GH runner. Based on [Docker docs](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners)
All 3 major cloud providers are selling arm64 cost-effective CPUs. It may be useful to Apple Silicone users as well
* ci: Dockerfile bump alpine version
* ci: docker-release add arm64 runner and multi-arch build
> Docker arm64 runners

- core/vm/contract.go
- core/vm/contract_pool.go
- core/vm/evm.go
- core/vm/instructions_test.go
- eth/tracers/js/tracer_test.go
- eth/tracers/logger/logger_test.go
- tests/state_test.go
- Replaced custom contract pool implementation with a global `sync.Pool`
- Simplified the API by removing the `ContractPool` struct and making functions package-level
- Improved JUMPDEST analysis reuse by properly handling parent contract context
- Removed unnecessary cleanup and size tracking functions
- Optimized memory usage by letting `sync.Pool` handle object lifecycle
- Changed from instance-based pool to a global `sync.Pool` for better performance
- Removed manual mutex locking as `sync.Pool` is thread-safe by design
- Improved JUMPDEST analysis reuse by checking parent contract context before creating new map
- Removed redundant cleanup of contract fields as they are reset on next use
- Simplified the API to just `GetContract` and `ReturnContract` functions
- Better performance …
> vm: implement contract pool

- internal/ethapi/api_mev.go
- miner/bid_simulator.go
- miner/miner_mev.go
miner: add more metrics for mev
* ...
> miner: add more metrics for mev

- core/blockchain.go
- core/state_prefetcher.go
- core/state_prefetcher_test.go
- core/types.go
- miner/bid_simulator.go
- miner/worker.go
miner: prefetch states for bids simulating
* ...
> miner: prefetch states for bids simulating

- CHANGELOG.md
- version/version.go
v1.5.17 is a maintenance release, which mainly includes several commits to further improve the performance.
Here is the list of recent performance commits:
- https://github.com/bnb-chain/bsc/pull/3105:  increase ~20% mining time.
- https://github.com/bnb-chain/bsc/pull/3141: could improve performance ~7% (optional)
- https://github.com/bnb-chain/bsc/pull/3140: could improve performance ~10% 
- https://github.com/bnb-chain/bsc/pull/3139: would benefit MEV, unknown improvements
- https://github.com/bnb-chain/bsc/pull/3145: would benefit MEV, unknown improvements
- https://github.com/bnb-chain/bsc/pull/3156: save cpu ~2%
- https://github.com/bnb-chain/bsc/pull/3112: reduce memory allocation frequency by ~6%
- https://github.com/bnb-chain/bsc/pull/3120: reduce memory allocation …
> release: prepare for release v1.5.17

- ethdb/pebble/pebble.go
In the current BSC validator and miner workflow, write stalls frequently occur during the commit or block synchronization processes. Specifically, operations like writeStateID or writing block data often experience write delays of several hundred milliseconds, which negatively impacts commit performance and causes miners to exceed the 750ms block production time. 
Pebble allows configuring multiple memtables for buffering unflushed data，if too many memtables are blocked and are waiting to be flushed, subsequent writes will stall, especially when Pebble performs a background flush while compaction is also ongoing. By default, Pebble is configured with only 2 memtables, each potentially exceeding 1GB in size. This behavior can be mitigated by increasing the number of memtables, which allows …
> ethdb: enlarge the number of memory tables

- cmd/evm/eest.go
- core/remote_state_verifier.go
- core/state_transition.go
fix some typos in comment
* ...
> chore: fix some typos in comment

- .nancy-ignore
- cmd/jsutils/getchainstatus.js
> chore: nancy and jsutils

- cmd/faucet/rate_limiter.go
- consensus/parlia/parlia.go
- consensus/parlia/snapshot.go
- core/blockchain.go
- core/monitor/malicious_vote_monitor.go
- core/remote_state_verifier.go
- core/vm/contract.go
- core/vote/vote_journal.go
- core/vote/vote_manager.go
- go.mod
- miner/worker.go
all: use typed lru
Improve code readability.
* ...
> all: use typed lru

- miner/bid_simulator.go
miner: only recommit bids when no error happens
a bug is introduced by PR https://github.com/bnb-chain/bsc/pull/3135/files
it will lead to log flusing:
this PR is to fix it.
* ...
> miner: only recommit bids when no error happens

- internal/ethapi/api.go
> chore: fix problematic comment

- ethdb/pebble/pebble.go
This value determine the amount of L0 read-amplification necessary to trigger an L0 compaction. Reduces the threshold for triggering compaction help make compaction more frequently and reduce the accumulated debt by 90%.  
The debt defined in pebble as bleow:
```
// An estimate of the number of bytes that need to be compacted for the LSM
// to reach a stable state.
EstimatedDebt uint64
```
the  bsc fullnode instance represented by the green line（run with pr new code） has an average compression debt of only 82.9 MiB, which is significantly lower than the average compression debt of about 8.62 GiB for the instance represented by the orange line
For execution performance, there also seems to be some improvement (P99).
This is because pebble's compaction negatively impacts read/write I/O,
and …
> ethdb: tuning pebble compaction parameter

- core/state_prefetcher.go
- params/config.go
params: only enable sharedStorage on special blocks
* ...
> params: only enable sharedStorage on special blocks

- core/blockchain.go
- core/headerchain.go
- core/verkle_witness_test.go
make function comment match function names
* ...
> chore: make function comment match function names

- cmd/geth/main.go
- cmd/utils/flags.go
- core/blockchain.go
- core/blockchain_reader.go
- core/state/state_object.go
- core/state/statedb.go
- core/state_prefetcher.go
- eth/backend.go
- eth/ethconfig/config.go
- params/config.go
Fixed the shared-storage-pool bug and added a flag to control the shared-storage-pool feature.
Https://github.com/bnb-chain/bsc/pull/792 introduces the shared-storage-pool. However, this feature was found to have a bug at https://forum.bnbchain.org/t/about-the-hertzfix/2400 and has been disabled by the hertzfix hardfork.
This PR fixed the shared-storage-pool bug and enabled the shared-storage-pool feature, improving performance by ~4%.
To ensure compatibility, before hertzfix, the original shared-storage-pool cache is still read. After hertzfix, it is determined whether the corresponding account has been destructed in the block. If deleted, it is not read from the shared-storage-pool to avoid reading the wrong data.
https://github.com/will-2012/bsc/blob/482f9a34e7a9dd21ec42cc3971b9ce915112 …
> feat: enable shared storage pool

- eth/handler_test.go
The comments here and below are identical, but the struct names are inconsistent.
https://github.com/bnb-chain/bsc/blob/develop/eth/handler_test.go#L330
I have made the corresponding modifications based on the comments before the `testTxPool` struct and the `newTestTxPool` method.  https://github.com/bnb-chain/bsc/blob/develop/eth/handler_test.go#L59
* ...
> chore: fix struct comment

- core/state_prefetcher_test.go
- core/state_transition.go
- eth/peerset_test.go
- eth/tracers/native/4byte.go
There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
* ...
> refactor: use slices.Contains to simplify code

- cmd/geth/dbcmd.go
- core/rawdb/ancient_utils.go
- node/node.go
The old blockstore code has set the disableFreezer as true  to make the ancient store in blockstore, which is not removed clearly.  This  bug only affects the multidb .
set disableFreezer  as false
* ...
> ethdb: fix disable freezer when enable multidb

- core/rawdb/chain_freezer.go
- core/rawdb/database.go
In the recent v1.5.18 upgrade, the previous pruneancient was replaced by tail-deletion, but some cases were found in the grayscale test to cause import performance degradation.
Nodes using the "--pruneancient" flag are affected. We observed that if you enable "--pruneancient" for the first time, it will delete the ancient directory to save storage, but due to a code bug, new blocks will not continue to be deleted and will continue to accumulate in pebbledb.
If "--pruneancient" is enabled and the node is upgraded to v1.5.18, a large number of historical block deletions will be triggered, which will cause great pressure on the disk. At the same time, you will also have high latency when accessing ancient data, which affects the import performance.
This PR reduces the `freezerBatchLimit` …
> freezer: change freeze batch size;

- core/blockchain_test.go
- core/rawdb/ancient_scheme.go
Set all chain tables to be prunable.
geth needs to truncate all chain tables when merging incr snapshot.
N/A
* N/A
> fix: set all chain tables to be prunable

- core/filtermaps/math.go
- eth/backend.go
core/fitermaps: fix final block logic
* ...
> core/fitermaps: fix final block logic

- cmd/geth/dbcmd.go
- cmd/utils/flags.go
add  expand mode 
`geth --datadir /data/ethereum --expandmode db migrate /target/dir 5`
last number is the version
* ...
> ethdb : add expand mode for migration tool

- core/state/state_object.go
- core/state/statedb.go
- core/state_processor.go
- internal/ethapi/transaction_opts_utils.go
core/state: code clear up
align more codes with go-ethereum
* ...
> core/state: code clear up

- miner/worker.go
During mining phase, if a new block was just imported, TransferPrefetcher could transfer a TriePrefetcher of previous block to the new block, which would cause later error on OpenTrieStorage of the TriePrefetch routine.
This PR is to fix [the](https://github.com/bnb-chain/bsc/issues/3304) 
NA
NA
NA
> worker: fix a trie prefetch corner case

- core/blockchain.go
- core/filtermaps/filtermaps.go
core/filtermaps: stop indexing if target block is pruned
fix https://github.com/bnb-chain/bsc/issues/3317
* ...
> core/filtermaps: stop indexing if target block is pruned

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/question.md
> github: update issue template

- ethdb/pebble/pebble.go
eth/pebble: use NoSync as write mode
* ...
> eth/pebble: use NoSync as write mode

- accounts/abi/bind/v2/dep_tree_test.go
- accounts/abi/bind/v2/internal/contracts/db/contract.sol
- cmd/devp2p/internal/ethtest/suite.go
- core/rawdb/accessors_indexes.go
- core/rawdb/database.go
- core/txpool/blobpool/lookup.go
- core/txpool/legacypool/legacypool_test.go
- tests/fuzzers/bn256/bn256_fuzz.go
fix some minor issues in comment
* ...
> chore: fix some minor issues in comment

- p2p/enode/iter.go
It fixes https://github.com/bnb-chain/bsc/issues/3343, node hang on shutdown occasionally.
When the hang occurs, there are two routines stuck.
- routine 1: AsyncFilter(...)
On node start, it will run part of the DiscoveryV4 protocol, which could take considerable time, here is its hang callstack:
```
goroutine 9711 [chan receive]:  // this routine was stuck on read channel: `<-f.slots`
github.com/ethereum/go-ethereum/p2p/enode.AsyncFilter.func1()
github.com/ethereum/go-ethereum/p2p/enode/iter.go:206 +0x125
created by github.com/ethereum/go-ethereum/p2p/enode.AsyncFilter in goroutine 1
github.com/ethereum/go-ethereum/p2p/enode/iter.go:192 +0x205
```
- Routine 2: Node Stop
It is the main routine to shutdown the process, but it got stuck when it tries to shutdown the discovery components, as …
> fix: discovery AyncFilter deadlock on shutdown

- CHANGELOG.md
- version/version.go
v1.6.1-beta is a maintenance preview release, which fixes several issues of the v1.6.0-alpha, it is more reliable, so mark it as beta stage.
This release has no new feature, no breaking changes, only some bugfix and improvements, pls refer change log for detail.
NA
[\#3336](https://github.com/bnb-chain/bsc/pull/3336) miner: avoid to commit a bid twice
[\#3347](https://github.com/bnb-chain/bsc/pull/3347) fix: discovery AyncFilter deadlock on shutdown
[\#3340](https://github.com/bnb-chain/bsc/pull/3340) core: rework fast node
[\#3337](https://github.com/bnb-chain/bsc/pull/3337) eth/pebble: use NoSync as write mode
[\#3332](https://github.com/bnb-chain/bsc/pull/3332) FilterMap: update bsc checkpoint file
[\#3324](https://github.com/bnb-chain/bsc/pull/3324) eth/downloader: remove …
> release: prepare for release v1.6.1-beta

- core/rawdb/accessors_chain.go
- core/rawdb/freezer_table.go
This is for https://github.com/bnb-chain/bsc/issues/3345
Some BSC nodes will run with flag: `--history.blocks=360000`, which only keep the recent 360000 blocks. When remote peer tries to fetch older blocks, it will failed and there would be log spam.
It is not an issue in this case, as the remote peer will drop and retry with other peers, so just downgrade the log level to debug to avoid log spam.
NA
NA
NA
> log: downupgrade header fetch failed log level

- consensus/consensus.go
- consensus/parlia/parlia.go
- core/vote/vote_manager.go
- core/vote/vote_pool.go
- eth/handler_test.go
[BEP-590: Extended Voting Rules for Fast Finality Stability](https://github.com/bnb-chain/BEPs/pull/590)
* ...
> BEP-590: Extended Voting Rules for Fast Finality Stability
