bnb-chain/bsc

- core/vm/interpreter.go
Resolves https://github.com/binance-chain/bsc/issues/12
> [R4R]fix debug_traceTransaction crashed issue

- PULL_REQUEST_TEMPLATE
We add a `pull request template` here so that everyone follows this template and check necessary items.
No impack
No
> [R4R]Create PULL_REQUEST_TEMPLATE

- CHANGELOG.md
add change log for v1.0.4 and prepare for release.
draft v1.0.4 release
IMPROVEMENT
* [\#35](https://github.com/binance-chain/bsc/pull/35) use fixed gas price when network is idle 
* [\#38](https://github.com/binance-chain/bsc/pull/38) disable noisy log from consensus engine 
* [\#47](https://github.com/binance-chain/bsc/pull/47) upgrade to golang1.15.5
* [\#49](https://github.com/binance-chain/bsc/pull/49) Create pull request template for all developer to follow 
* ...
...
> [R4R]add change log for release v1.0.4

- CHANGELOG.md
- params/version.go
Prepare for release v1.0.5
SECURITY
* [\#63](https://github.com/binance-chain/bsc/pull/63) security patches from go-ethereum 
* [\#54](https://github.com/binance-chain/bsc/pull/54) les: fix GetProofsV2 that could potentially cause a panic.
FEATURES
* [\#56](https://github.com/binance-chain/bsc/pull/56) apply mirror sync upgrade 
* [\#53](https://github.com/binance-chain/bsc/pull/53) support fork id in header; elegant upgrade
IMPROVEMENT
* [\#61](https://github.com/binance-chain/bsc/pull/61)Add `x-forward-for` log message when handle message failed
* [\#60](https://github.com/binance-chain/bsc/pull/61) add rpc method request gauge
BUGFIX
* [\#59](https://github.com/binance-chain/bsc/pull/59) fix potential deadlock of pub/sub module 
* …
> [R4R]prepare for release v1.0.5

- Dockerfile
add jq to containner.
* ...
...
> [R4R]add jq to docker file

- core/vm/interpreter.go
https://gist.github.com/karalabe/e1891c8a99fdc16c4e60d9713c35401f
https://github.com/ethereum/go-ethereum/security/advisories/GHSA-69v6-xc2j-r2jf
* ...
...
> revert bug fix in 1.9.17

- README.md
the previous discord link expired, and the new one will never expire
update a discord invite link that will never  expire.
* ...
...
> [R4R]update discord link

- CHANGELOG.md
- params/version.go
Release v1.1.0 stable version
N/A
* more aggressive write cache policy(#227 )
* update discord link(#280 )
* update discord link(#282 )
#309
> Release v1.1.0 stable version

- CHANGELOG.md
- params/version.go
This release focous on performance:
*[\#333](https://github.com/binance-chain/bsc/pull/333) improve block fetcher efficiency
*[\#326](https://github.com/binance-chain/bsc/pull/326) eth/tracers: improve tracing performance
*[\#257](https://github.com/binance-chain/bsc/pull/257) performance improvement in many aspects
Add one config `TriesInMemory`, which specify the snapshot layers and how many MPT trees in memory.
...
> [R4R]prepare release 1.1.1-beta

- CHANGELOG.md
The current changing log is not well formatted.
Fix the format of changing log.
* ...
...
> [R5R]format change log 

- CHANGELOG.md
- params/version.go
v1.1.2 is a pre-announced hotfix release to patch a vulnerability in the EVM (CVE-2021-39137).
Security fix from upstream https://github.com/ethereum/go-ethereum/releases/tag/v1.10.8
* ...
...
> [R4R]prepare for release 1.1.2

- CHANGELOG.md
- params/version.go
Prepare for release v.1.1.4
Improvement
* [\#472](https://github.com/binance-chain/bsc/pull/472) add metrics for contract code bitmap cache
* [\#473](https://github.com/binance-chain/bsc/pull/473) fix ci test flow
BUGFIX
* [\#491](https://github.com/binance-chain/bsc/pull/491) fix prefetcher related bugs
FEATURES
* [\#480](https://github.com/binance-chain/bsc/pull/480) implement bep 95
...
> [R4R] prepare for release v.1.1.4

- cmd/utils/flags.go
- core/blockchain.go
- core/blockchain_diff_test.go
- core/state_processor.go
- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
- eth/downloader/queue.go
- eth/downloader/resultstore.go
- eth/ethconfig/config.go
- eth/handler_diff.go
- eth/protocols/diff/handler.go
- internal/ethapi/api.go
- node/node.go
* [\#493](https://github.com/binance-chain/bsc/pull/493) accelerate get diff accounts with scope
* [\#509](https://github.com/binance-chain/bsc/pull/509) fix graceful shutdown bug
* [\#527](https://github.com/binance-chain/bsc/pull/527) improve the protocol details of Diff sync
...
> pre release of v1.1.5

- README.md
The old Discord link is Invalid.
Update the new one https://discord.gg/z2VpC455eU
N/A
N/A
* README.md
#737
> [R4R] Update discord link

- CHANGELOG.md
- README.md
- docs/parlia/README-BEP-127.md
- params/config.go
- params/version.go
The master branch has merged several commits, we should sync develop branch with the master.
Keep develop branch sync with the master.
NA
*
> [R4R] sync with master branch

- core/blockchain_diff_test.go
- core/blockchain_notries_test.go
Because #926 introduces the implementation of asynchronous cache Difflayer, it may obtain DiffLayer when the cache is not completed during testing.
```
go test -timeout 30m -run ^TestFastNode$ github.com/ethereum/go-ethereum/core
go test -timeout 30s -run ^TestGetRootByDiffHash$ github.com/ethereum/go-ethereum/core
```
* core/blockchain_diff_test.go
* core/blockchain_notries_test.go
> [R4R] fix asynchronous caching of difflayer causes random errors in tests

- .github/workflows/docker-release.yml
Automatically upload the latest version of Docker Image to GitHub package when a new version is released
N/A
N/A
* .github/workflows/docker-release.yml
> [R4R] add ci script to docker image

- appveyor.yml
- build/ci.go
- cmd/geth/snapshot.go
- core/blockchain.go
- core/rawdb/accessors_state.go
- core/state/pruner/pruner.go
- core/state/state_object.go
- core/state/statedb.go
- core/vm/operations_acl.go
- eth/downloader/downloader.go
- eth/protocols/snap/sync.go
- eth/tracers/api.go
- graphql/graphql.go
- internal/build/download.go
- internal/ethapi/api.go
- les/vflux/client/fillset_test.go
- les/vflux/server/clientpool.go
- light/lightchain.go
- mobile/geth.go
- p2p/server.go
- rpc/server_test.go
- tests/fuzzers/vflux/clientpool-fuzzer.go
- trie/iterator.go
- trie/iterator_test.go
Pick some patches from `go-ethereum` on v1.10.16, v1.1.0.17, mainly including some bug fixes, and would submit some separate `prs` for left related patches about  features/performance.
N/A
N/A
* mainly including some bug fixes
> fix: upstream patches

- CHANGELOG.md
- params/version.go
This PR is prepare for the v1.1.14, a maintenances release.
Change logs:
IMPROVEMENT
* [\#1057](https://github.com/bnb-chain/bsc/pull/1057) ci: allow merge pull request
* [\#1063](https://github.com/bnb-chain/bsc/pull/1063) ci: fix the pattern of commit lint
BUGFIX
* [\#1062](https://github.com/bnb-chain/bsc/pull/1062) test: fix TestOfflineBlockPrune failed randomly
* [\#1076](https://github.com/bnb-chain/bsc/pull/1076) bug: pick some patches from go-ethereum on v1.10.18
* [\#1079](https://github.com/bnb-chain/bsc/pull/1079) core: fix potential goroutine leak
NA
No impact to users
> release: update version and changelogs

- Dockerfile
> remove bind-tools version

- Dockerfile
fix dockerfile
N/A
* Dockerfile
> docker: fix dockerfile

- Dockerfile
> docker: update bind-tools version to 9.16.36

- core/tx_list.go
- core/tx_pool.go
- core/tx_pool_test.go
- core/txpool2_test.go
follow https://github.com/ethereum/go-ethereum/pull/26648
* ...
> core/txpool: implement additional DoS defenses

- cmd/utils/flags.go
- eth/backend.go
More background, pls refer: https://github.com/bnb-chain/bsc/issues/1485
Just not register the diff protocol
NA
NA
> feature: remove diff protocol registration

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
D__BLST_PORTABLE__ not export for release binary
it may lead to geth not work on some old machines
https://github.com/bnb-chain/bsc/issues/1562
* ...
> fix: make BLST PORTABLE for release binary

- consensus/parlia/parlia.go
log info when failed to verifyVoteAttestation even after plato upgrade
* ...
> Fix log verify vote attestation

- consensus/parlia/parlia.go
Very simple commit, skip description.
NA
NA
NA
> fix: log info when failed to verifyVoteAttestation

- README.md
There is missed description on sync from genesis, just add it.
NA
NA
NA
> readme: update full sync from genesis

- cmd/geth/blsaccountcmd.go
support password flag when handling bls keys
Easier to be integrated into scripts
* ...
> support password flag when handling bls keys

- beacon/engine/types.go
- core/rawdb/accessors_chain_test.go
- core/rawdb/blob.go
- core/rawdb/blob_test.go
- core/rawdb/blobbolt/crud.go
- core/rawdb/bloblevel/crud.go
- core/types/data_blob.go
- go.mod
- go.sum
- params/config.go
> 4844 blobs storage

- .github/commitlint.config.js
PR merge will append the PR number at the end, like:... (#1805), which has extra 8 characters
NA
NA
NA
NA
> ci: increase header-max-length from 72 to 80 for master branch

- go.mod
- go.sum
Update BLST to v0.3.11
[tell us why we need these changes...](https://github.com/supranational/blst/releases)
* ...
> crypto: Update BLST to v0.3.11

- cmd/utils/flags.go
- docker/Dockerfile
- miner/ordering.go
- p2p/discover/table.go
- p2p/discover/table_util_test.go
- p2p/discover/v4_udp.go
- p2p/discover/v5_udp.go
- tests/truffle/config/config-bsc-rpc.toml
- tests/truffle/config/config-validator.toml
- tests/truffle/scripts/bsc-validator.sh
fix integration test
1. miner.etherbase must be set for validator now
2. if BootstrapNodes is a empty slice ,not nil, and BootnodesFlag is set,
we should add extra bootnodes from BootnodesFlag
3. copy nil baseFee will cause panic
```
make truffle-test pass
transfer using metamask pass
```
* ...
> Big merge v1.10.16 v1.12.2 fix integration test

- cmd/geth/dbcmd.go
- trie/committer.go
- trie/hash2path.go
- trie/triedb/pathdb/disklayer.go
add hashdb to pathdb tool
Reduce sync time
NA
* NA
> dbtool: add hashdb to pathdb tool

- core/blockchain_insert.go
- core/forkchoice.go
> logs: add some logs to trace block miner, justified reorg; (#1894)

- core/blockchain.go
fast node has no trie, no need to check hasState check.
* ...
> fix: skip HasState check for fast node

- core/vm/contracts.go
> Revert "fix: skip a patch that could fork the chain"

- eth/protocols/eth/protocol.go
> eth: sidecar sanity check todo

- CHANGELOG.md
v1.3.1 will include more changes, update the CHANGELOG.md
NA
NA
NA
> doc: update changelog for v1.3.1

- consensus/parlia/abi.go
- consensus/parlia/parlia.go
> chore: modify breath block interval for test

- consensus/parlia/parlia.go
This pr is to fix a bug in determining breathe block
* change logic of determining breathe block
> fix: bug in determining breathe block

- README.md
Update the readme to show the latest hardware requirements to run a BSC full node.
NA
NA
NA
> readme: update hardware requirements for BSC full node

- core/vm/contracts.go
This pr is to remove unused code
No notable changes
> chore: remove unused code

- core/blockchain.go
core: add metrics for bad block
in chapel net or mainnet, `BAD BLOCK` should not happen
so we monitor it, if it happens, alert us to analyse and solve it
* ...
> core: add metrics for bad block

- miner/worker.go
This pr is to add `SystemTxsGas` for Feynman upgrade`SystemTxsGas` for Feynman upgrade
Feynman upgrade will introduce many new system txs. So we need more `SystemTxsGas`
* add `SystemTxsGas`
> chore: add `SystemTxsGas` for Feynman upgrade

- params/config.go
Just to fix lint issue 
None
None
None
> chore: fix lint issue

- params/protocol_params.go
As BSC's validator set is increasing, larger validator set may consume more gas, so increase the gas reserved for system transactions.
NA
NA
NA
> improve: increase SystemTxsGas from 1,500,000 to 5,000,000

- cmd/jsutils/README.md
- cmd/jsutils/gettxcount.js
add --miner flag to support filter by miner address
* cmd/jsutil: add --miner flag
> cmd/jsutil: add --miner when count tx

- consensus/parlia/parlia.go
- core/chain_makers.go
- core/state_processor.go
- eth/tracers/api.go
- miner/worker.go
This pr is to adjusted the timing of `UpgradeBuildInSystemContract`
To avoid set code too early
* move the call to `UpgradeBuildInSystemContract` from the beginning of a block to the end of a block
> fix: adjusted the timing of `UpgradeBuildInSystemContract`

- eth/state_accessor.go
- eth/tracers/api.go
This pr is to fix an issue that wrongly upgrading system contracts twice in `traceBlockParallel`
* ...
> fix: upgrade system contracts twice issue in `traceBlockParallel`

- consensus/parlia/feynmanfork.go
- consensus/parlia/parlia.go
This pr is to add initialize for TokenRecoverPortalContract
* ...
> chore: add initialize for TokenRecoverPortalContract

- build/ci.go
- cmd/geth/blsaccountcmd.go
- consensus/parlia/parlia.go
- eth/state_accessor.go
- eth/tracers/api.go
- eth/tracers/api_test.go
This pr is to fix some review comments
* adjust the timing of initializing Feynman system contracts
* update ci setting
> fix: adjust the timing of initializing Feynman system contracts

- eth/gasprice/feehistory.go
> eth/gasprice: fix percentile validation in eth_feeHistory (#2242)

- go.mod
- go.sum
ci: fix nancy vulnerabilities issue;
* ci: fix nancy vulnerabilities issue;
* ...
> ci: fix nancy vulnerabilities issue;

- consensus/parlia/parlia.go
This change add support of `EIP1153` for for internal SC transactions
* ...
> parlia: add state prepare for internal SC transaction

- consensus/parlia/parlia.go
- core/block_validator.go
- core/data_availability.go
- core/evm.go
- eth/protocols/eth/broadcast.go
- eth/protocols/eth/peer.go
- miner/worker.go
> blobtx mining pass

- common/types.go
- common/types_test.go
- consensus/parlia/parlia.go
- core/blockchain.go
- core/blockchain_reader.go
- core/chain_makers.go
- core/data_availability.go
- core/data_availability_test.go
- core/evm.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_chain_test.go
- core/rawdb/ancient_scheme.go
- core/rawdb/chain_freezer.go
- core/rawdb/database.go
- core/rawdb/freezer.go
- core/rawdb/schema.go
- core/state/pruner/pruner.go
- core/state_transition.go
- core/types/block.go
- eth/downloader/downloader.go
- eth/downloader/queue.go
- eth/fetcher/block_fetcher.go
- eth/handler_eth.go
- eth/handler_test.go
- eth/protocols/eth/broadcast.go
- eth/protocols/eth/handler_test.go
- eth/protocols/eth/handlers.go
- eth/protocols/eth/peer.go
- eth/sync_test.go
- miner/worker.go
syncing: support to sync blobs and check DA;
* execution: add blob gas fee reward to system;
* syncing: support blob syncing & DA checking;
* ...
> syncing: support to sync blobs and check DA;

- eth/api_backend.go
> core: build fix

- consensus/parlia/parlia.go
- core/types/block.go
- eth/protocols/eth/handlers.go
- eth/protocols/eth/peer.go
> fix the semantics of WithXXX

- Makefile
- tests/truffle/scripts/bootstrap.sh
use pbss to test sometimes may halt
block other PRs now
* ...
> tests/truffle: use hbss to run test

- core/types/bid.go
- miner/miner_mev.go
feat: export GasCeil in mev_params
> feat: export GasCeil in mev_params

- consensus/parlia/parlia.go
- core/data_availability_test.go
- core/evm.go
- core/vm/runtime/runtime_test.go
- internal/ethapi/api.go
> remove useless Config()

- miner/worker.go
fix: fix mined block sidecar issue;
* fix: fix mined block sidecar issue;
* ...
> fix: fix mined block sidecar issue;

- core/data_availability_test.go
- core/types/block.go
> fix WithSidecars

- miner/bid_simulator.go
fix: NPE at bid_simulator L739
* ...
> fix: a nil point error in mev worker

- miner/bid_simulator.go
1. fix oom of mev bid env
2. reduce mev recommit log
* ...
> fix: oom caused by non-discarded mev simulation env

- core/blockchain.go
- core/blockchain_insert.go
metrics: add blockInsertMgaspsGauge to trace mgasps
* ...
> metrics: add blockInsertMgaspsGauge to trace mgasps

- .nancy-ignore
Detected Nancy failure:
```
pkg:golang/github.com/btcsuite/btcd/btcec/v2@v2.3.2
1 known vulnerabilities affecting installed version 
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ [CVE-2024-34478] CWE-754: Improper Check for Unusual or Exceptional Conditions                                                                                                                                                   ┃
┣━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ …
```
> nancy: add files .nancy-ignore

- cmd/geth/snapshot.go
- core/state/pruner/pruner.go
- eth/ethconfig/config.go
- trie/hbss2pbss.go
fix a lot of typos
https://github.com/bnb-chain/bsc/pull/2432#issuecomment-2081446283
* ...
> chore: fix some typos

- core/rawdb/accessors_chain.go
core/rawdb: add sanity-limit to header accessor (#29534)
* ...
> core/rawdb: add sanity-limit to header accessor (#29534)

- core/rawdb/accessors_chain.go
- eth/filters/api.go
- eth/handler.go
- 1.Two bugfix PR for go-ethereum for security.
- 2.One bug fix PR of block propagation after 4844
NA
NA
NA
> merge some PRs for v1.4.7 

- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- consensus/parlia/feynmanfork.go
- params/protocol_params.go
> cmd/utils: add a flag to change breathe block interval for testing

- eth/backend.go
> fix: adjust cache

- README.md
> doc: update url linker

- eth/fetcher/block_fetcher_test.go
> chore: fix function name

- ethclient/ethclient.go
the second param should be a point not a bool value
* [ethclient/ethclient.go
* ...
> fix getBlobSidecars by ethclient

- core/blockchain.go
- core/events.go
- eth/handler.go
- miner/worker.go
Revert "miner/worker: broadcast block immediately once sealed (bnb-chain#2576)"
* ...
> Revert "miner/worker: broadcast block immediately once sealed (bnb-chain#2576)"

- consensus/parlia/parlia.go
consensus/parlia: support recovery when snapshot of parlia gone in disk
* ...
> consensus/parlia: support recovery when snapshot of parlia gone in disk

- triedb/versiondb/versadb.go
> chore: update versadb default config

- triedb/versiondb/versadb.go
> chore: update trivals

- core/state/snapshot/disklayer.go
- core/state/snapshot/metrics.go
- triedb/pathdb/disklayer.go
- triedb/pathdb/metrics.go
> perf: add db metrics

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
> github: upgrade upload artifact from v4.1.7 to v4.3.3

- cmd/pyutils/reorg_analyzer.py
> utils: print monikey for reorg script

- core/state/statedb.go
- internal/ethapi/transaction_args.go
> log: change log level

- core/blockchain.go
- core/types/blob_sidecar.go
- miner/worker.go
- params/config.go
params: fix ChainConfig.String for Ethash
* ...
> params: fix ChainConfig.String for Ethash

- consensus/parlia/parlia.go
> fix(parlia): correct error msg

- cmd/geth/config.go
- cmd/jsutils/getchainstatus.js
- cmd/utils/flags.go
- consensus/parlia/parlia.go
- core/blockchain.go
- core/txpool/legacypool/legacypool.go
- core/vote/vote_manager.go
- eth/backend.go
- metrics/exp/exp.go
- metrics/label.go
- metrics/prometheus/collector.go
- triedb/pathdb/asyncnodebuffer.go
- triedb/pathdb/buffer.go
- triedb/pathdb/disklayer.go
- triedb/pathdb/journal.go
This PR includes some bug fix for v1.5.2-alpha.
Pls refer: https://github.com/bnb-chain/bsc/pull/2808, for release notes of v1.5.2-alpha.
NA
NA
NA
> some bug fix before release 1.5.2-alpha

- core/state_transition.go
core: check authority not in black list
* ...
> core: check authority not in black list

- triedb/pathdb/database_test.go
triedb/pathdb: recover testDisable
* ...
> triedb/pathdb: recover testDisable

- miner/worker.go
When the block gas limit is reached in the miner's local building loop, the packing process stops prematurely, even though there might be still much time till the block.timestamp. At that time, some builders may not have provided their best bids, leading to suboptimal block selection.
On February 14th, during a peak usage period on the BNB Chain mainnet, builders struggled to have their bids accepted by validators, making it difficult for bundles and private transactions to finalize.
This PR adds a simple mechanism: if there's still ample time before sealing, introduce a short wait. This ensures the validator makes full use of the 3-second window to pack transactions and wait for potentially better bids.
- Extends the packing window to its full duration.
- Minimizes the risk of missing …
> fix: wait builder's final bid during the peak time

- cmd/geth/chaincmd.go
- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- core/genesis.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
- params/config.go
> params: add LorentzTime

- core/types/bid.go
- miner/bid_simulator.go
> fix: gas compare in bid simulator

- params/config.go
Expected Testet Lorentz hard fork time: 2025-04-08 07:33:00 AM UTC
NA
NA
NA
> config: update tentative BSC Testnet hardfork time: Lorentz

- core/systemcontracts/upgrade.go
core/systemcontracts: update url for lorentz hardfork
https://github.com/bnb-chain/bsc-genesis-contract/commit/44ebc6c17a00bd24db3240141a78091528dcebbb
belong to develop branch of `bsc-genesis-contract` repo
* ...
> core/systemcontracts: update url for lorentz hardfork

- cmd/jsutils/getchainstatus.js
cmd/jsutils: add tool GetMevStatus
* ...
> cmd/jsutils: add tool GetMevStatus

- cmd/jsutils/.prettierrc
- cmd/jsutils/getchainstatus.js
- cmd/jsutils/package.json
cmd/jsutils: configure prettier as formmatter
avoid developer use different code style to format, 
cause a lot of differences
* ...
> cmd/jsutils: configure prettier as formatter

- cmd/jsutils/getchainstatus.js
cmd/jsutils: improve getMevStatus
1. simplify codes
2. align output
align output
node getchainstatus.js GetMevStatus --rpc https://bsc-dataseed-public.bnbchain.org --startNum 47772896  --endNum 47772916
```
blockNum: 47772896      miner: Namelix          builder: (puissant x          ) 0x48B4bBEbF0655557A461e91B8905b85864B8BB48
blockNum: 47772897      miner: Namelix          builder: (puissant x          ) 0x48B4bBEbF0655557A461e91B8905b85864B8BB48
blockNum: 47772898      miner: Namelix          builder: (blockrazor frankfurt) 0xBA4233f6e478DB76698b0A5000972Af0196b7bE1
blockNum: 47772899      miner: Namelix          builder: (puissant x          ) 0x48B4bBEbF0655557A461e91B8905b85864B8BB48
blockNum: 47772900      miner: Tranchess        builder: (blockrazor virginia ) …
```
> cmd/jsutils: improve getMevStatus

- trie/dummy_trie.go
fix function name in comment
* ...
> chore: fix function name in comment

- cmd/jsutils/getchainstatus.js
cmd/jsutils: add builders for chapel testnet
* ...
> cmd/jsutils: add builders for chapel testnet

- cmd/jsutils/getchainstatus.js
To dump more governance value.
NA
NA
NA
> jsutil: update getKeyParameters

- internal/ethapi/api.go
remove duplicate package imports
* ...
> chore: remove duplicate package imports

- core/rawdb/prunedfreezer.go
> chore: fix comment

- miner/bid_simulator.go
miner: fix memory leak caused by no discard env
this is a PR to fix memory leak by PR [miner: optimize clear up logic for envs](https://github.com/bnb-chain/bsc/pull/3034)
* ...
> miner: fix memory leak caused by no discard env

- miner/bid_simulator.go
miner: fix init for bidsToSim
* ...
> miner: fix init for bidsToSim

- eth/protocols/bsc/peer.go
eth/protocols/bsc: adjust vote reception limit
* ...
> eth/protocols/bsc: adjust vote reception limit

- rpc/http.go
There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
* ...
> refactor: use slices.Contains to simplify code

- core/systemcontracts/upgrade.go
> chore: update maxwell contrats addresses

- cmd/geth/chaincmd.go
- common/bitutil/bitutil.go
- common/hexutil/hexutil.go
- common/hexutil/json.go
- eth/backend.go
- eth/handler.go
- eth/peerset.go
- p2p/config.go
- p2p/config_toml.go
- p2p/peer.go
> merge develop branch to master for v1.5.13

- cmd/geth/chaincmd.go
- common/bitutil/bitutil.go
- common/hexutil/hexutil.go
- common/hexutil/json.go
- eth/backend.go
- eth/handler.go
- eth/peerset.go
- eth/protocols/bsc/dispatcher.go
- p2p/config.go
- p2p/config_toml.go
- p2p/peer.go
> merge: develop to master for v1.5.13

- miner/bid_simulator.go
miner: discard outdated bids before simulation
there may be many outdated bids in channel newBidCh
they may be cleared when simulating, cause panic, just filter out them before simulating.
* ...
> miner: discard outdated bids before simulation

- internal/ethapi/api_mev.go
internal/ethapi: improve error msg when refusing bids
1. send too early or too late is very different scenario, return different error msg here,
It will be helpful for builders.
2. when `rawBid.BlockNumber > latestBlockNumber+1`,
without this PR, error msg will be `ErrMevNotInTurn`, this PR fix it.
* ...
> internal/ethapi: improve error msg when refusing bids

- cmd/geth/chaincmd.go
- cmd/geth/config.go
- cmd/geth/main.go
- cmd/utils/flags.go
- consensus/misc/eip4844/eip4844.go
- core/genesis.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
- params/config.go
- params/forks/forks.go
> params: add FermiTime

- miner/bid_simulator.go
miner: fix metric simulateSpeedGauge
* ...
> miner: fix metric simulateSpeedGauge

- consensus/parlia/parlia.go
- core/state/statedb_hooked.go
- core/vm/interface.go
consensus/parlia: warn fast node to update to latest hard fork version
* ...
> consensus/parlia: warn fast node to update to latest hard fork version

- core/opcodeCompiler/compiler/metrics.go
- core/opcodeCompiler/compiler/opCodeProcessor.go
- core/vm/evm.go
- core/vm/instructions.go
- core/vm/interpreter.go
- core/vm/metrics.go
> fix: opcode optimization bug

- build/ci.go
- eth/peerset.go
- eth/protocols/snap/sync.go
- miner/ordering.go
- node/api.go
fix some minor issues in the comments
* ...
> chore: fix some minor issues in the comments

- consensus/parlia/parlia.go
- core/state/statedb.go
- core/state/statedb_hooked.go
- core/state_processor.go
- core/vm/interface.go
> state: extra check for nano address

- cmd/geth/dbcmd.go
- core/rawdb/ancient_utils.go
- core/vm/lightclient/v2/lightclient_test.go
- eth/fetcher/block_fetcher.go
- node/node.go
There is a multiDB bug fix, better to be included in v1.5.18.
NA
NA
NA
> Merge develop to master for v1.5.18

- cmd/jsutils/getchainstatus.js
to get the slash count for a range of days.
NA
NA
NA
> jsutils: get slash count with specific step size and counter

- cmd/jsutils/getchainstatus.js
> jsutil: fix a getSlashCount issue

- ethclient/ethclient.go
- log/root_test.go
- trie/dummy_trie.go
fix some function names in comment
* ...
> chore: fix some function names in comment

- ethdb/shardingdb/shardingdb.go
support fastcache to improve sharding db read performance
* ...
> ethdb : add fastcahe for Sharding db

- core/blockchain.go
- internal/ethapi/api_mev.go
- miner/worker.go
miner: avoid to commit a bid twice
* ...
> miner: avoid to commit a bid twice
